/**
 * Attract-quality parent personas for seeding (no "demo" label in product UI).
 * Identifiable via registrationSource === SEED_PARENT_SOURCE for reset.
 */
export const SEED_PARENT_SOURCE = "seed:parent-attract-v2";

export type SeedParent = {
  email: string;
  name: string;
  phoneNumber: string;
  country: string;
  city: string;
  area: string;
  /** Indian vs overseas persona */
  region: "india" | "foreign";
};

export type SeedRequirement = {
  parentEmail: string;
  subject: string;
  classLevel: string;
  city: string;
  area: string;
  modes: ("online" | "student_home" | "tutor_home")[];
  budgetMin: number;
  budgetMax: number;
  details: string;
  startTimeline: "immediately" | "within_week" | "within_month" | "flexible";
  interestCount: number;
  postedHoursAgo: number;
};

/** 42 Indian parents — Bengaluru-focused + metro India, genuine local names & numbers */
export const INDIAN_SEED_PARENTS: SeedParent[] = [
  { email: "priya.menon84@gmail.com", name: "Priya Menon", phoneNumber: "9845192847", country: "India", city: "Bengaluru", area: "Jayanagar", region: "india" },
  { email: "rajesh.iyer.home@gmail.com", name: "Rajesh Iyer", phoneNumber: "9876548193", country: "India", city: "Bengaluru", area: "Koramangala", region: "india" },
  { email: "anjali.sharma.ind@gmail.com", name: "Anjali Sharma", phoneNumber: "9900482736", country: "India", city: "Bengaluru", area: "Indiranagar", region: "india" },
  { email: "suresh.nair.hsr@gmail.com", name: "Suresh Nair", phoneNumber: "9731846291", country: "India", city: "Bengaluru", area: "HSR Layout", region: "india" },
  { email: "meera.krishnan.wf@gmail.com", name: "Meera Krishnan", phoneNumber: "9886471835", country: "India", city: "Bengaluru", area: "Whitefield", region: "india" },
  { email: "vikram.reddy.btm@gmail.com", name: "Vikram Reddy", phoneNumber: "9611584729", country: "India", city: "Bengaluru", area: "BTM Layout", region: "india" },
  { email: "divya.patel.mallesh@gmail.com", name: "Divya Patel", phoneNumber: "9845739182", country: "India", city: "Bengaluru", area: "Malleshwaram", region: "india" },
  { email: "arun.kumar.ecity@gmail.com", name: "Arun Kumar", phoneNumber: "9900863417", country: "India", city: "Bengaluru", area: "Electronic City", region: "india" },
  { email: "lakshmi.venugopal.bsk@gmail.com", name: "Lakshmi Venugopal", phoneNumber: "9741263854", country: "India", city: "Bengaluru", area: "Banashankari", region: "india" },
  { email: "karthik.rao.hebbal@gmail.com", name: "Karthik Rao", phoneNumber: "9986429175", country: "India", city: "Bengaluru", area: "Hebbal", region: "india" },
  { email: "nisha.gupta.mhalli@gmail.com", name: "Nisha Gupta", phoneNumber: "9845372618", country: "India", city: "Bengaluru", area: "Marathahalli", region: "india" },
  { email: "amit.joshi.ylk@gmail.com", name: "Amit Joshi", phoneNumber: "9611748293", country: "India", city: "Bengaluru", area: "Yelahanka", region: "india" },
  { email: "sowmya.bhat.jp@gmail.com", name: "Sowmya Bhat", phoneNumber: "9886619472", country: "India", city: "Bengaluru", area: "JP Nagar", region: "india" },
  { email: "ravi.chandran.rtn@gmail.com", name: "Ravi Chandran", phoneNumber: "9741835269", country: "India", city: "Bengaluru", area: "RT Nagar", region: "india" },
  { email: "pooja.desai.sarjapur@gmail.com", name: "Pooja Desai", phoneNumber: "9900748163", country: "India", city: "Bengaluru", area: "Sarjapur Road", region: "india" },
  { email: "manoj.singh.basava@gmail.com", name: "Manoj Singh", phoneNumber: "9845281736", country: "India", city: "Bengaluru", area: "Basavanagudi", region: "india" },
  { email: "kavitha.suresh.rrn@gmail.com", name: "Kavitha Suresh", phoneNumber: "9731492856", country: "India", city: "Bengaluru", area: "RR Nagar", region: "india" },
  { email: "deepak.mishra.bellandur@gmail.com", name: "Deepak Mishra", phoneNumber: "9986384721", country: "India", city: "Bengaluru", area: "Bellandur", region: "india" },
  { email: "anita.fernandes.ft@gmail.com", name: "Anita Fernandes", phoneNumber: "9845618294", country: "India", city: "Bengaluru", area: "Fraser Town", region: "india" },
  { email: "sanjay.pillai.ulsoor@gmail.com", name: "Sanjay Pillai", phoneNumber: "9611927463", country: "India", city: "Bengaluru", area: "Ulsoor", region: "india" },
  { email: "rekha.iyengar.vjn@gmail.com", name: "Rekha Iyengar", phoneNumber: "9900381746", country: "India", city: "Bengaluru", area: "Vijayanagar", region: "india" },
  { email: "naveen.shetty.kundalahalli@gmail.com", name: "Naveen Shetty", phoneNumber: "9741172835", country: "India", city: "Bengaluru", area: "Kundalahalli", region: "india" },
  { email: "shweta.agarwal.baner@gmail.com", name: "Shweta Agarwal", phoneNumber: "9876291845", country: "India", city: "Pune", area: "Baner", region: "india" },
  { email: "rahul.mehta.andheri@gmail.com", name: "Rahul Mehta", phoneNumber: "9820471836", country: "India", city: "Mumbai", area: "Andheri West", region: "india" },
  { email: "neha.kapoor.saket@gmail.com", name: "Neha Kapoor", phoneNumber: "9810628473", country: "India", city: "Delhi", area: "Saket", region: "india" },
  { email: "gautam.das.saltlake@gmail.com", name: "Gautam Das", phoneNumber: "9830472916", country: "India", city: "Kolkata", area: "Salt Lake", region: "india" },
  { email: "fatima.shaikh.banjara@gmail.com", name: "Fatima Shaikh", phoneNumber: "9849183746", country: "India", city: "Hyderabad", area: "Banjara Hills", region: "india" },
  { email: "arjun.varma.adyar@gmail.com", name: "Arjun Varma", phoneNumber: "9884261837", country: "India", city: "Chennai", area: "Adyar", region: "india" },
  { email: "ishita.bose.gachibowli@gmail.com", name: "Ishita Bose", phoneNumber: "9000837461", country: "India", city: "Hyderabad", area: "Gachibowli", region: "india" },
  { email: "pranav.kulkarni.kothrud@gmail.com", name: "Pranav Kulkarni", phoneNumber: "9822618473", country: "India", city: "Pune", area: "Kothrud", region: "india" },
  { email: "sneha.thakur.powai@gmail.com", name: "Sneha Thakur", phoneNumber: "9820391847", country: "India", city: "Mumbai", area: "Powai", region: "india" },
  { email: "harish.gupta.noida62@gmail.com", name: "Harish Gupta", phoneNumber: "9811738492", country: "India", city: "Noida", area: "Sector 62", region: "india" },
  { email: "aishwarya.rao.hsr@gmail.com", name: "Aishwarya Rao", phoneNumber: "9845193746", country: "India", city: "Bengaluru", area: "HSR Layout", region: "india" },
  { email: "rohit.bansal.ggn@gmail.com", name: "Rohit Bansal", phoneNumber: "9810482736", country: "India", city: "Gurugram", area: "DLF Phase 3", region: "india" },
  { email: "tanvi.joshi.whitefield@gmail.com", name: "Tanvi Joshi", phoneNumber: "9886172849", country: "India", city: "Bengaluru", area: "Whitefield", region: "india" },
  { email: "chitra.nambiar.kalyan@gmail.com", name: "Chitra Nambiar", phoneNumber: "9845382917", country: "India", city: "Bengaluru", area: "Kalyan Nagar", region: "india" },
  { email: "venkatesh.iyer.jayanagar@gmail.com", name: "Venkatesh Iyer", phoneNumber: "9731648271", country: "India", city: "Bengaluru", area: "Jayanagar 4th Block", region: "india" },
  { email: "pallavi.shekar.hsr2@gmail.com", name: "Pallavi Shekar", phoneNumber: "9900583746", country: "India", city: "Bengaluru", area: "HSR Layout Sector 2", region: "india" },
  { email: "imran.qureshi.indir@gmail.com", name: "Imran Qureshi", phoneNumber: "9886728491", country: "India", city: "Bengaluru", area: "Indiranagar 12th Main", region: "india" },
  { email: "swati.deshmukh.koregaon@gmail.com", name: "Swati Deshmukh", phoneNumber: "9822481736", country: "India", city: "Pune", area: "Koregaon Park", region: "india" },
  { email: "abhinav.shukla.vk@gmail.com", name: "Abhinav Shukla", phoneNumber: "9810573829", country: "India", city: "Delhi", area: "Vasant Kunj", region: "india" },
  { email: "megha.rao.borivali@gmail.com", name: "Megha Rao", phoneNumber: "9820618473", country: "India", city: "Mumbai", area: "Borivali East", region: "india" },
];

/** 24 overseas parents — looking for online / India-curriculum tutors */
export const FOREIGN_SEED_PARENTS: SeedParent[] = [
  { email: "james.walker.uk92@gmail.com", name: "James Walker", phoneNumber: "+447846291057", country: "United Kingdom", city: "London", area: "Wimbledon", region: "foreign" },
  { email: "aisha.khan.sg@gmail.com", name: "Aisha Khan", phoneNumber: "+6591827463", country: "Singapore", city: "Singapore", area: "Bukit Timah", region: "foreign" },
  { email: "michael.chen.nyc@gmail.com", name: "Michael Chen", phoneNumber: "+13476829145", country: "United States", city: "New York", area: "Queens", region: "foreign" },
  { email: "emily.brown.toronto@gmail.com", name: "Emily Brown", phoneNumber: "+14168294731", country: "Canada", city: "Toronto", area: "North York", region: "foreign" },
  { email: "omar.hassan.auh@gmail.com", name: "Omar Hassan", phoneNumber: "+971554829173", country: "United Arab Emirates", city: "Abu Dhabi", area: "Al Reem Island", region: "foreign" },
  { email: "sophia.mueller.berlin@gmail.com", name: "Sophia Müller", phoneNumber: "+491768294715", country: "Germany", city: "Berlin", area: "Charlottenburg", region: "foreign" },
  { email: "daniel.okonkwo.lagos@gmail.com", name: "Daniel Okonkwo", phoneNumber: "+2348039284716", country: "Nigeria", city: "Lagos", area: "Lekki", region: "foreign" },
  { email: "priyanka.das.sydney@gmail.com", name: "Priyanka Das", phoneNumber: "+61481293746", country: "Australia", city: "Sydney", area: "Parramatta", region: "foreign" },
  { email: "thomas.nguyen.hcmc@gmail.com", name: "Thomas Nguyen", phoneNumber: "+84918274635", country: "Vietnam", city: "Ho Chi Minh City", area: "District 7", region: "foreign" },
  { email: "fatima.alrashid.riyadh@gmail.com", name: "Fatima Al-Rashid", phoneNumber: "+966508294716", country: "Saudi Arabia", city: "Riyadh", area: "Olaya", region: "foreign" },
  { email: "lucas.silva.sp@gmail.com", name: "Lucas Silva", phoneNumber: "+5511982746351", country: "Brazil", city: "São Paulo", area: "Pinheiros", region: "foreign" },
  { email: "yuki.tanaka.tokyo@gmail.com", name: "Yuki Tanaka", phoneNumber: "+819082746351", country: "Japan", city: "Tokyo", area: "Setagaya", region: "foreign" },
  { email: "amelia.scott.mcr@gmail.com", name: "Amelia Scott", phoneNumber: "+447700928473", country: "United Kingdom", city: "Manchester", area: "Didsbury", region: "foreign" },
  { email: "kevin.obrien.dublin@gmail.com", name: "Kevin O'Brien", phoneNumber: "+353872946183", country: "Ireland", city: "Dublin", area: "Rathmines", region: "foreign" },
  { email: "nina.petrov.msk@gmail.com", name: "Nina Petrov", phoneNumber: "+79038294716", country: "Russia", city: "Moscow", area: "Khamovniki", region: "foreign" },
  { email: "hassan.ali.doha@gmail.com", name: "Hassan Ali", phoneNumber: "+97455192847", country: "Qatar", city: "Doha", area: "West Bay", region: "foreign" },
  { email: "claire.dupont.paris@gmail.com", name: "Claire Dupont", phoneNumber: "+33618294735", country: "France", city: "Paris", area: "15th Arrondissement", region: "foreign" },
  { email: "rajiv.malhotra.sf@gmail.com", name: "Rajiv Malhotra", phoneNumber: "+14158294716", country: "United States", city: "San Francisco", area: "Sunset District", region: "foreign" },
  { email: "leila.benali.casa@gmail.com", name: "Leila Benali", phoneNumber: "+212661829473", country: "Morocco", city: "Casablanca", area: "Maarif", region: "foreign" },
  { email: "anders.berg.sthlm@gmail.com", name: "Anders Berg", phoneNumber: "+46708294716", country: "Sweden", city: "Stockholm", area: "Södermalm", region: "foreign" },
  { email: "maria.garcia.madrid@gmail.com", name: "María García", phoneNumber: "+34618294735", country: "Spain", city: "Madrid", area: "Chamberí", region: "foreign" },
  { email: "william.park.seoul@gmail.com", name: "William Park", phoneNumber: "+821082947163", country: "South Korea", city: "Seoul", area: "Gangnam", region: "foreign" },
  { email: "zara.ahmed.kl@gmail.com", name: "Zara Ahmed", phoneNumber: "+60123829471", country: "Malaysia", city: "Kuala Lumpur", area: "Mont Kiara", region: "foreign" },
  { email: "ethan.wilson.akl@gmail.com", name: "Ethan Wilson", phoneNumber: "+64218294716", country: "New Zealand", city: "Auckland", area: "Remuera", region: "foreign" },
];

export const ALL_SEED_PARENTS: SeedParent[] = [
  ...INDIAN_SEED_PARENTS,
  ...FOREIGN_SEED_PARENTS,
];

/** Board posts from a mix of Indian + foreign parents */
export const SEED_REQUIREMENTS: SeedRequirement[] = [
  {
    parentEmail: "priya.menon84@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 10",
    city: "Bengaluru",
    area: "Jayanagar",
    modes: ["student_home", "online"],
    budgetMin: 600,
    budgetMax: 900,
    details:
      "Looking for a patient CBSE Class 10 maths tutor for my daughter. She needs help with quadratic equations and trigonometry before board exams. Prefer evenings after 6 pm, 3 days a week.",
    startTimeline: "within_week",
    interestCount: 4,
    postedHoursAgo: 6,
  },
  {
    parentEmail: "rajesh.iyer.home@gmail.com",
    subject: "Physics",
    classLevel: "Class 12",
    city: "Bengaluru",
    area: "Koramangala",
    modes: ["online", "tutor_home"],
    budgetMin: 800,
    budgetMax: 1200,
    details:
      "Need a strong Physics faculty for JEE Main prep — optics and modern physics. Son is in Class 12. Online is fine if the tutor explains with diagrams clearly.",
    startTimeline: "immediately",
    interestCount: 7,
    postedHoursAgo: 14,
  },
  {
    parentEmail: "anjali.sharma.ind@gmail.com",
    subject: "English",
    classLevel: "Class 6",
    city: "Bengaluru",
    area: "Indiranagar",
    modes: ["student_home"],
    budgetMin: 400,
    budgetMax: 650,
    details:
      "Home tutor for Class 6 English — reading comprehension and writing. Soft-spoken tutor preferred. Twice a week near 100 Feet Road.",
    startTimeline: "flexible",
    interestCount: 2,
    postedHoursAgo: 28,
  },
  {
    parentEmail: "suresh.nair.hsr@gmail.com",
    subject: "Chemistry",
    classLevel: "Class 11",
    city: "Bengaluru",
    area: "HSR Layout",
    modes: ["online"],
    budgetMin: 700,
    budgetMax: 1000,
    details:
      "Organic chemistry basics for Class 11 CBSE. Looking for someone who can give weekly tests. Weekend mornings work best for us.",
    startTimeline: "within_week",
    interestCount: 3,
    postedHoursAgo: 9,
  },
  {
    parentEmail: "meera.krishnan.wf@gmail.com",
    subject: "Coding",
    classLevel: "Class 5",
    city: "Bengaluru",
    area: "Whitefield",
    modes: ["online"],
    budgetMin: 500,
    budgetMax: 800,
    details:
      "Want to introduce Scratch / basic Python for my Class 5 kid in a fun way — not exam coaching. 1 hour on Saturdays.",
    startTimeline: "within_month",
    interestCount: 5,
    postedHoursAgo: 40,
  },
  {
    parentEmail: "vikram.reddy.btm@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 8",
    city: "Bengaluru",
    area: "BTM Layout",
    modes: ["student_home", "tutor_home"],
    budgetMin: 450,
    budgetMax: 700,
    details:
      "Class 8 ICSE maths — algebra and geometry. Looking for a tutor who can come home Mon/Wed/Fri after school.",
    startTimeline: "immediately",
    interestCount: 6,
    postedHoursAgo: 3,
  },
  {
    parentEmail: "divya.patel.mallesh@gmail.com",
    subject: "Kannada",
    classLevel: "Class 4",
    city: "Bengaluru",
    area: "Malleshwaram",
    modes: ["student_home"],
    budgetMin: 350,
    budgetMax: 550,
    details:
      "Need help with school Kannada for Class 4. Reading and writing practice. Local tutor who knows the school syllabus preferred.",
    startTimeline: "flexible",
    interestCount: 1,
    postedHoursAgo: 55,
  },
  {
    parentEmail: "arun.kumar.ecity@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 9",
    city: "Bengaluru",
    area: "Electronic City",
    modes: ["online", "student_home"],
    budgetMin: 500,
    budgetMax: 750,
    details:
      "Class 9 CBSE maths — struggling with polynomials. Open to online if the tutor is experienced with board pattern.",
    startTimeline: "within_week",
    interestCount: 4,
    postedHoursAgo: 18,
  },
  {
    parentEmail: "lakshmi.venugopal.bsk@gmail.com",
    subject: "Science",
    classLevel: "Class 7",
    city: "Bengaluru",
    area: "Banashankari",
    modes: ["student_home"],
    budgetMin: 400,
    budgetMax: 600,
    details:
      "General science (physics + bio) for Class 7. Looking for someone who can make concepts interesting, not just notes.",
    startTimeline: "within_month",
    interestCount: 2,
    postedHoursAgo: 72,
  },
  {
    parentEmail: "karthik.rao.hebbal@gmail.com",
    subject: "Accountancy",
    classLevel: "Class 12",
    city: "Bengaluru",
    area: "Hebbal",
    modes: ["online"],
    budgetMin: 700,
    budgetMax: 1100,
    details:
      "Commerce Class 12 Accountancy — partnership and company accounts. Prefer CA / experienced faculty. Evenings IST.",
    startTimeline: "immediately",
    interestCount: 3,
    postedHoursAgo: 11,
  },
  {
    parentEmail: "nisha.gupta.mhalli@gmail.com",
    subject: "Hindi",
    classLevel: "Class 5",
    city: "Bengaluru",
    area: "Marathahalli",
    modes: ["student_home", "online"],
    budgetMin: 350,
    budgetMax: 500,
    details:
      "Hindi reading and grammar for Class 5. We're a Kannada-speaking home so need gentle pace. Twice a week.",
    startTimeline: "flexible",
    interestCount: 2,
    postedHoursAgo: 33,
  },
  {
    parentEmail: "sowmya.bhat.jp@gmail.com",
    subject: "Biology",
    classLevel: "Class 11",
    city: "Bengaluru",
    area: "JP Nagar",
    modes: ["online", "tutor_home"],
    budgetMin: 650,
    budgetMax: 950,
    details:
      "NEET foundation biology for Class 11 — cell biology and plant physiology. Looking for structured weekly plans.",
    startTimeline: "within_week",
    interestCount: 5,
    postedHoursAgo: 20,
  },
  {
    parentEmail: "pooja.desai.sarjapur@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 3",
    city: "Bengaluru",
    area: "Sarjapur Road",
    modes: ["student_home"],
    budgetMin: 300,
    budgetMax: 450,
    details:
      "Class 3 maths — tables, word problems, and confidence building. Female tutor preferred for home visits.",
    startTimeline: "within_week",
    interestCount: 3,
    postedHoursAgo: 8,
  },
  {
    parentEmail: "deepak.mishra.bellandur@gmail.com",
    subject: "Computer Science",
    classLevel: "Class 11",
    city: "Bengaluru",
    area: "Bellandur",
    modes: ["online"],
    budgetMin: 700,
    budgetMax: 1000,
    details:
      "Python and basics of data structures for Class 11 CS. Can do late evenings after 8 pm.",
    startTimeline: "flexible",
    interestCount: 4,
    postedHoursAgo: 45,
  },
  {
    parentEmail: "rahul.mehta.andheri@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 10",
    city: "Mumbai",
    area: "Andheri West",
    modes: ["online", "student_home"],
    budgetMin: 700,
    budgetMax: 1100,
    details:
      "SSC Class 10 maths — geometry and algebra. Need someone who has taken board students before. Weekend slots preferred.",
    startTimeline: "immediately",
    interestCount: 6,
    postedHoursAgo: 5,
  },
  {
    parentEmail: "neha.kapoor.saket@gmail.com",
    subject: "Economics",
    classLevel: "Class 12",
    city: "Delhi",
    area: "Saket",
    modes: ["online"],
    budgetMin: 600,
    budgetMax: 900,
    details:
      "CBSE Class 12 Economics — micro + macro revision. Looking for clear explanations and past-year paper practice.",
    startTimeline: "within_week",
    interestCount: 2,
    postedHoursAgo: 26,
  },
  {
    parentEmail: "fatima.alrashid.riyadh@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 9",
    city: "Riyadh",
    area: "Olaya",
    modes: ["online"],
    budgetMin: 800,
    budgetMax: 1400,
    details:
      "Our daughter follows CBSE via an Indian school in Riyadh. Need an online maths tutor in IST evenings for Class 9 — algebra focus. Clear Indian English preferred.",
    startTimeline: "within_week",
    interestCount: 5,
    postedHoursAgo: 12,
  },
  {
    parentEmail: "james.walker.uk92@gmail.com",
    subject: "Physics",
    classLevel: "Class 11",
    city: "London",
    area: "Wimbledon",
    modes: ["online"],
    budgetMin: 900,
    budgetMax: 1500,
    details:
      "Looking for an online Physics mentor for Class 11 (CBSE) while we are based in London. Prefer tutors experienced with board + competitive exam overlap. GMT evenings / IST mornings.",
    startTimeline: "flexible",
    interestCount: 3,
    postedHoursAgo: 36,
  },
  {
    parentEmail: "aisha.khan.sg@gmail.com",
    subject: "Chemistry",
    classLevel: "Class 10",
    city: "Singapore",
    area: "Bukit Timah",
    modes: ["online"],
    budgetMin: 750,
    budgetMax: 1200,
    details:
      "CBSE Class 10 Chemistry revision before boards — acids, bases, metals. Online only. Looking for patient teaching style.",
    startTimeline: "immediately",
    interestCount: 4,
    postedHoursAgo: 7,
  },
  {
    parentEmail: "michael.chen.nyc@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 8",
    city: "New York",
    area: "Queens",
    modes: ["online"],
    budgetMin: 700,
    budgetMax: 1100,
    details:
      "Son is in an Indian curriculum weekend programme. Need Class 8 maths support online — fractions, linear equations. US Eastern evenings.",
    startTimeline: "within_month",
    interestCount: 2,
    postedHoursAgo: 60,
  },
  {
    parentEmail: "emily.brown.toronto@gmail.com",
    subject: "English",
    classLevel: "Class 7",
    city: "Toronto",
    area: "North York",
    modes: ["online"],
    budgetMin: 600,
    budgetMax: 950,
    details:
      "Want an Indian English tutor for creative writing and grammar (Class 7 level). Helps keep connection with CBSE-style writing.",
    startTimeline: "flexible",
    interestCount: 1,
    postedHoursAgo: 48,
  },
  {
    parentEmail: "omar.hassan.auh@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 12",
    city: "Abu Dhabi",
    area: "Al Reem Island",
    modes: ["online"],
    budgetMin: 1000,
    budgetMax: 1600,
    details:
      "JEE Main maths — calculus and coordinate geometry. Looking for a serious mentor who can run 4 sessions a week online from India.",
    startTimeline: "immediately",
    interestCount: 8,
    postedHoursAgo: 4,
  },
  {
    parentEmail: "priyanka.das.sydney@gmail.com",
    subject: "Biology",
    classLevel: "Class 11",
    city: "Sydney",
    area: "Parramatta",
    modes: ["online"],
    budgetMin: 800,
    budgetMax: 1300,
    details:
      "NEET biology for Class 11 while we are in Australia. Prefer early morning IST / evening AEST slots.",
    startTimeline: "within_week",
    interestCount: 3,
    postedHoursAgo: 22,
  },
  {
    parentEmail: "rajiv.malhotra.sf@gmail.com",
    subject: "Computer Science",
    classLevel: "Class 10",
    city: "San Francisco",
    area: "Sunset District",
    modes: ["online"],
    budgetMin: 900,
    budgetMax: 1500,
    details:
      "Class 10 CS / coding fundamentals with an Indian curriculum tutor. Python preferred. Weekend US Pacific mornings.",
    startTimeline: "flexible",
    interestCount: 2,
    postedHoursAgo: 70,
  },
  {
    parentEmail: "zara.ahmed.kl@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 6",
    city: "Kuala Lumpur",
    area: "Mont Kiara",
    modes: ["online"],
    budgetMin: 500,
    budgetMax: 850,
    details:
      "Class 6 maths for a child in an international school who also follows Indian worksheets at home. Friendly online tutor, 2× week.",
    startTimeline: "within_month",
    interestCount: 2,
    postedHoursAgo: 52,
  },
  {
    parentEmail: "chitra.nambiar.kalyan@gmail.com",
    subject: "English",
    classLevel: "Class 4",
    city: "Bengaluru",
    area: "Kalyan Nagar",
    modes: ["student_home"],
    budgetMin: 350,
    budgetMax: 550,
    details:
      "Looking for a warm home tutor for Class 4 English — phonics catch-up, reading aloud, and short paragraphs. Daughter is shy so patience matters. Twice a week after 5 pm near HRBR Layout.",
    startTimeline: "within_week",
    interestCount: 2,
    postedHoursAgo: 5,
  },
  {
    parentEmail: "venkatesh.iyer.jayanagar@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 11",
    city: "Bengaluru",
    area: "Jayanagar 4th Block",
    modes: ["online", "tutor_home"],
    budgetMin: 700,
    budgetMax: 1100,
    details:
      "CBSE Class 11 maths — limits, derivatives, and trigonometry. Son needs weekly chapter tests and clear board-pattern practice. Prefer evenings or early weekend slots.",
    startTimeline: "immediately",
    interestCount: 5,
    postedHoursAgo: 2,
  },
  {
    parentEmail: "pallavi.shekar.hsr2@gmail.com",
    subject: "Science",
    classLevel: "Class 8",
    city: "Bengaluru",
    area: "HSR Layout Sector 2",
    modes: ["student_home", "online"],
    budgetMin: 450,
    budgetMax: 700,
    details:
      "Class 8 CBSE science (physics + chemistry basics). Need someone who explains with everyday examples, not only textbook notes. 3 days a week after school near 27th Main.",
    startTimeline: "within_week",
    interestCount: 3,
    postedHoursAgo: 9,
  },
  {
    parentEmail: "imran.qureshi.indir@gmail.com",
    subject: "Coding",
    classLevel: "Class 7",
    city: "Bengaluru",
    area: "Indiranagar 12th Main",
    modes: ["online"],
    budgetMin: 500,
    budgetMax: 850,
    details:
      "Want a project-based coding mentor for Class 7 — Scratch moving to beginner Python. Not exam coaching; small games and logic puzzles. One hour on weekday evenings.",
    startTimeline: "flexible",
    interestCount: 4,
    postedHoursAgo: 14,
  },
  {
    parentEmail: "swati.deshmukh.koregaon@gmail.com",
    subject: "Chemistry",
    classLevel: "Class 12",
    city: "Pune",
    area: "Koregaon Park",
    modes: ["online", "student_home"],
    budgetMin: 750,
    budgetMax: 1200,
    details:
      "Maharashtra Board Class 12 Chemistry — organic reactions and numericals. Looking for a tutor who has guided HSC students before. Prefer weekend mornings plus one weekday online session.",
    startTimeline: "immediately",
    interestCount: 6,
    postedHoursAgo: 4,
  },
  {
    parentEmail: "abhinav.shukla.vk@gmail.com",
    subject: "Physics",
    classLevel: "Class 10",
    city: "Delhi",
    area: "Vasant Kunj",
    modes: ["online"],
    budgetMin: 600,
    budgetMax: 950,
    details:
      "CBSE Class 10 Physics revision before boards — light, electricity, and magnetic effects. Need past-year paper drills and formula clarity. Online only, evenings IST.",
    startTimeline: "within_week",
    interestCount: 4,
    postedHoursAgo: 7,
  },
  {
    parentEmail: "megha.rao.borivali@gmail.com",
    subject: "Mathematics",
    classLevel: "Class 5",
    city: "Mumbai",
    area: "Borivali East",
    modes: ["student_home"],
    budgetMin: 400,
    budgetMax: 650,
    details:
      "Class 5 maths for my son — fractions, decimals, and word problems. Looking for a local home tutor who can build confidence without rushing. Twice a week after 6 pm.",
    startTimeline: "within_week",
    interestCount: 3,
    postedHoursAgo: 11,
  },
];
