/**
 * Every country a parent can pick, plus a main city when we don't have a
 * longer city list in locations.ts.
 */
export const WORLD_COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

/** Main cities for countries that don't have a longer list. */
export const CITIES_BY_WORLD_COUNTRY: Record<string, readonly string[]> = {
  Afghanistan: ["Kabul"],
  Albania: ["Tirana"],
  Algeria: ["Algiers"],
  Andorra: ["Andorra la Vella"],
  Angola: ["Luanda"],
  "Antigua and Barbuda": ["St. John's"],
  Argentina: ["Buenos Aires"],
  Armenia: ["Yerevan"],
  Austria: ["Vienna"],
  Azerbaijan: ["Baku"],
  Bahamas: ["Nassau"],
  Bahrain: ["Manama"],
  Bangladesh: ["Dhaka", "Chattogram"],
  Barbados: ["Bridgetown"],
  Belarus: ["Minsk"],
  Belgium: ["Brussels"],
  Belize: ["Belize City"],
  Benin: ["Cotonou"],
  Bhutan: ["Thimphu"],
  Bolivia: ["La Paz", "Santa Cruz"],
  "Bosnia and Herzegovina": ["Sarajevo"],
  Botswana: ["Gaborone"],
  Brazil: ["São Paulo", "Rio de Janeiro", "Brasília"],
  Brunei: ["Bandar Seri Begawan"],
  Bulgaria: ["Sofia"],
  "Burkina Faso": ["Ouagadougou"],
  Burundi: ["Gitega"],
  "Cabo Verde": ["Praia"],
  Cambodia: ["Phnom Penh"],
  Cameroon: ["Yaoundé", "Douala"],
  "Central African Republic": ["Bangui"],
  Chad: ["N'Djamena"],
  Chile: ["Santiago"],
  China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"],
  Colombia: ["Bogotá", "Medellín"],
  Comoros: ["Moroni"],
  Congo: ["Brazzaville", "Kinshasa"],
  "Costa Rica": ["San José"],
  Croatia: ["Zagreb"],
  Cuba: ["Havana"],
  Cyprus: ["Nicosia"],
  Czechia: ["Prague"],
  Denmark: ["Copenhagen"],
  Djibouti: ["Djibouti"],
  Dominica: ["Roseau"],
  "Dominican Republic": ["Santo Domingo"],
  Ecuador: ["Quito", "Guayaquil"],
  Egypt: ["Cairo", "Alexandria"],
  "El Salvador": ["San Salvador"],
  "Equatorial Guinea": ["Malabo"],
  Eritrea: ["Asmara"],
  Estonia: ["Tallinn"],
  Eswatini: ["Mbabane"],
  Ethiopia: ["Addis Ababa"],
  Fiji: ["Suva"],
  Finland: ["Helsinki"],
  France: ["Paris", "Lyon", "Marseille"],
  Gabon: ["Libreville"],
  Gambia: ["Banjul"],
  Georgia: ["Tbilisi"],
  Germany: ["Berlin", "Munich", "Frankfurt", "Hamburg"],
  Ghana: ["Accra"],
  Greece: ["Athens"],
  Grenada: ["St. George's"],
  Guatemala: ["Guatemala City"],
  Guinea: ["Conakry"],
  "Guinea-Bissau": ["Bissau"],
  Guyana: ["Georgetown"],
  Haiti: ["Port-au-Prince"],
  Honduras: ["Tegucigalpa"],
  Hungary: ["Budapest"],
  Iceland: ["Reykjavík"],
  Indonesia: ["Jakarta", "Surabaya", "Bali"],
  Iran: ["Tehran"],
  Iraq: ["Baghdad"],
  Ireland: ["Dublin", "Cork"],
  Israel: ["Tel Aviv", "Jerusalem"],
  Italy: ["Rome", "Milan"],
  Jamaica: ["Kingston"],
  Japan: ["Tokyo", "Osaka"],
  Jordan: ["Amman"],
  Kazakhstan: ["Astana", "Almaty"],
  Kenya: ["Nairobi", "Mombasa"],
  Kiribati: ["Tarawa"],
  Kuwait: ["Kuwait City"],
  Kyrgyzstan: ["Bishkek"],
  Laos: ["Vientiane"],
  Latvia: ["Riga"],
  Lebanon: ["Beirut"],
  Lesotho: ["Maseru"],
  Liberia: ["Monrovia"],
  Libya: ["Tripoli"],
  Liechtenstein: ["Vaduz"],
  Lithuania: ["Vilnius"],
  Luxembourg: ["Luxembourg"],
  Madagascar: ["Antananarivo"],
  Malawi: ["Lilongwe"],
  Malaysia: ["Kuala Lumpur", "Penang", "Johor Bahru"],
  Maldives: ["Malé"],
  Mali: ["Bamako"],
  Malta: ["Valletta"],
  "Marshall Islands": ["Majuro"],
  Mauritania: ["Nouakchott"],
  Mauritius: ["Port Louis"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey"],
  Micronesia: ["Palikir"],
  Moldova: ["Chișinău"],
  Monaco: ["Monaco"],
  Mongolia: ["Ulaanbaatar"],
  Montenegro: ["Podgorica"],
  Morocco: ["Casablanca", "Rabat"],
  Mozambique: ["Maputo"],
  Myanmar: ["Yangon", "Naypyidaw"],
  Namibia: ["Windhoek"],
  Nauru: ["Yaren"],
  Nepal: ["Kathmandu", "Pokhara"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch"],
  Nicaragua: ["Managua"],
  Niger: ["Niamey"],
  Nigeria: ["Lagos", "Abuja"],
  "North Korea": ["Pyongyang"],
  "North Macedonia": ["Skopje"],
  Norway: ["Oslo"],
  Oman: ["Muscat"],
  Pakistan: ["Karachi", "Lahore", "Islamabad"],
  Palau: ["Ngerulmud"],
  Palestine: ["Ramallah"],
  Panama: ["Panama City"],
  "Papua New Guinea": ["Port Moresby"],
  Paraguay: ["Asunción"],
  Peru: ["Lima"],
  Philippines: ["Manila", "Cebu", "Davao"],
  Poland: ["Warsaw", "Kraków"],
  Portugal: ["Lisbon", "Porto"],
  Qatar: ["Doha"],
  Romania: ["Bucharest"],
  Russia: ["Moscow", "Saint Petersburg"],
  Rwanda: ["Kigali"],
  "Saint Kitts and Nevis": ["Basseterre"],
  "Saint Lucia": ["Castries"],
  "Saint Vincent and the Grenadines": ["Kingstown"],
  Samoa: ["Apia"],
  "San Marino": ["San Marino"],
  "Sao Tome and Principe": ["São Tomé"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Dammam"],
  Senegal: ["Dakar"],
  Serbia: ["Belgrade"],
  Seychelles: ["Victoria"],
  "Sierra Leone": ["Freetown"],
  Slovakia: ["Bratislava"],
  Slovenia: ["Ljubljana"],
  "Solomon Islands": ["Honiara"],
  Somalia: ["Mogadishu"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria"],
  "South Korea": ["Seoul", "Busan"],
  "South Sudan": ["Juba"],
  Spain: ["Madrid", "Barcelona"],
  "Sri Lanka": ["Colombo", "Kandy"],
  Sudan: ["Khartoum"],
  Suriname: ["Paramaribo"],
  Sweden: ["Stockholm"],
  Switzerland: ["Zurich", "Geneva", "Bern"],
  Syria: ["Damascus"],
  Taiwan: ["Taipei"],
  Tajikistan: ["Dushanbe"],
  Tanzania: ["Dar es Salaam"],
  Thailand: ["Bangkok", "Chiang Mai"],
  "Timor-Leste": ["Dili"],
  Togo: ["Lomé"],
  Tonga: ["Nukuʻalofa"],
  "Trinidad and Tobago": ["Port of Spain"],
  Tunisia: ["Tunis"],
  Turkey: ["Istanbul", "Ankara"],
  Turkmenistan: ["Ashgabat"],
  Tuvalu: ["Funafuti"],
  Uganda: ["Kampala"],
  Ukraine: ["Kyiv"],
  Uruguay: ["Montevideo"],
  Uzbekistan: ["Tashkent"],
  Vanuatu: ["Port Vila"],
  "Vatican City": ["Vatican City"],
  Venezuela: ["Caracas"],
  Vietnam: ["Ho Chi Minh City", "Hanoi"],
  Yemen: ["Sana'a"],
  Zambia: ["Lusaka"],
  Zimbabwe: ["Harare"],
};
