import type { PythonLmsLesson } from "@/lib/python-lms/types";

export const LESSON_07: PythonLmsLesson = {
  slug: "lesson-7",
  number: 7,
  title: "Strings",
  subtitle: "Working with text",
  minutes: 60,
  goals: [
    "Read one character with an index, starting from 0",
    "Use len() and know the last index is one less than the length",
    "Change text with .upper(), .lower(), .strip() and .replace()",
    "Remember that a method gives back a new string and keep it with =",
    "Join text with +, and turn a number into text with str() first",
  ],
  canDo: "Read, measure and change text with indexing and string methods.",

  notes: [
    {
      id: "row",
      part: "Part 1 · Characters in a row",
      title: "A string is characters standing in a row",
      blocks: [
        {
          type: "lead",
          text: "A string is text. To Python, it is a row of characters, and every character has a position number called its index.",
        },
        {
          type: "p",
          text: "The counting starts at 0, not 1. In the word Python, P is at index 0, y is at index 1, and the last letter n is at index 5. Six letters, numbered 0 to 5.",
        },
        {
          type: "table",
          head: ["Character", "P", "y", "t", "h", "o", "n"],
          rows: [["Index", "0", "1", "2", "3", "4", "5"]],
        },
        {
          type: "p",
          text: "This is the same zero start you met in range(6), which visits 0, 1, 2, 3, 4, 5. Six positions, and the first one is 0.",
        },
        {
          type: "check",
          id: "c-row",
          question: 'In "Python", what is the index of the letter P?',
          options: ["1", "0", "6", "P has no index"],
          answer: 1,
          explain: "Counting starts at 0. The first character is always at index 0.",
        },
      ],
    },
    {
      id: "index",
      part: "Part 1 · Characters in a row",
      title: "Square brackets read one character",
      blocks: [
        {
          type: "p",
          text: "Put the index in square brackets after the string, or after a variable that holds it. Python gives back that one character, as a string of length 1.",
        },
        {
          type: "anatomy",
          code: "name[0]",
          parts: [
            { token: "name", label: "The variable holding the text." },
            { token: "[", label: "Square bracket. Not round brackets. Round brackets would mean a call." },
            { token: "0", label: "The **index**: which position to read." },
            { token: "]", label: "Closes the bracket." },
          ],
        },
        {
          type: "code",
          live: true,
          code: 'name = "Python"\nprint(name[0])\nprint(name[3])',
        },
        {
          type: "p",
          text: "name[0] is P. name[3] is h, the fourth letter, because the positions go 0, 1, 2, 3. Reading a character does not change name. It still holds Python.",
        },
        {
          type: "check",
          id: "c-index",
          question: 'name = "Python". What does print(name[2]) show?',
          options: ["y", "t", "h", "P"],
          answer: 1,
          explain: "P is 0, y is 1, t is 2.",
        },
      ],
    },
    {
      id: "length",
      part: "Part 1 · Characters in a row",
      title: "len() counts, the index stops one short",
      blocks: [
        {
          type: "p",
          text: "len() counts every character. len(\"Python\") is 6. The index of the last character is 5, one less than the length, because the numbering started at 0.",
        },
        {
          type: "code",
          live: true,
          code: 'name = "Python"\nprint(len(name))\nprint(name[5])',
        },
        {
          type: "compare",
          left: {
            label: "Index 6 does not exist",
            tone: "bad",
            code: 'name = "Python"\nprint(name[6])',
            output: "IndexError: string index out of range",
          },
          right: {
            label: "The last one is 5",
            tone: "good",
            code: 'name = "Python"\nprint(name[5])',
            output: "n",
          },
        },
        {
          type: "callout",
          tone: "exam",
          text: "Index and length are different. A 6-letter word has indexes 0 to 5. The last index is always len minus 1. Asking for the length as an index is IndexError.",
        },
        {
          type: "check",
          id: "c-length",
          question: 'word = "cat". Which line is an IndexError?',
          options: ["print(word[0])", "print(word[2])", "print(word[3])", "print(len(word))"],
          codeOptions: true,
          answer: 2,
          explain: "cat has 3 letters at indexes 0, 1, 2. Index 3 is past the end.",
        },
      ],
    },
    {
      id: "negative",
      part: "Part 1 · Characters in a row",
      title: "Counting from the end",
      blocks: [
        {
          type: "p",
          text: "A minus sign counts from the right. name[-1] is the last character, name[-2] is the one before it. You do not need to know the length.",
        },
        {
          type: "table",
          head: ["Character", "P", "y", "t", "h", "o", "n"],
          rows: [
            ["From the left", "0", "1", "2", "3", "4", "5"],
            ["From the right", "-6", "-5", "-4", "-3", "-2", "-1"],
          ],
        },
        {
          type: "code",
          live: true,
          code: 'name = "Python"\nprint(name[-1])\nprint(name[-2])',
        },
        {
          type: "p",
          text: "There is no -0. The right-hand count starts at -1. So the last letter is name[-1] or name[len(name) - 1]. Both give n.",
        },
        {
          type: "check",
          id: "c-negative",
          question: 'word = "hello". What is word[-1]?',
          options: ["h", "o", "l", "IndexError"],
          answer: 1,
          explain: "-1 is always the last character. The last letter of hello is o.",
        },
      ],
    },
    {
      id: "spaces",
      part: "Part 1 · Characters in a row",
      title: "Spaces and punctuation count too",
      blocks: [
        {
          type: "p",
          text: "Every character takes a position: letters, digits, spaces, commas, the exclamation mark. Hi there! is 9 characters, not 7.",
        },
        {
          type: "table",
          head: ["H", "i", "(space)", "t", "h", "e", "r", "e", "!"],
          rows: [["0", "1", "2", "3", "4", "5", "6", "7", "8"]],
        },
        {
          type: "code",
          live: true,
          code: 'text = "Hi there!"\nprint(len(text))\nprint(text[3])',
        },
        {
          type: "p",
          text: "text[2] is a space, so print shows a blank-looking line. text[3] is t. A string with nothing in it, \"\", has length 0 and no indexes at all.",
        },
        {
          type: "check",
          id: "c-spaces",
          question: 'What is len("a b")?',
          options: ["2", "3", "1", "0"],
          answer: 1,
          explain: "a, the space, and b. Three characters.",
        },
      ],
    },
    {
      id: "slice",
      part: "Part 1 · Characters in a row",
      title: "A slice is a piece of the text",
      blocks: [
        {
          type: "p",
          text: "Two numbers with a colon between them take a piece. name[0:3] starts at 0 and stops before 3, exactly like range(0, 3). The piece is Pyt.",
        },
        {
          type: "table",
          head: ["Slice", "Positions taken", "Result"],
          rows: [
            ["name[0:3]", "0, 1, 2", "Pyt"],
            ["name[2:5]", "2, 3, 4", "tho"],
            ["name[:2]", "from the start, 0 and 1", "Py"],
            ["name[2:]", "from 2 to the end", "thon"],
          ],
        },
        {
          type: "code",
          live: true,
          code: 'name = "Python"\nprint(name[0:3])\nprint(name[2:])',
        },
        {
          type: "p",
          text: "Leave out the first number to start at the beginning. Leave out the second to go to the end. A slice that runs past the end does not raise an error. It just stops at the last character.",
        },
        {
          type: "check",
          id: "c-slice",
          question: 'name = "Python". What is name[1:4]?',
          options: ["Pyt", "yth", "ytho", "yt"],
          answer: 1,
          explain: "Start at 1 (y), stop before 4. Positions 1, 2, 3 are y, t, h.",
        },
      ],
    },
    {
      id: "upper-lower",
      part: "Part 2 · String methods",
      title: ".upper() and .lower()",
      blocks: [
        {
          type: "lead",
          text: "A method is a command that belongs to a value. You write the value, a dot, the method name, and round brackets.",
        },
        {
          type: "anatomy",
          code: "name.upper()",
          parts: [
            { token: "name", label: "The string to work on." },
            { token: ".", label: "The dot connects the string to its method." },
            { token: "upper", label: "The method name. upper makes every letter a capital." },
            { token: "()", label: "Round brackets run it. Without them nothing happens." },
          ],
        },
        {
          type: "code",
          live: true,
          code: 'name = "Mia Khan"\nprint(name.upper())\nprint(name.lower())',
        },
        {
          type: "p",
          text: "Only letters change. Spaces, digits and punctuation stay as they are. \"Room 7!\".upper() is ROOM 7!.",
        },
        {
          type: "check",
          id: "c-upper",
          question: 'What does print("Hi there".upper()) show?',
          options: ["Hi there", "HI THERE", "Hi There", "hi there"],
          answer: 1,
          explain: "upper turns every letter into a capital. The space stays a space.",
        },
      ],
    },
    {
      id: "new-string",
      part: "Part 2 · String methods",
      title: "A method gives back a new string",
      blocks: [
        {
          type: "p",
          text: "Strings cannot be changed in place. name.upper() builds a new, capital version and hands it back. If you do not print it or store it, it is thrown away, and name is still the old text.",
        },
        {
          type: "compare",
          left: {
            label: "Result thrown away",
            tone: "bad",
            code: 'name = "mia"\nname.upper()\nprint(name)',
            output: "mia",
          },
          right: {
            label: "Result stored",
            tone: "good",
            code: 'name = "mia"\nname = name.upper()\nprint(name)',
            output: "MIA",
          },
        },
        {
          type: "p",
          text: "The fix is the same update you used with score = score + 5. Put the new value back into the variable: name = name.upper(). Or store it in a new name, such as loud = name.upper().",
        },
        {
          type: "check",
          id: "c-new-string",
          question: 'word = "cat", then word.upper() on its own line, then print(word). What is printed?',
          options: ["CAT", "cat", "Cat", "Nothing"],
          answer: 1,
          explain: "The capital version was made and then thrown away. word was never given a new value.",
        },
      ],
    },
    {
      id: "strip",
      part: "Part 2 · String methods",
      title: ".strip() removes spaces at the ends",
      blocks: [
        {
          type: "p",
          text: "People often type a space before or after an answer by accident. .strip() removes spaces from both ends. Spaces in the middle are left alone.",
        },
        {
          type: "code",
          live: true,
          code: 'text = "  Mia  "\nprint(len(text))\nclean = text.strip()\nprint(len(clean))\nprint(clean)',
        },
        {
          type: "p",
          text: "The raw text is 7 characters: two spaces, Mia, two spaces. After strip it is 3. \"  hi there  \".strip() is hi there. The space between the words is still there.",
        },
        {
          type: "callout",
          tone: "tip",
          text: "Use .strip() on anything typed with input() before you compare it. \"yes \" with a trailing space is not equal to \"yes\".",
        },
        {
          type: "check",
          id: "c-strip",
          question: 'What is "  hi there  ".strip()?',
          options: ['"hithere"', '"hi there"', '"  hi there"', '"hi there  "'],
          codeOptions: true,
          answer: 1,
          explain: "Both ends lose their spaces. The middle space is kept.",
        },
      ],
    },
    {
      id: "chain",
      part: "Part 2 · String methods",
      title: "Clean an answer before you test it",
      blocks: [
        {
          type: "p",
          text: "\"Yes\", \"YES\" and \" yes\" are three different strings, so answer == \"yes\" is False for all of them. Clean the answer first: strip the spaces, then make it lower case.",
        },
        {
          type: "p",
          text: "Methods can follow each other. answer.strip().lower() strips first, then lowers whatever strip gave back. Python reads the dots from left to right.",
        },
        {
          type: "code",
          live: true,
          inputs: ["  YES"],
          code: 'print("Do you like Python?")\nanswer = input()\nif answer.strip().lower() == "yes":\n    print("Great!")\nelse:\n    print("Maybe later.")',
        },
        {
          type: "p",
          text: "Try typing YES, yes, and Yes with spaces. All of them reach Great!. Without the cleaning, only the exact text yes would.",
        },
        {
          type: "check",
          id: "c-chain",
          question: 'answer is " Yes". What is answer.strip().lower()?',
          options: ['" yes"', '"Yes"', '"yes"', '"YES"'],
          codeOptions: true,
          answer: 2,
          explain: "strip removes the leading space, giving Yes. lower turns that into yes.",
        },
      ],
    },
    {
      id: "replace",
      part: "Part 2 · String methods",
      title: ".replace(old, new)",
      blocks: [
        {
          type: "p",
          text: ".replace() takes two strings: the text to find and the text to put in its place. It changes every match, not just the first.",
        },
        {
          type: "anatomy",
          code: 'msg.replace("cats", "dogs")',
          parts: [
            { token: "msg", label: "The string to search." },
            { token: '"cats"', label: "What to find." },
            { token: '"dogs"', label: "What to put instead." },
          ],
        },
        {
          type: "code",
          live: true,
          code: 'msg = "I like cats"\nprint(msg.replace("cats", "dogs"))\nprint("banana".replace("a", "o"))',
        },
        {
          type: "p",
          text: "banana becomes bonono, because all three a's are replaced. The search is case-sensitive. \"Banana\".replace(\"b\", \"c\") finds nothing, since the B is a capital, and gives back Banana unchanged. Like upper, replace gives back a new string. msg itself still says cats.",
        },
        {
          type: "check",
          id: "c-replace",
          question: 'What is "banana".replace("a", "o")?',
          options: ["bonana", "bonono", "banana", "bnn"],
          answer: 1,
          explain: "replace changes every a, not just the first one.",
        },
      ],
    },
    {
      id: "join",
      part: "Part 3 · Joining text",
      title: "+ joins, and adds no space",
      blocks: [
        {
          type: "p",
          text: "You met this in the input lesson: when both sides are strings, + joins them. It joins exactly what is there. It never adds a space for you.",
        },
        {
          type: "compare",
          left: {
            label: "No space",
            tone: "bad",
            code: 'first = "Mia"\nlast = "Khan"\nprint(first + last)',
            output: "MiaKhan",
          },
          right: {
            label: "Space joined in",
            tone: "good",
            code: 'first = "Mia"\nlast = "Khan"\nprint(first + " " + last)',
            output: "Mia Khan",
          },
        },
        {
          type: "p",
          text: "print with commas is different. print(first, last) puts a space between the items itself. + builds one new string, which you can store: full = first + \" \" + last.",
        },
        {
          type: "check",
          id: "c-join",
          question: 'What does print("Hello" + "World") show?',
          options: ["Hello World", "HelloWorld", "Hello+World", "TypeError"],
          answer: 1,
          explain: "+ joins the two strings as they are. Neither contains a space.",
        },
      ],
    },
    {
      id: "str-number",
      part: "Part 3 · Joining text",
      title: "Numbers need str() before +",
      blocks: [
        {
          type: "p",
          text: "+ will not join a string and a number. \"Age: \" + 11 is a TypeError, because Python will not guess whether you meant maths or text. Turn the number into text first with str().",
        },
        {
          type: "compare",
          left: {
            label: "String + number",
            tone: "bad",
            code: 'age = 11\nprint("Age: " + age)',
            output: 'TypeError: can only concatenate str (not "int") to str',
          },
          right: {
            label: "str() first",
            tone: "good",
            code: 'age = 11\nprint("Age: " + str(age))',
            output: "Age: 11",
          },
        },
        {
          type: "p",
          text: "str() does the opposite job of int(). int(\"11\") turns text into a number. str(11) turns a number into text. A string can also be repeated with *: \"ha\" * 3 is hahaha.",
        },
        {
          type: "code",
          live: true,
          code: 'age = 11\nprint("Age: " + str(age))\nprint("ha" * 3)\nprint("-" * 10)',
        },
        {
          type: "check",
          id: "c-str",
          question: 'Which line prints Score: 5 when score = 5?',
          options: [
            'print("Score: " + score)',
            'print("Score: " + str(score))',
            'print("Score: " + int(score))',
            'print("Score: " - score)',
          ],
          codeOptions: true,
          answer: 1,
          explain: "score is a number. str(score) turns it into text so + can join it.",
        },
      ],
    },
    {
      id: "loop",
      part: "Part 3 · Joining text",
      title: "A for loop can walk a string",
      blocks: [
        {
          type: "p",
          text: "for works on a string as well as on range. Each pass, the loop variable holds the next character, from left to right.",
        },
        {
          type: "code",
          live: true,
          code: 'for letter in "Hi!":\n    print(letter)',
        },
        {
          type: "p",
          text: "Three characters, three passes: H, then i, then !. Add an if inside and you can count things. This loop counts how many a's are in banana.",
        },
        {
          type: "code",
          live: true,
          code: 'word = "banana"\ncount = 0\nfor letter in word:\n    if letter == "a":\n        count = count + 1\nprint(count)',
        },
        {
          type: "p",
          text: "count works like the running total from the loops lesson. It is created before the loop, grows inside it, and is printed once after. banana has three a's, so it prints 3.",
        },
        {
          type: "check",
          id: "c-loop",
          question: 'How many lines does for letter in "code": print(letter) print?',
          options: ["1", "4", "5", "0"],
          answer: 1,
          explain: "code has four characters. One pass per character, one print per pass.",
        },
      ],
    },
    {
      id: "username",
      part: "Part 3 · Joining text",
      title: "Build a username",
      blocks: [
        {
          type: "p",
          text: "This is the lesson project. Ask for a first name, a last name and a favourite number. The username is the first name in lower case, the first letter of the last name in lower case, and the number.",
        },
        {
          type: "code",
          live: true,
          inputs: ["Mia", "Khan", "7"],
          code: 'print("First name?")\nfirst = input()\nprint("Last name?")\nlast = input()\nprint("Favourite number?")\nnumber = input()\nusername = first.lower() + last[0].lower() + number\nprint(username)',
        },
        {
          type: "list",
          ordered: true,
          items: [
            "first.lower() turns Mia into mia.",
            "last[0] is K, the first letter of Khan. .lower() makes it k.",
            "number came from input(), so it is already the string 7. No str() needed.",
            "+ joins the three pieces into miak7.",
          ],
        },
        {
          type: "callout",
          tone: "warn",
          text: "If the last name is left empty, last[0] is IndexError, because an empty string has no index 0. Real sign-up forms check for that before building a name.",
        },
        {
          type: "check",
          id: "c-username",
          question: 'first = "Sam", last = "Lee", number = "3". What is first.lower() + last[0].lower() + number?',
          options: ["samlee3", "saml3", "Saml3", "sam l 3"],
          answer: 1,
          explain: "sam, then l from Lee, then 3. + adds no spaces.",
        },
      ],
    },
    {
      id: "terms",
      part: "Part 4 · Revise",
      title: "Key terms",
      blocks: [
        {
          type: "terms",
          items: [
            { term: "String", meaning: "Text. A row of characters inside quotes." },
            { term: "Character", meaning: "One letter, digit, space or symbol in a string." },
            { term: "Index", meaning: "The position number of a character. The first is 0." },
            { term: "len()", meaning: "Counts the characters. The last index is len minus 1." },
            { term: "Negative index", meaning: "Counts from the right. [-1] is the last character." },
            { term: "Slice", meaning: "A piece of a string. word[0:3] takes positions 0, 1, 2." },
            { term: "Method", meaning: "A command that belongs to a value, written after a dot, such as .upper()." },
            { term: ".strip()", meaning: "Removes spaces from both ends." },
            { term: ".replace(old, new)", meaning: "Swaps every match of old for new." },
            { term: "str()", meaning: "Turns a number into text, so + can join it." },
            { term: "IndexError", meaning: "You asked for a position that does not exist." },
          ],
        },
      ],
    },
    {
      id: "exam",
      part: "Part 4 · Revise",
      title: "Exam corner",
      blocks: [
        {
          type: "lead",
          text: "Write the index numbers under the word before you answer. Most string mistakes are counting mistakes.",
        },
        {
          type: "flashcards",
          cards: [
            { q: 'What is "Python"[0]?', a: "P. The first character is index 0." },
            { q: 'What is len("Python")?', a: "6. len counts every character." },
            { q: "What is the last index of a 6-letter word?", a: "5. Always len minus 1." },
            { q: 'What happens with "Python"[6]?', a: "IndexError: string index out of range." },
            { q: 'What is "Python"[-1]?', a: "n. -1 is the last character." },
            { q: 'What is "Python"[0:3]?', a: "Pyt. Start at 0, stop before 3." },
            { q: 'name = "mia" then name.upper() alone. What is name?', a: "Still mia. The new string was not stored." },
            { q: 'What is "  hi  ".strip()?', a: "hi. Both ends lose their spaces." },
            { q: 'What is "banana".replace("a", "o")?', a: "bonono. Every match is replaced." },
            { q: 'What does "Mia" + "Khan" give?', a: "MiaKhan. + adds no space." },
            { q: 'What happens with "Age: " + 11?', a: "TypeError. Use str(11) first." },
            { q: 'What is "ha" * 3?', a: "hahaha." },
          ],
        },
        {
          type: "check",
          id: "c-exam-index",
          question: 'word = "school". Which gives the last letter?',
          options: ["word[6]", "word[5]", "word[-0]", "word[len(word)]"],
          codeOptions: true,
          answer: 1,
          explain: "school has 6 letters, at indexes 0 to 5. word[-1] would also work.",
        },
        {
          type: "check",
          id: "c-exam-method",
          question: 'msg = "Hi". Which line changes msg to HI?',
          options: ["msg.upper()", "msg = msg.upper()", "upper(msg)", "msg.upper"],
          codeOptions: true,
          answer: 1,
          explain: "upper gives back a new string. It only sticks if you store it back into msg.",
        },
      ],
    },
    {
      id: "recap",
      part: "Part 4 · Revise",
      title: "Chapter summary",
      blocks: [
        {
          type: "list",
          items: [
            "A string is a row of characters. Each one has an index, starting at 0.",
            "len() counts characters. The last index is len minus 1. Asking past the end is IndexError.",
            "[-1] is the last character. word[0:3] is a slice of positions 0, 1, 2.",
            "Spaces and punctuation are characters too.",
            ".upper(), .lower(), .strip() and .replace() give back a new string. Store it with =.",
            "+ joins strings with no space added. Numbers need str() first.",
            "for letter in word visits each character in order.",
          ],
        },
        {
          type: "callout",
          tone: "fact",
          title: "Next up",
          text: "The Examples step through indexes, methods, a string loop and the username builder. Then you print the first and last letters, shout a message, build a username and fix an IndexError.",
        },
      ],
    },
  ],

  examples: [
    {
      type: "trace",
      id: "trace-index",
      title: "First, last, and how many",
      intro: "Index 0, index -1, and len(). Say each answer before you step.",
      code: 'name = "Python"\nprint(name[0])\nprint(name[-1])\nprint(len(name))',
      steps: [
        { line: 1, note: "name holds six characters, at indexes 0 to 5." },
        { line: 2, output: "P", note: "Index 0 is the first character." },
        { line: 3, output: "n", note: "-1 counts from the right. It is the last character, the same as name[5]." },
        { line: 4, output: "6", note: "len counts characters. 6 is the count, not an index. name[6] would be IndexError." },
      ],
    },
    {
      type: "trace",
      id: "trace-methods",
      title: "Clean, shout, swap",
      intro: "Each method gives back a new string. Watch text stay the same while clean is used.",
      code: 'text = "  Hello World  "\nclean = text.strip()\nprint(clean.upper())\nprint(clean.replace("World", "Mia"))\nprint(len(text), len(clean))',
      steps: [
        { line: 1, note: "text has two spaces at each end. That is 2 + 11 + 2 = 15 characters." },
        { line: 2, note: "strip gives back Hello World without the outer spaces. It is stored in clean. text is unchanged." },
        { line: 3, output: "HELLO WORLD", note: "upper makes a capital copy and print shows it. clean itself is still Hello World." },
        { line: 4, output: "Hello Mia", note: "replace swaps World for Mia in a new string." },
        { line: 5, output: "15 11", note: "text still has its spaces, 15 characters. clean has 11." },
      ],
    },
    {
      type: "trace",
      id: "trace-loop",
      title: "A loop over the letters",
      intro: "The loop variable gets the next character on every pass.",
      code: 'word = "cab"\ncount = 0\nfor letter in word:\n    if letter == "a":\n        count = count + 1\nprint(count)',
      steps: [
        { line: 1, note: "word has three characters: c, a, b." },
        { line: 2, note: "count starts at 0, before the loop." },
        { line: 3, note: "Pass 1. letter is c." },
        { line: 4, note: "c == a is False. The add is skipped." },
        { line: 3, note: "Pass 2. letter is a." },
        { line: 4, note: "a == a is True." },
        { line: 5, note: "count becomes 1." },
        { line: 3, note: "Pass 3. letter is b." },
        { line: 4, note: "b == a is False. There are no more characters, so the loop ends." },
        { line: 6, output: "1", note: "Printed once, after the loop. There is one a in cab." },
      ],
    },
    {
      type: "trace",
      id: "trace-username",
      title: "Three pieces, one username",
      intro: "Follow each piece of the + chain.",
      code: 'first = "Mia"\nlast = "Khan"\nnumber = "7"\nusername = first.lower() + last[0].lower() + number\nprint(username)',
      steps: [
        { line: 1, note: "first holds Mia." },
        { line: 2, note: "last holds Khan. last[0] is K." },
        { line: 3, note: "number is the string 7, in quotes. That is what input() would give." },
        { line: 4, note: "mia + k + 7. All three are strings, so + joins them into miak7." },
        { line: 5, output: "miak7", note: "No spaces anywhere, because + never adds any." },
      ],
    },
    {
      type: "playground",
      id: "play-ends",
      title: "First and last letter",
      intro: "Print the first letter of the word, then the last, on two lines. Use indexes, not typed letters.",
      starter: 'word = "Python"\n# print the first letter, then the last letter\n',
      tryThis: ["The first letter is word[0]", "The last letter is word[-1]", "Change word to school and run again"],
      goal: {
        text: "With word as Python, print P then n, using square brackets.",
        check: (r, code) => r.ok && /word\s*\[/.test(code) && r.stdout.trim() === "P\nn",
        success: "Index 0 for the first, -1 for the last. It works for any word.",
      },
    },
    {
      type: "playground",
      id: "play-shout",
      title: "Shout it back",
      intro: "Read a message and print it in capital letters. Keep the keyboard answer as hello there.",
      starter: 'print("Message?")\nmessage = input()\n# print the message in capitals\n',
      inputs: "hello there",
      tryThis: ["Use .upper() on the message", "Add .strip() first in case of spaces", "Then try .replace(\" \", \"!\")"],
      goal: {
        text: "With answer hello there, print HELLO THERE.",
        check: (r, code) =>
          r.ok && /\.upper\s*\(/.test(code) && r.stdout.split("\n").map((l) => l.trim()).includes("HELLO THERE"),
        success: "upper gave back a capital copy, and print showed it.",
      },
    },
    {
      type: "playground",
      id: "play-username",
      title: "Username generator",
      intro: "The lesson project. Keep the keyboard answers as Mia, Khan and 7, one per line.",
      starter:
        'print("First name?")\nfirst = input()\nprint("Last name?")\nlast = input()\nprint("Favourite number?")\nnumber = input()\n# build the username and print it\n',
      inputs: "Mia\nKhan\n7",
      tryThis: ["first.lower() for the first part", "last[0].lower() for the initial", "+ number at the end"],
      goal: {
        text: "With Mia, Khan and 7, print miak7.",
        check: (r, code) =>
          r.ok &&
          /\.lower\s*\(/.test(code) &&
          /last\s*\[\s*0\s*\]/.test(code) &&
          r.stdout.split("\n").map((l) => l.trim()).includes("miak7"),
        success: "mia + k + 7. You built a username from three answers.",
      },
    },
    {
      type: "playground",
      id: "play-bugs",
      title: "Bug hunt: one past the end",
      intro: "This should print the last letter of Python. It crashes instead. Read the error, then fix the index.",
      starter: 'word = "Python"\nprint(word[6])',
      tryThis: ["Run it and read the last line of the error", "6 is the length, not the last index", "Use 5, or -1"],
      goal: {
        text: "Print n with no error.",
        check: (r) => r.ok && r.stdout.trim() === "n",
        success: "The last index is len minus 1. -1 always works too.",
      },
    },
  ],

  practice: [
    {
      type: "mcq",
      id: "q-first",
      level: "easy",
      skill: "Index 0",
      prompt: 'name = "Python". What does print(name[0]) show?',
      options: ["y", "P", "n", "IndexError"],
      answer: 1,
      explain: "Counting starts at 0. Index 0 is the first character.",
    },
    {
      type: "mcq",
      id: "q-len",
      level: "easy",
      skill: "len()",
      prompt: 'What does print(len("Python")) show?',
      options: ["5", "6", "7", "P"],
      answer: 1,
      explain: "len counts every character. P, y, t, h, o, n is six.",
    },
    {
      type: "mcq",
      id: "q-last-index",
      level: "medium",
      skill: "Index vs length",
      prompt: 'What is the index of the last letter in "Python"?',
      options: ["6", "5", "-6", "0"],
      answer: 1,
      explain: "Six letters are numbered 0 to 5. The last index is len minus 1.",
    },
    {
      type: "mcq",
      id: "q-out-of-range",
      level: "medium",
      skill: "IndexError",
      prompt: 'word = "cat". What happens with print(word[3])?',
      options: ["It prints t", "It prints nothing", "IndexError", "It prints cat"],
      answer: 2,
      explain: "cat has indexes 0, 1, 2. 3 is past the end.",
    },
    {
      type: "mcq",
      id: "q-negative",
      level: "easy",
      skill: "Negative index",
      prompt: 'word = "hello". What does print(word[-1]) show?',
      options: ["h", "o", "l", "IndexError"],
      answer: 1,
      explain: "-1 is the last character.",
    },
    {
      type: "fill",
      id: "q-fill-first",
      level: "easy",
      skill: "Read the first character",
      prompt: "Fill the index so the line prints the first letter of word.",
      code: "print(word[___])",
      answers: ["0"],
      mode: "code",
      placeholder: "0",
      explain: "The first character is always index 0.",
    },
    {
      type: "mcq",
      id: "q-spaces",
      level: "medium",
      skill: "Spaces count",
      prompt: 'What is len("Hi there!")?',
      options: ["7", "8", "9", "2"],
      answer: 2,
      explain: "H, i, space, t, h, e, r, e, !. Nine characters. The space and ! count.",
    },
    {
      type: "mcq",
      id: "q-upper",
      level: "easy",
      skill: ".upper()",
      prompt: 'What does print("hello".upper()) show?',
      options: ["hello", "Hello", "HELLO", "hELLO"],
      answer: 2,
      explain: "upper turns every letter into a capital.",
    },
    {
      type: "mcq",
      id: "q-not-stored",
      level: "medium",
      skill: "Methods give a new string",
      prompt: "What is printed?",
      code: 'name = "mia"\nname.upper()\nprint(name)',
      options: ["MIA", "mia", "Mia", "Nothing"],
      answer: 1,
      explain: "The capital copy was made and thrown away. name = name.upper() would keep it.",
    },
    {
      type: "mcq",
      id: "q-strip",
      level: "medium",
      skill: ".strip()",
      prompt: 'What is "  Mia  ".strip()?',
      options: ['"Mia  "', '"  Mia"', '"Mia"', '"M i a"'],
      codeOptions: true,
      answer: 2,
      explain: "strip removes spaces from both ends.",
    },
    {
      type: "mcq",
      id: "q-replace",
      level: "medium",
      skill: ".replace()",
      prompt: 'What is "banana".replace("a", "o")?',
      options: ["bonana", "bonono", "banano", "banana"],
      answer: 1,
      explain: "replace changes every match, not just the first.",
    },
    {
      type: "mcq",
      id: "q-replace-case",
      level: "hard",
      skill: "replace is case-sensitive",
      prompt: 'What is "Banana".replace("b", "c")?',
      options: ["Canana", "canana", "Banana", "Bcnana"],
      answer: 2,
      explain: "The only b is a capital B. A lower-case b is not found, so nothing changes.",
    },
    {
      type: "mcq",
      id: "q-join",
      level: "easy",
      skill: "Joining with +",
      prompt: 'What does print("Mia" + "Khan") show?',
      options: ["Mia Khan", "MiaKhan", "Mia+Khan", "TypeError"],
      answer: 1,
      explain: "+ joins exactly what is there. It adds no space.",
    },
    {
      type: "mcq",
      id: "q-type-error",
      level: "medium",
      skill: "String + number",
      prompt: 'age = 11. What happens with print("Age: " + age)?',
      options: ["Age: 11", "Age:11", "TypeError", "Age: age"],
      answer: 2,
      explain: "+ will not join a string and a number. Use str(age).",
    },
    {
      type: "fill",
      id: "q-fill-str",
      level: "medium",
      skill: "str()",
      prompt: "Fill the blank so the line prints Age: 11.",
      code: 'age = 11\nprint("Age: " + ___(age))',
      answers: ["str"],
      mode: "code",
      placeholder: "str",
      explain: "str() turns the number into text, so + can join it.",
    },
    {
      type: "fill",
      id: "q-fill-repeat",
      level: "easy",
      skill: "Repeat with *",
      prompt: "Type exactly what this prints.",
      code: 'print("ha" * 3)',
      answers: ["hahaha"],
      mode: "text",
      explain: "* repeats a string. Three copies of ha.",
    },
    {
      type: "mcq",
      id: "q-slice",
      level: "hard",
      skill: "Slices",
      prompt: 'name = "Python". What is name[0:3]?',
      options: ["Pyth", "Pyt", "yth", "Py"],
      answer: 1,
      explain: "Start at 0, stop before 3. Positions 0, 1 and 2 are P, y, t.",
    },
    {
      type: "mcq",
      id: "q-loop",
      level: "medium",
      skill: "Looping over a string",
      prompt: "How many lines does this print?",
      code: 'for letter in "code":\n    print(letter)',
      options: ["1", "4", "5", "0"],
      answer: 1,
      explain: "One pass per character. code has four.",
    },
    {
      type: "fill",
      id: "q-fill-lower",
      level: "medium",
      skill: "Clean an answer",
      prompt: "Fill the method so YES, Yes and yes all pass the test.",
      code: 'if answer.strip().___() == "yes":',
      answers: ["lower"],
      mode: "code",
      placeholder: "lower",
      explain: "lower turns every capital into a small letter, so all three become yes.",
    },
    {
      type: "order",
      id: "q-order-username",
      level: "medium",
      skill: "Order the username builder",
      prompt: "Put the lines in an order that reads two names and prints a username.",
      lines: ["first = input()", "last = input()", "username = first.lower() + last[0].lower()", "print(username)"],
      code: true,
      explain: "Both names must exist before the username line uses them. The print comes last.",
    },
    {
      type: "write",
      id: "q-write-ends",
      level: "easy",
      skill: "First and last",
      prompt:
        'word = "Python" is in the starter. Print its first letter, then its last letter, on two lines. Use indexes.\n\nOutput must be:\nP\nn',
      starter: 'word = "Python"\n',
      expected: "P\nn",
      check: (_r, code) => {
        if (!/word\s*\[/.test(code)) return "Use word[...] to read the letters, not typed text.";
        return null;
      },
      hint: "print(word[0]) then print(word[-1]).",
      solution: 'word = "Python"\nprint(word[0])\nprint(word[-1])',
    },
    {
      type: "write",
      id: "q-write-shout",
      level: "medium",
      skill: "upper and len",
      prompt:
        "Print Name? and read a name. Print it in capitals, then print how many characters it has.\n\nThe checker types:\nmia\n\nOutput must be:\nName?\nMIA\n3",
      starter: "",
      inputs: ["mia"],
      expected: "Name?\nMIA\n3",
      check: (_r, code) => {
        if (!/\.upper\s*\(/.test(code)) return "Use .upper() for the capitals.";
        if (!/len\s*\(/.test(code)) return "Use len() for the count.";
        return null;
      },
      hint: 'print("Name?"), name = input(), print(name.upper()), print(len(name)).',
      solution: 'print("Name?")\nname = input()\nprint(name.upper())\nprint(len(name))',
    },
    {
      type: "write",
      id: "q-write-replace",
      level: "medium",
      skill: ".replace()",
      prompt: 'msg = "I like cats" is in the starter. Use replace to print it with dogs instead of cats.\n\nOutput must be:\nI like dogs',
      starter: 'msg = "I like cats"\n',
      expected: "I like dogs",
      check: (_r, code) => {
        if (!/\.replace\s*\(/.test(code)) return "Use .replace(), not a new typed sentence.";
        return null;
      },
      hint: 'print(msg.replace("cats", "dogs"))',
      solution: 'msg = "I like cats"\nprint(msg.replace("cats", "dogs"))',
    },
    {
      type: "write",
      id: "q-write-username",
      level: "hard",
      skill: "Username generator",
      prompt:
        "Print First? and read a first name. Print Last? and read a last name. Print Number? and read a number. Print the username: first name in lower case, the first letter of the last name in lower case, then the number.\n\nThe checker types:\nMia\nKhan\n7\n\nOutput must be:\nFirst?\nLast?\nNumber?\nmiak7",
      starter: "",
      inputs: ["Mia", "Khan", "7"],
      expected: "First?\nLast?\nNumber?\nmiak7",
      check: (_r, code) => {
        if (!/\.lower\s*\(/.test(code)) return "Use .lower() so the username is in small letters.";
        if (!/\[\s*0\s*\]/.test(code)) return "Take the first letter of the last name with [0].";
        return null;
      },
      hint: "username = first.lower() + last[0].lower() + number",
      solution:
        'print("First?")\nfirst = input()\nprint("Last?")\nlast = input()\nprint("Number?")\nnumber = input()\nprint(first.lower() + last[0].lower() + number)',
    },
    {
      type: "write",
      id: "q-challenge",
      level: "hard",
      skill: "Mini challenge",
      challenge: true,
      prompt:
        "Build a secret message transformer.\n• Print Message? and read a message\n• Strip the spaces and make it lower case\n• Replace every e with 3, then every a with 4\n• Print the secret message, then print its length\n\nThe checker types:\nMeet at Seven\n\nOutput must be:\nMessage?\nm33t 4t s3v3n\n13",
      starter: 'print("Message?")\n',
      inputs: ["Meet at Seven"],
      expected: "Message?\nm33t 4t s3v3n\n13",
      check: (_r, code) => {
        if (!/\.lower\s*\(/.test(code)) return "Make the message lower case with .lower() first, so the capital E is caught.";
        if ((code.match(/\.replace\s*\(/g) ?? []).length < 2) return "Use .replace() twice: once for e, once for a.";
        if (!/len\s*\(/.test(code)) return "Print the length with len().";
        return null;
      },
      hint: 'secret = message.strip().lower(), then secret = secret.replace("e", "3"), then the same for a and 4.',
      solution:
        'print("Message?")\nmessage = input()\nsecret = message.strip().lower()\nsecret = secret.replace("e", "3")\nsecret = secret.replace("a", "4")\nprint(secret)\nprint(len(secret))',
    },
  ],
};
