import type { PythonLmsLesson } from "@/lib/python-lms/types";

export const LESSON_03: PythonLmsLesson = {
  slug: "lesson-3",
  number: 3,
  title: "Input & Calculations",
  subtitle: "Making programs interactive",
  minutes: 55,
  goals: [
    "Ask a question with input() and store the answer",
    "Explain why that answer is always text",
    "Convert text into a whole number with int() and a decimal with float()",
    "Calculate with +  -  *  /  and %",
    "Predict a calculation that mixes operators, including brackets",
    "Read TypeError, ValueError and ZeroDivisionError",
  ],
  canDo: "Ask for values, convert them, and calculate with all five operators.",

  notes: [
    {
      id: "why-input",
      part: "Part 1 · Asking a person",
      title: "A program that waits",
      blocks: [
        {
          type: "lead",
          text: "So far every value was written into the program before it ran. input() stops and waits for the person at the keyboard.",
        },
        {
          type: "p",
          text: "A calculator that only adds 8 and 3 is a demo. A calculator that asks for the two numbers can be used again tomorrow with different numbers. The program stays the same. The answers change.",
        },
        {
          type: "flow",
          title: "What happens at input()",
          steps: [
            { kind: "terminal", text: "Python reaches an input() line" },
            { kind: "io", text: "It shows the prompt, if you wrote one" },
            { kind: "io", text: "It waits. Nothing else runs until Enter" },
            { kind: "process", text: "The typed line comes back as text" },
            { kind: "process", text: "If you wrote name = input(), that text is stored" },
          ],
        },
        {
          type: "callout",
          tone: "fact",
          title: "The keyboard box on these slides",
          text: "When a snippet uses input(), a Keyboard box sits under the code. Each line is one answer, in order. Change a line and run again. That is the person typing.",
        },
        {
          type: "check",
          id: "c-wait",
          question: "What does the program do when it reaches input()?",
          options: [
            "It skips the line",
            "It waits for a line of text and Enter",
            "It always stores the number 0",
            "It ends the program",
          ],
          answer: 1,
          explain: "input() pauses until the person types a line and presses Enter. Later lines do not run yet.",
        },
      ],
    },
    {
      id: "anatomy",
      part: "Part 1 · Asking a person",
      title: "The shape of an input line",
      blocks: [
        {
          type: "p",
          text: "Most input lines in this chapter have three jobs: show a question, wait, and store the answer under a name.",
        },
        {
          type: "anatomy",
          code: 'name = input("Name: ")',
          parts: [
            { token: "name", label: "The **variable**. After Enter, this name holds whatever was typed." },
            { token: "=", label: "**Assignment**, same as last chapter. The right side is finished first. Here the right side is the call to input()." },
            { token: 'input("Name: ")', label: "The **call**. The text inside the brackets is the prompt. It is shown to the person. It is not the value that gets stored." },
          ],
        },
        {
          type: "p",
          text: "You can also ask with print(), then call input() with empty brackets. The question sits on its own line, which is easier to read in the output.",
        },
        {
          type: "compare",
          left: {
            label: "Prompt inside input()",
            tone: "neutral",
            code: 'name = input("Name: ")\nprint(name)',
            output: "Name: Aarav",
          },
          right: {
            label: "Question on its own line",
            tone: "good",
            code: 'print("What is your name?")\nname = input()\nprint(name)',
            output: "What is your name?\nAarav",
          },
        },
        {
          type: "callout",
          tone: "exam",
          text: "The prompt is only a label on the screen. The value is the text the person types. input(\"Age: \") does not store the word Age.",
        },
        {
          type: "check",
          id: "c-prompt",
          question: 'name = input("Name: ") and the person types Mia. What is stored in name?',
          options: ["Name: ", "Name: Mia", "Mia", "input"],
          answer: 2,
          explain: "The prompt Name: is displayed. The value returned, and stored, is Mia.",
        },
      ],
    },
    {
      id: "live-name",
      part: "Part 1 · Asking a person",
      title: "Run a question",
      blocks: [
        {
          type: "p",
          text: "Run this with the keyboard answer already filled in. Then change Aarav to your own name and run it again. The program text does not change. The stored value does.",
        },
        {
          type: "code",
          live: true,
          inputs: ["Aarav"],
          code: 'print("What is your name?")\nname = input()\nprint("Hello,", name)',
        },
        {
          type: "p",
          text: "print(\"Hello,\", name) puts a space between the greeting and the value. The comma inside the quotes is a character in the text. The comma between the two items tells print to show both.",
        },
        {
          type: "check",
          id: "c-hello",
          question: 'name holds Mia. What does print("Hello,", name) show?',
          options: ["Hello,name", "Hello, Mia", "Hello Mia", "Mia"],
          answer: 1,
          explain: "The quoted text already ends with a comma. print then adds a space and the value of name.",
        },
      ],
    },
    {
      id: "always-text",
      part: "Part 2 · Text that looks like a number",
      title: "input() always returns text",
      blocks: [
        {
          type: "lead",
          text: "This is the fact the rest of the chapter depends on. Even when the person types 12, input() gives you the string \"12\".",
        },
        {
          type: "p",
          text: "Python cannot know that you meant a number. A name, a city and an age all arrive the same way: characters, then Enter. type() reports str every time.",
        },
        {
          type: "code",
          live: true,
          inputs: ["12"],
          code: 'print("Age?")\nage = input()\nprint(age)\nprint(type(age))',
        },
        {
          type: "table",
          head: ["The person types", "What is stored", "type()"],
          rows: [
            ["Aarav", '"Aarav"', "<class 'str'>"],
            ["12", '"12"', "<class 'str'>"],
            ["5.4", '"5.4"', "<class 'str'>"],
            ["True", '"True"', "<class 'str'>"],
          ],
        },
        {
          type: "callout",
          tone: "warn",
          text: "Typing True does not create the bool True. It creates the four characters T, r, u, e. Quotes are not typed by the person. input() adds the string type for you.",
        },
        {
          type: "check",
          id: "c-always-str",
          question: "The person types 5.4 at input(). What is the type of the result?",
          options: ["float", "int", "str", "bool"],
          answer: 2,
          explain: "input() does not look at the characters and choose a type. The result is always str until you convert it.",
        },
      ],
    },
    {
      id: "crash",
      part: "Part 2 · Text that looks like a number",
      title: "Why age + 1 crashes",
      blocks: [
        {
          type: "p",
          text: "A string and a number cannot be added. \"12\" + 1 is a TypeError. Python is refusing to guess whether you meant arithmetic or text.",
        },
        {
          type: "p",
          text: "Run the program below. The keyboard answer is 12, and it still fails. Read the last line of the error before you move on.",
        },
        {
          type: "code",
          live: true,
          inputs: ["12"],
          code: 'print("Age?")\nage = input()\nprint(age + 1)',
        },
        {
          type: "compare",
          left: {
            label: "Text plus text joins",
            tone: "neutral",
            code: 'print("8" + "5")',
            output: "85",
          },
          right: {
            label: "Text plus a number crashes",
            tone: "bad",
            code: 'print("8" + 5)',
            output: "TypeError: can only concatenate str (not \"int\") to str",
          },
        },
        {
          type: "p",
          text: "If both sides are strings, + joins them. \"8\" + \"5\" is the text 85, not the number 13. That is a second trap. The program runs, and the answer is quietly wrong.",
        },
        {
          type: "check",
          id: "c-typeerror",
          question: "age = input() and the person types 11. What does age + 1 do?",
          options: ["Prints 12", "Prints 111", "Raises TypeError", "Stores 11 as an int"],
          answer: 2,
          explain: "age is the string \"11\". Adding the int 1 is not allowed, so Python raises TypeError.",
        },
      ],
    },
    {
      id: "int-convert",
      part: "Part 3 · int() and float()",
      title: "Turn text into a whole number",
      blocks: [
        {
          type: "p",
          text: "int() converts a value into an integer. int(\"12\") is the number 12. After that conversion, arithmetic works.",
        },
        {
          type: "anatomy",
          code: "age = int(input())",
          parts: [
            { token: "input()", label: "Runs first, because it is inside the brackets. Returns text, such as \"11\"." },
            { token: "int(...)", label: "Converts that text into an int. int(\"11\") is 11." },
            { token: "age =", label: "Stores the number, not the text. Later lines can do age + 1." },
          ],
        },
        {
          type: "p",
          text: "The same conversion can be two lines. age_text = input() keeps the text, then age = int(age_text) makes the number. One line, int(input()), does both. Both styles are correct.",
        },
        {
          type: "code",
          live: true,
          inputs: ["11"],
          code: 'print("How old are you?")\nage = int(input())\nprint(age + 1)',
        },
        {
          type: "p",
          text: "Change the keyboard answer from 11 to 14 and run again. The printed age next year should become 15. If it does, the conversion is doing the work.",
        },
        {
          type: "check",
          id: "c-int-input",
          question: "Which line stores a real whole number from the keyboard?",
          options: ["age = input()", "age = int(input())", 'age = "int"', "age = input(int)"],
          codeOptions: true,
          answer: 1,
          explain: "input() returns text. int() wraps that call and converts the text before it is stored.",
        },
      ],
    },
    {
      id: "int-rules",
      part: "Part 3 · int() and float()",
      title: "What int() accepts",
      blocks: [
        {
          type: "p",
          text: "int() is strict. It accepts a string of digits, optionally with spaces around them and optionally with a minus sign. It does not accept letters, a decimal point, or an empty line.",
        },
        {
          type: "table",
          head: ["Call", "Result"],
          rows: [
            ["int(\"12\")", "12"],
            ["int(\" 12 \")", "12, spaces around the digits are allowed"],
            ["int(\"-3\")", "-3"],
            ["int(\"12.5\")", "ValueError"],
            ["int(\"12 years\")", "ValueError"],
            ["int(\"\")", "ValueError, the line was empty"],
          ],
        },
        {
          type: "p",
          text: "int() can also cut the fraction off a float that is already a number. int(9.9) is 9. It does not round. 9.9 does not become 10. You will not need that often yet, but exams do ask it.",
        },
        {
          type: "code",
          live: true,
          code: "print(int(9.9))\nprint(int(2.1))\nprint(int(-3.8))",
        },
        {
          type: "callout",
          tone: "exam",
          text: "int() on a float truncates toward zero. int(9.9) is 9. int(-3.8) is -3. Rounding is a different function, round(), and it is not this chapter.",
        },
        {
          type: "check",
          id: "c-truncate",
          question: "What is int(9.9)?",
          options: ["10", "9.9", "9", "\"9\""],
          codeOptions: true,
          answer: 2,
          explain: "The decimal part is dropped. int() does not round 9.9 up to 10.",
        },
      ],
    },
    {
      id: "float-convert",
      part: "Part 3 · int() and float()",
      title: "Decimals use float()",
      blocks: [
        {
          type: "p",
          text: "A price, a height or a mark like 18.5 is not an int. float() converts text into a decimal number. float(\"12.5\") is 12.5. float(\"12\") also works: it becomes 12.0.",
        },
        {
          type: "compare",
          left: {
            label: "Whole number",
            tone: "good",
            code: 'age = int("12")\nprint(age)',
            output: "12",
          },
          right: {
            label: "Decimal number",
            tone: "good",
            code: 'price = float("12.5")\nprint(price)',
            output: "12.5",
          },
        },
        {
          type: "p",
          text: "Choosing the wrong converter is a normal mistake. int(\"12.5\") raises ValueError because of the point. float(\"12.5\") succeeds. If a question says the value might include paise, rupees and a point, or a height, use float().",
        },
        {
          type: "code",
          live: true,
          inputs: ["12.5", "4"],
          code: 'print("Price?")\nprice = float(input())\nprint("Quantity?")\nqty = int(input())\nprint(price * qty)',
        },
        {
          type: "callout",
          tone: "fact",
          title: "Why the total is 50.0",
          text: "12.5 is a float and 4 is an int. A calculation that includes a float produces a float. 12.5 * 4 is 50.0, not 50. The value is fifty. The type is float.",
        },
        {
          type: "check",
          id: "c-float",
          question: "The person will type a price such as 19.5. Which conversion is right?",
          options: ["int(input())", "float(input())", "str(input())", "input(float)"],
          codeOptions: true,
          answer: 1,
          explain: "19.5 has a decimal point, so int() would raise ValueError. float() accepts it.",
        },
      ],
    },
    {
      id: "value-error",
      part: "Part 3 · int() and float()",
      title: "ValueError means the text was the wrong shape",
      blocks: [
        {
          type: "p",
          text: "TypeError means the operation does not allow that type, such as adding text to a number. ValueError means the type is allowed, but this particular text cannot be converted.",
        },
        {
          type: "table",
          head: ["Error", "Meaning in this chapter", "Example"],
          rows: [
            ["TypeError", "The operation and the types do not match", '"12" + 1'],
            ["ValueError", "Conversion refused this text", 'int("12.5") or int("hi")'],
            ["NameError", "The name was never assigned", "print(total) before total exists"],
          ],
        },
        {
          type: "p",
          text: "When a program crashes, read the error name first. It tells you which kind of fix to try. A ValueError on int() usually means the person typed a decimal, a word, or nothing.",
        },
        {
          type: "check",
          id: "c-value",
          question: 'price = int(input()) and the person types 12.5. Which error is that?',
          options: ["TypeError", "ValueError", "NameError", "No error, price becomes 12"],
          answer: 1,
          explain: "int() does not accept a decimal point in a string. The message is ValueError. Use float() for 12.5.",
        },
      ],
    },
    {
      id: "operators",
      part: "Part 4 · The five operators",
      title: "Add, subtract, multiply, divide",
      blocks: [
        {
          type: "lead",
          text: "Once both values are numbers, the arithmetic operators do what you expect. Division has one surprise: it always produces a float.",
        },
        {
          type: "table",
          head: ["Operator", "Name", "Example", "Result"],
          rows: [
            ["+", "Add", "8 + 3", "11"],
            ["-", "Subtract", "8 - 3", "5"],
            ["*", "Multiply", "8 * 3", "24"],
            ["/", "Divide", "8 / 2", "4.0, a float"],
            ["%", "Remainder", "8 % 3", "2"],
          ],
        },
        {
          type: "p",
          text: "The star is multiplication. There is no × in Python, and writing 8 x 3 is a syntax error. The slash is division. 10 / 2 is 5.0, not 5. The .0 means the type is float even when the division comes out even.",
        },
        {
          type: "code",
          live: true,
          code: "print(8 + 3)\nprint(8 - 3)\nprint(8 * 3)\nprint(10 / 2)\nprint(7 / 2)",
        },
        {
          type: "check",
          id: "c-div-float",
          question: "What does print(10 / 2) show?",
          options: ["5", "5.0", "4", "2"],
          codeOptions: true,
          answer: 1,
          explain: "/ always produces a float. Ten divided by two is the float 5.0.",
        },
      ],
    },
    {
      id: "floor",
      part: "Part 4 · The five operators",
      title: "The whole part of a division",
      blocks: [
        {
          type: "p",
          text: "7 / 2 is 3.5. Sometimes you want only the whole number of times 2 fits into 7, which is 3. That operator is //, called floor division. This chapter’s five operators are + - * / and %. // is here so that 3.5 does not surprise you, and so you do not invent it by typing a second slash by accident.",
        },
        {
          type: "compare",
          left: {
            label: "True division /",
            tone: "neutral",
            code: "print(7 / 2)",
            output: "3.5",
          },
          right: {
            label: "Floor division //",
            tone: "neutral",
            code: "print(7 // 2)",
            output: "3",
          },
        },
        {
          type: "p",
          text: "For positive numbers, // drops the fraction. It does not round to the nearest whole number. 7 // 2 is 3, not 4. The leftover part is what % reports.",
        },
        {
          type: "code",
          live: true,
          code: "print(7 / 2)\nprint(7 // 2)\nprint(7 % 2)",
        },
        {
          type: "callout",
          tone: "tip",
          text: "Read those three lines as one idea. 2 fits into 7 three whole times, with remainder 1, and the exact quotient is 3.5.",
        },
        {
          type: "check",
          id: "c-floor",
          question: "What is 7 // 2?",
          options: ["3.5", "3", "4", "1"],
          codeOptions: true,
          answer: 1,
          explain: "// keeps the whole number of times 2 fits into 7. The fraction is dropped, so the result is 3.",
        },
      ],
    },
    {
      id: "remainder",
      part: "Part 4 · The five operators",
      title: "The remainder operator %",
      blocks: [
        {
          type: "p",
          text: "% gives the leftover after division. 17 divided by 5 is 3 groups of 5, which use up 15, and the leftover is 2. So 17 % 5 is 2.",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "17 ÷ 5 is 3 whole groups, because 5 * 3 = 15.",
            "17 - 15 = 2. That leftover is the remainder.",
            "So 17 % 5 is 2, and 17 // 5 is 3.",
          ],
        },
        {
          type: "p",
          text: "The most common use at this level is even and odd. A number is even when the remainder after dividing by 2 is 0. 8 % 2 is 0. 9 % 2 is 1.",
        },
        {
          type: "code",
          live: true,
          inputs: ["17"],
          code: 'print("Number?")\nn = int(input())\nprint(n % 5)\nprint(n % 2)',
        },
        {
          type: "callout",
          tone: "warn",
          title: "% is not percent",
          text: "In maths class, 50% means 50 out of 100. In Python, 50 % 100 is the remainder 50. Nothing in the operator means “out of 100”. If a question says “find the remainder”, the symbol is %.",
        },
        {
          type: "check",
          id: "c-mod",
          question: "What is 17 % 5?",
          options: ["3", "2", "15", "85"],
          answer: 1,
          explain: "5 * 3 = 15, and 17 - 15 = 2. The remainder is 2. 3 would be 17 // 5.",
        },
      ],
    },
    {
      id: "even",
      part: "Part 4 · The five operators",
      title: "Even, odd, and a few more remainders",
      blocks: [
        {
          type: "table",
          head: ["Expression", "Result", "Why"],
          rows: [
            ["8 % 2", "0", "8 is even. Nothing is left over."],
            ["9 % 2", "1", "9 is odd. One is left over."],
            ["10 % 3", "1", "3 * 3 = 9, and 10 - 9 = 1."],
            ["10 % 10", "0", "A multiple of 10 divides exactly."],
            ["4 % 10", "4", "4 is smaller than 10, so the remainder is 4 itself."],
          ],
        },
        {
          type: "p",
          text: "When the left number is smaller than the right, and both are positive, the remainder is the left number. 4 % 10 is 4 because 10 does not fit even once.",
        },
        {
          type: "check",
          id: "c-even",
          question: "Which expression equals 0 exactly when n is even?",
          options: ["n / 2", "n % 2", "n // 2", "n * 2"],
          codeOptions: true,
          answer: 1,
          explain: "Even means divisible by 2 with nothing left over. That is n % 2 == 0. You will write the == test in the next chapter.",
        },
      ],
    },
    {
      id: "precedence",
      part: "Part 5 · How a calculation is worked out",
      title: "Multiply and divide before add and subtract",
      blocks: [
        {
          type: "p",
          text: "Python does not simply run operators from left to right. * / // and % happen before + and -. 2 + 3 * 4 is 2 + 12, which is 14. It is not 5 * 4.",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "Brackets first. (2 + 3) * 4 becomes 5 * 4.",
            "Then *  /  //  % , from left to right.",
            "Then + and - , from left to right.",
          ],
        },
        {
          type: "code",
          live: true,
          code: "print(2 + 3 * 4)\nprint((2 + 3) * 4)\nprint(20 - 6 / 2)\nprint(8 / 2 * 3)",
        },
        {
          type: "p",
          text: "20 - 6 / 2 is 20 - 3.0, which is 17.0, because division happens first and division produces a float. 8 / 2 * 3 is left to right among the same rank: 4.0 * 3, which is 12.0. It is not 8 / 6.",
        },
        {
          type: "callout",
          tone: "exam",
          text: "If you are unsure, add brackets. (20 - 6) / 2 and 20 - (6 / 2) are different calculations. Brackets make the order visible to anyone reading the program.",
        },
        {
          type: "check",
          id: "c-prec",
          question: "What is 2 + 3 * 4?",
          options: ["20", "14", "24", "9"],
          answer: 1,
          explain: "Multiplication happens first: 3 * 4 is 12, then 2 + 12 is 14.",
        },
      ],
    },
    {
      id: "store-result",
      part: "Part 5 · How a calculation is worked out",
      title: "Store the result, then use it",
      blocks: [
        {
          type: "p",
          text: "A calculation can be stored like any other value. total = price * qty finishes the multiplication, then stores it. Later lines use total instead of repeating the formula.",
        },
        {
          type: "p",
          text: "You can also update a number with the old value, which you did in the variables chapter. score = score + 5 still works when score came from int(input()).",
        },
        {
          type: "code",
          live: true,
          inputs: ["10"],
          code: 'print("Score?")\nscore = int(input())\nscore = score + 5\nprint(score)',
        },
        {
          type: "check",
          id: "c-update",
          question: "score = int(input()) and the person types 10. Then score = score + 5. What is score?",
          options: ["10", "5", "15", "105"],
          answer: 2,
          explain: "int() makes 10 a number first. The right side is then 10 + 5, and 15 is stored back into score.",
        },
      ],
    },
    {
      id: "zero",
      part: "Part 5 · How a calculation is worked out",
      title: "You cannot divide by zero",
      blocks: [
        {
          type: "p",
          text: "10 / 0, 10 // 0 and 10 % 0 all raise ZeroDivisionError. There is no number that means “how many times does nothing fit into ten”. The program stops on that line.",
        },
        {
          type: "p",
          text: "This shows up when a second input() is 0 and you divide by it. The fix is not a different operator. The next chapter, decisions, is how a program can refuse to divide when the number is 0. For now, recognise the error and do not write a divisor of 0.",
        },
        {
          type: "callout",
          tone: "warn",
          text: "ZeroDivisionError is not a TypeError. The types are fine. The value 0 is the problem, and only for /  //  and %.",
        },
        {
          type: "check",
          id: "c-zero",
          question: "What does print(10 / 0) raise?",
          options: ["ValueError", "TypeError", "ZeroDivisionError", "It prints 0"],
          answer: 2,
          explain: "Dividing by zero is undefined. Python raises ZeroDivisionError and stops.",
        },
      ],
    },
    {
      id: "calculator",
      part: "Part 6 · A program that does a job",
      title: "Build the calculator in order",
      blocks: [
        {
          type: "p",
          text: "A small calculator is four decisions you have already made: ask, convert, calculate, print. Writing them in that order matters. You cannot convert a value that has not been read, and you cannot print a total that has not been calculated.",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "Print a question so the person knows what to type.",
            "Read with input() and convert immediately with int() or float().",
            "Do the same for the second number.",
            "Store each result you care about, or print the expression directly.",
          ],
        },
        {
          type: "code",
          live: true,
          inputs: ["8", "3"],
          code: 'print("First?")\na = int(input())\nprint("Second?")\nb = int(input())\nprint(a + b)\nprint(a - b)\nprint(a * b)\nprint(a / b)\nprint(a % b)',
        },
        {
          type: "p",
          text: "With 8 and 3 the five lines are 11, 5, 24, 2.6666666666666665 and 2. The long decimal is the exact float Python gets for 8 / 3. It is not a bug in your formula. Change the keyboard answers and the five results should all change with them.",
        },
        {
          type: "check",
          id: "c-order",
          question: "Which order is a working calculator?",
          options: [
            "Calculate, then ask, then convert",
            "Ask, convert with int() or float(), then calculate",
            "Convert, then ask, then print the prompt",
            "Print the total, then read the numbers",
          ],
          answer: 1,
          explain: "The number has to be read before it can be converted, and converted before it can be used in arithmetic.",
        },
      ],
    },
    {
      id: "bill",
      part: "Part 6 · A program that does a job",
      title: "A bill: price times quantity",
      blocks: [
        {
          type: "p",
          text: "A bill uses two different types on purpose. Quantity is a whole number of items, so int(). Price may be 12.5, so float(). The total is their product.",
        },
        {
          type: "code",
          live: true,
          inputs: ["12.5", "4"],
          code: 'print("Price?")\nprice = float(input())\nprint("Quantity?")\nqty = int(input())\ntotal = price * qty\nprint(total)',
        },
        {
          type: "p",
          text: "Walk the lines with these answers. price becomes 12.5. qty becomes 4. total becomes 50.0. print shows 50.0. If the quantity answer is changed to 1, the total becomes 12.5. If someone types 12.5 as the quantity, int() raises ValueError, because a count of items was supposed to be a whole number.",
        },
        {
          type: "callout",
          tone: "tip",
          text: "Name the variables for the fact they hold. price, qty and total are readable. a, b and c also run, and they are harder to check six weeks later.",
        },
        {
          type: "check",
          id: "c-bill",
          question: "price is 19.5 and qty is 2, computed as price * qty. What is printed?",
          options: ["21.5", "39", "39.0", "19.52"],
          codeOptions: true,
          answer: 2,
          explain: "19.5 * 2 is 39.0. Multiplication, not addition. The float stays a float.",
        },
      ],
    },
    {
      id: "first-error",
      part: "Part 6 · A program that does a job",
      title: "Python stops at the first error",
      blocks: [
        {
          type: "p",
          text: "If a program has three mistakes, you will only see the first one. Fix that line, run again, and the next error appears. That is not the program hiding bugs. Later lines have not run yet.",
        },
        {
          type: "p",
          text: "This starter fails on age + 1. After you convert age, it will fail on int() of a decimal price. After you use float(), it will fail on division by zero. The Examples step has the same hunt with a goal.",
        },
        {
          type: "list",
          items: [
            "TypeError on + usually means a string was never converted.",
            "ValueError on int() of a price usually means the text has a decimal point. Use float().",
            "ZeroDivisionError means the divisor is 0. Change that expression.",
          ],
        },
        {
          type: "check",
          id: "c-first",
          question: "A program’s first line raises TypeError, and a later line would raise ValueError. What do you see on the first run?",
          options: ["Both errors", "Only the TypeError", "Only the ValueError", "No error, Python skips both lines"],
          answer: 1,
          explain: "Execution stops at the first error. The later line has not run, so its error is not reported yet.",
        },
      ],
    },
    {
      id: "terms",
      part: "Part 7 · Revise",
      title: "Key terms",
      blocks: [
        {
          type: "terms",
          items: [
            { term: "input()", meaning: "Waits for one line from the keyboard and returns it as a string." },
            { term: "Prompt", meaning: "The text shown to the person. It is not the value that gets stored." },
            { term: "int()", meaning: "Converts a whole-number string, or truncates a float toward zero." },
            { term: "float()", meaning: "Converts text that may contain a decimal point into a float." },
            { term: "TypeError", meaning: "The operation does not allow these types. \"12\" + 1 is the usual example." },
            { term: "ValueError", meaning: "The type is right, but this text cannot be converted. int(\"12.5\") is the usual example." },
            { term: "ZeroDivisionError", meaning: "Division, floor division, or remainder with a divisor of 0." },
            { term: "/", meaning: "Division. Always produces a float. 10 / 2 is 5.0." },
            { term: "//", meaning: "Floor division. The whole number of times, for positive numbers. 7 // 2 is 3." },
            { term: "%", meaning: "Remainder after division. Not percent. 17 % 5 is 2. Even numbers give n % 2 == 0." },
          ],
        },
      ],
    },
    {
      id: "exam",
      part: "Part 7 · Revise",
      title: "Exam corner",
      blocks: [
        {
          type: "lead",
          text: "These are the questions this chapter is built to answer. Say the answer, then flip the card.",
        },
        {
          type: "flashcards",
          cards: [
            { q: "What does input() return?", a: "A string. Always. Digits are still text until you convert them." },
            { q: "What is stored by name = input(\"Name: \") if the person types Mia?", a: "Mia. The prompt is only displayed." },
            { q: "Why does age = input() then age + 1 crash when the person types 11?", a: "age is \"11\", and a string cannot be added to the int 1. TypeError." },
            { q: "What is \"8\" + \"5\"?", a: "The string 85. Both sides are text, so + joins them." },
            { q: "Write the one-line way to read a whole number.", a: "n = int(input())" },
            { q: "Why does int(\"12.5\") fail, and what should you call instead?", a: "ValueError. The point is not allowed. Use float(\"12.5\")." },
            { q: "What is int(9.9)?", a: "9. The fraction is dropped. It is not rounded." },
            { q: "What is 10 / 2, and what type is it?", a: "5.0, a float. / always returns a float." },
            { q: "What is 7 // 2 and what is 7 % 2?", a: "3 and 1. Two fits three times, with remainder 1." },
            { q: "What is 17 % 5?", a: "2. Not 3, and not 85. % is the leftover." },
            { q: "What is 2 + 3 * 4?", a: "14. Multiplication happens before addition." },
            { q: "price = 19.5 and qty = 2. What is price * qty?", a: "39.0" },
          ],
        },
        {
          type: "check",
          id: "c-exam-join",
          question: 'What does print("10" + "4") show?',
          options: ["14", "104", "10.4", "TypeError"],
          answer: 1,
          explain: "Both values are strings, so + joins the characters. The number 14 would need int(\"10\") + int(\"4\").",
        },
        {
          type: "check",
          id: "c-exam-prec",
          question: "What is 20 - 6 / 2?",
          options: ["7", "7.0", "17.0", "14"],
          codeOptions: true,
          answer: 2,
          explain: "Division first: 6 / 2 is 3.0. Then 20 - 3.0 is 17.0.",
        },
      ],
    },
    {
      id: "recap",
      part: "Part 7 · Revise",
      title: "Chapter summary",
      blocks: [
        {
          type: "list",
          items: [
            "input() waits for one line and returns a string. The prompt is display only.",
            "\"12\" + 1 raises TypeError. \"8\" + \"5\" is the text 85, not the number 13.",
            "int() makes a whole number. float() allows a decimal point. int(9.9) is 9, not 10.",
            "+ - * work as in arithmetic. / always returns a float. // is the whole part. % is the remainder, not percent.",
            "* / // % happen before + -. Brackets happen before either.",
            "A useful program asks, converts, calculates, then prints. Python shows one error at a time.",
          ],
        },
        {
          type: "callout",
          tone: "fact",
          title: "Next up",
          text: "The Examples step through the \"85\" trap, a converted age, and the operators. Then you build a greeting, a calculator and a bill. Practice checks conversion, remainder and small programs.",
        },
      ],
    },
  ],

  examples: [
    {
      type: "trace",
      id: "trace-join",
      title: "Text joins, numbers add",
      intro: "Same characters, two different operations. Step through and watch 85 become 13 only after int().",
      code: 'a = "8"\nb = "5"\nprint(a + b)\nprint(int(a) + int(b))',
      steps: [
        { line: 1, note: "a holds the string 8, not the number 8." },
        { line: 2, note: "b holds the string 5." },
        { line: 3, output: "85", note: "+ on two strings joins them. The result is the text 85." },
        { line: 4, output: "13", note: "int(a) is 8 and int(b) is 5. Those are numbers, so + adds them." },
      ],
    },
    {
      type: "trace",
      id: "trace-age",
      title: "Age next year, with a typed answer",
      intro: "The person types 11 and presses Enter. Nothing numeric exists until int() runs.",
      code: 'print("How old are you?")\nage_text = input()\nage = int(age_text)\nprint(age + 1)',
      steps: [
        { line: 1, output: "How old are you?", note: "The question is printed. The program has not read anything yet." },
        { line: 2, note: "input() waits. The person types 11. age_text becomes the string \"11\"." },
        { line: 3, note: "int(\"11\") is the number 11. age holds an int. age_text is still the string." },
        { line: 4, output: "12", note: "11 + 1 is 12. This line would have raised TypeError if it had used age_text." },
      ],
    },
    {
      type: "trace",
      id: "trace-ops",
      title: "Division, remainder, and order",
      intro: "Four short calculations. Say the result before you reveal the line.",
      code: "print(7 / 2)\nprint(7 // 2)\nprint(17 % 5)\nprint(2 + 3 * 4)",
      steps: [
        { line: 1, output: "3.5", note: "/ is true division and the result is a float." },
        { line: 2, output: "3", note: "// keeps how many whole times 2 fits into 7." },
        { line: 3, output: "2", note: "5 * 3 = 15, and 17 - 15 = 2. That leftover is %." },
        { line: 4, output: "14", note: "3 * 4 happens first. 2 + 12 is 14, not 20." },
      ],
    },
    {
      type: "playground",
      id: "play-greet",
      title: "Ask for a name and greet them",
      intro: "Run it once so you see the shape. Then change the greeting word. Leave the keyboard answer as Aarav so the goal can see the name.",
      starter: 'print("What is your name?")\nname = input()\nprint("Hello,", name)',
      inputs: "Aarav",
      tryThis: [
        "Change Hello to Hi, or to Welcome",
        "Change the keyboard answer, run, then put Aarav back",
        "Print name a second time on its own line",
      ],
      goal: {
        text: "Keep the keyboard answer as Aarav. Use input(), and make the greeting something other than Hello, Aarav.",
        check: (r, code) => r.ok && /input\s*\(/.test(code) && r.stdout.includes("Aarav") && !r.stdout.includes("Hello, Aarav"),
        success: "The name came from the keyboard, and the greeting is yours.",
      },
    },
    {
      type: "playground",
      id: "play-next",
      title: "Print the age next year",
      intro: "The starter reads text and does not add yet. Convert with int(), then print the age plus 1. Leave the keyboard answer as 11.",
      starter: 'print("How old are you?")\nage = input()\n# print the age next year\n',
      inputs: "11",
      tryThis: ["Wrap the input in int(), or convert age on the next line", "Print age + 1", "Try keyboard answer 14 and confirm the print is 15, then set it back to 11"],
      goal: {
        text: "With keyboard answer 11, the program must convert with int() and print 12.",
        check: (r, code) => r.ok && /int\s*\(/.test(code) && r.stdout.split("\n").some((line) => line.trim() === "12"),
        success: "11 was text, int() made it a number, and 11 + 1 printed 12.",
      },
    },
    {
      type: "playground",
      id: "play-calc",
      title: "Five results from two numbers",
      intro: "The starter already prints the sum, difference and product of 8 and 3. Add true division and the remainder.",
      starter: 'print("First?")\na = int(input())\nprint("Second?")\nb = int(input())\nprint(a + b)\nprint(a - b)\nprint(a * b)',
      inputs: "8\n3",
      tryThis: ["Add print(a / b)", "Add print(a % b)", "Change 3 to 0, run, read the error, then change it back"],
      goal: {
        text: "Keep the answers 8 and 3. Print 11, 5, 24, the division starting with 2.666, and the remainder 2.",
        check: (r, code) => {
          const lines = r.stdout.split("\n").map((line) => line.trim());
          return (
            r.ok &&
            /int\s*\(\s*input\s*\(/.test(code) &&
            lines.includes("11") &&
            lines.includes("5") &&
            lines.includes("24") &&
            lines.includes("2") &&
            lines.some((line) => line.startsWith("2.666"))
          );
        },
        success: "Same two numbers, five operations. The long decimal is 8 / 3 as a float.",
      },
    },
    {
      type: "playground",
      id: "play-bill",
      title: "Price times quantity",
      intro: "Price may contain a point. Quantity is a whole number. The starter does not convert, and total does not exist yet.",
      starter: 'print("Price?")\nprice = input()\nprint("Quantity?")\nqty = input()\n# store price times quantity in total\nprint(total)',
      inputs: "12.5\n4",
      tryThis: ["Convert price with float() and qty with int()", "Set total = price * qty before the print", "Leave the keyboard answers as 12.5 and 4"],
      goal: {
        text: "Keep the answers 12.5 and 4. Use float() and int(), multiply, and print 50.0 as the last line.",
        check: (r, code) =>
          r.ok &&
          /float\s*\(/.test(code) &&
          /int\s*\(/.test(code) &&
          /\*/.test(code) &&
          r.stdout.trim().split("\n").pop()?.trim() === "50.0",
        success: "12.5 * 4 is 50.0. The float stayed a float.",
      },
    },
    {
      type: "playground",
      id: "play-bugs",
      title: "Bug hunt: three errors, one at a time",
      intro: "Run it. Fix only the error Python names, then run again. The keyboard answers are 11 and then 12.5. Do not change them.",
      starter: 'print("Age?")\nage = input()\nprint(age + 1)\nprint("Price?")\nprice = int(input())\nprint(price / 0)',
      inputs: "11\n12.5",
      tryThis: [
        "The first run is TypeError. age is text, so convert it before adding 1.",
        "The next run is ValueError. 12.5 needs float(), not int().",
        "The last run is ZeroDivisionError. Divide by a real number, such as 2.",
      ],
      goal: {
        text: "Make the whole program run. Convert the age with int(), the price with float(), and do not divide by zero.",
        check: (r, code) => r.ok && /int\s*\(/.test(code) && /float\s*\(/.test(code) && !/\/\s*0\b/.test(code),
        success: "Three different errors, three different fixes. That is how a longer program gets repaired.",
      },
    },
  ],

  practice: [
    {
      type: "mcq",
      id: "q-returns",
      level: "easy",
      skill: "What input returns",
      prompt: "What does input() return?",
      options: ["An int", "A float", "A string", "Either a string or an int, depending on what was typed"],
      answer: 2,
      explain: "input() always returns text. A line of digits is still a string until int() or float() converts it.",
    },
    {
      type: "mcq",
      id: "q-stored",
      level: "easy",
      skill: "Prompt versus value",
      prompt: 'name = input("Name: ") and the person types Mia. What is stored?',
      options: ["Name:", "Name: Mia", "Mia", "input"],
      answer: 2,
      explain: "The prompt is shown on screen. The returned value is the typed line, Mia.",
    },
    {
      type: "mcq",
      id: "q-typeerror",
      level: "easy",
      skill: "Text plus a number",
      prompt: "age = input() and the person types 11. Then the program does print(age + 1). What happens?",
      options: ["It prints 12", "It prints 111", "TypeError", "ValueError"],
      answer: 2,
      explain: "age holds \"11\". Adding the number 1 to a string raises TypeError.",
    },
    {
      type: "mcq",
      id: "q-join",
      level: "medium",
      skill: "Joining strings",
      prompt: 'What does print("8" + "5") show?',
      options: ["13", "85", "8.5", "TypeError"],
      answer: 1,
      explain: "Both sides are strings, so + joins them into the text 85. The number 13 needs int() on each side.",
    },
    {
      type: "mcq",
      id: "q-which-int",
      level: "easy",
      skill: "Convert a whole number",
      prompt: "Which line stores a whole number read from the keyboard?",
      options: ["n = input()", "n = int(input())", "n = float(\"input\")", "n = input(int)"],
      codeOptions: true,
      answer: 1,
      explain: "input() is called first and returns text. int() converts that text, and the number is stored in n.",
    },
    {
      type: "fill",
      id: "q-fill-int",
      level: "easy",
      skill: "Write int()",
      prompt: "Fill the blank so age becomes a whole number.",
      code: "age = ___(input())",
      answers: ["int"],
      mode: "code",
      placeholder: "int",
      explain: "int() converts the text from input() into a whole number.",
    },
    {
      type: "fill",
      id: "q-fill-float",
      level: "easy",
      skill: "Write float()",
      prompt: "Fill the blank so price can be a decimal such as 12.5.",
      code: "price = ___(input())",
      answers: ["float"],
      mode: "code",
      placeholder: "float",
      explain: "float() accepts a decimal point. int() would raise ValueError on 12.5.",
    },
    {
      type: "mcq",
      id: "q-value",
      level: "medium",
      skill: "ValueError",
      prompt: "price = int(input()) and the person types 12.5. What happens?",
      options: ["price becomes 12", "price becomes 12.5", "ValueError", "TypeError"],
      answer: 2,
      explain: "int() refuses a string that contains a decimal point. That is ValueError. float() is the conversion that accepts 12.5.",
    },
    {
      type: "mcq",
      id: "q-truncate",
      level: "medium",
      skill: "int() on a float",
      prompt: "What is int(9.9)?",
      options: ["10", "9", "9.9", "9.0"],
      codeOptions: true,
      answer: 1,
      explain: "int() drops the fraction. It does not round 9.9 up to 10.",
    },
    {
      type: "mcq",
      id: "q-div",
      level: "medium",
      skill: "True division",
      prompt: "What does print(10 / 2) show?",
      options: ["5", "5.0", "4", "2.5"],
      codeOptions: true,
      answer: 1,
      explain: "/ always produces a float, even when the division is exact.",
    },
    {
      type: "mcq",
      id: "q-floor",
      level: "medium",
      skill: "Floor division",
      prompt: "What is 7 // 2?",
      options: ["3.5", "3", "4", "1"],
      codeOptions: true,
      answer: 1,
      explain: "2 fits into 7 three whole times. // drops the fraction instead of rounding.",
    },
    {
      type: "mcq",
      id: "q-mod",
      level: "easy",
      skill: "Remainder",
      prompt: "What is 17 % 5?",
      options: ["3", "2", "12", "85"],
      answer: 1,
      explain: "5 * 3 = 15 and the leftover is 2. % is that leftover, not the number of groups and not a percentage.",
    },
    {
      type: "fill",
      id: "q-fill-mod",
      level: "easy",
      skill: "The remainder symbol",
      prompt: "Fill the operator that gives the remainder.",
      code: "print(17 ___ 5)",
      answers: ["%"],
      mode: "code",
      placeholder: "%",
      explain: "% is the remainder operator. 17 % 5 is 2.",
    },
    {
      type: "mcq",
      id: "q-percent",
      level: "medium",
      skill: "% is not percent",
      prompt: "What is 50 % 100 in Python?",
      options: ["0.5", "50", "100", "1"],
      answer: 1,
      explain: "100 does not fit into 50 even once, so the remainder is 50. The operator does not mean percent.",
    },
    {
      type: "mcq",
      id: "q-even",
      level: "medium",
      skill: "Even numbers",
      prompt: "Which value means n is even?",
      options: ["n / 2 is 0", "n % 2 is 0", "n // 2 is 0", "n * 2 is 0"],
      answer: 1,
      explain: "Even means nothing is left over after dividing by 2. That leftover is n % 2.",
    },
    {
      type: "fill",
      id: "q-fill-mod-out",
      level: "medium",
      skill: "Predict a remainder",
      prompt: "What number is printed? Type the output only.",
      code: "print(10 % 3)",
      answers: ["1"],
      mode: "text",
      explain: "3 * 3 = 9, and 10 - 9 = 1.",
    },
    {
      type: "mcq",
      id: "q-prec",
      level: "hard",
      skill: "Operator order",
      prompt: "What is 2 + 3 * 4?",
      options: ["20", "14", "24", "9"],
      answer: 1,
      explain: "Multiplication happens before addition. 3 * 4 is 12, then 2 + 12 is 14.",
    },
    {
      type: "mcq",
      id: "q-prec-sub",
      level: "hard",
      skill: "Operator order",
      prompt: "What is 20 - 6 / 2?",
      options: ["7", "7.0", "17.0", "14.0"],
      codeOptions: true,
      answer: 2,
      explain: "6 / 2 is 3.0, and that happens first. 20 - 3.0 is 17.0.",
    },
    {
      type: "mcq",
      id: "q-zero",
      level: "medium",
      skill: "Division by zero",
      prompt: "What does 10 / 0 raise?",
      options: ["ValueError", "TypeError", "ZeroDivisionError", "It prints 0.0"],
      answer: 2,
      explain: "The types are numbers, so this is not a TypeError. Dividing by zero raises ZeroDivisionError.",
    },
    {
      type: "mcq",
      id: "q-first-error",
      level: "hard",
      skill: "One error at a time",
      prompt: "Line 2 raises TypeError. Line 6 would raise ValueError. What does the first run report?",
      options: ["Both errors", "Only the TypeError", "Only the ValueError", "Nothing, Python skips broken lines"],
      answer: 1,
      explain: "Python stops at the first error. Line 6 has not run yet.",
    },
    {
      type: "order",
      id: "q-order-age",
      level: "medium",
      skill: "Order of a conversion",
      prompt: "Put the lines in an order that asks for an age and prints the age next year.",
      lines: ['print("How old are you?")', "age = int(input())", "print(age + 1)"],
      code: true,
      explain: "Ask first, then read and convert, then calculate. Printing before the conversion would fail or show the wrong thing.",
    },
    {
      type: "order",
      id: "q-order-bill",
      level: "hard",
      skill: "Order of a bill",
      prompt: "Put the lines in an order that reads a decimal price and a whole quantity, then prints the total.",
      lines: ['print("Price?")', "price = float(input())", 'print("Quantity?")', "qty = int(input())", "print(price * qty)"],
      code: true,
      explain: "The price question comes first because price is read first. float() matches a decimal. The product cannot be printed before both numbers exist.",
    },
    {
      type: "mcq",
      id: "q-bill",
      level: "hard",
      skill: "Float times int",
      prompt: "price is the float 19.5 and qty is the int 2. What is price * qty?",
      options: ["21.5", "39", "39.0", "38"],
      codeOptions: true,
      answer: 2,
      explain: "This is multiplication, and a float in the calculation keeps the result a float. 19.5 * 2 is 39.0.",
    },
    {
      type: "write",
      id: "q-write-greet",
      level: "easy",
      skill: "Read text and print it",
      prompt:
        "Ask with the line print(\"What is your name?\"). Read the answer with input() into name. Then print Hello, and the name.\n\nThe checker types:\nMia\n\nOutput must be:\nWhat is your name?\nHello, Mia",
      starter: "",
      inputs: ["Mia"],
      expected: "What is your name?\nHello, Mia",
      check: (_r, code) => (/input\s*\(/.test(code) ? null : "Read the name with input()."),
      hint: 'print("What is your name?") then name = input() then print("Hello,", name).',
      solution: 'print("What is your name?")\nname = input()\nprint("Hello,", name)',
    },
    {
      type: "write",
      id: "q-write-age",
      level: "medium",
      skill: "Convert and add",
      prompt:
        "Print How old are you? on its own line. Read the age with int(input()). Print the age next year.\n\nThe checker types:\n11\n\nOutput must be:\nHow old are you?\n12",
      starter: 'print("How old are you?")\n',
      inputs: ["11"],
      expected: "How old are you?\n12",
      check: (_r, code) => (/int\s*\(/.test(code) ? null : "Convert the text with int() before you add."),
      hint: "age = int(input()) then print(age + 1).",
      solution: 'print("How old are you?")\nage = int(input())\nprint(age + 1)',
    },
    {
      type: "write",
      id: "q-write-mod",
      level: "medium",
      skill: "Remainder of an input",
      prompt:
        "Print Number? on its own line. Read a whole number. Print the remainder when it is divided by 2.\n\nThe checker types:\n9\n\nOutput must be:\nNumber?\n1",
      starter: "",
      inputs: ["9"],
      expected: "Number?\n1",
      check: (_r, code) => (/int\s*\(/.test(code) && /%/.test(code) ? null : "Use int() and the remainder operator %."),
      hint: "n = int(input()) then print(n % 2). 9 is odd, so the remainder is 1.",
      solution: 'print("Number?")\nn = int(input())\nprint(n % 2)',
    },
    {
      type: "write",
      id: "q-write-calc",
      level: "hard",
      skill: "Sum and product",
      prompt:
        "Print First? and read a whole number. Print Second? and read another whole number. Print their sum, then their product, on two lines.\n\nThe checker types:\n6\n7\n\nOutput must be:\nFirst?\nSecond?\n13\n42",
      starter: "",
      inputs: ["6", "7"],
      expected: "First?\nSecond?\n13\n42",
      check: (_r, code) => {
        const reads = code.match(/int\s*\(\s*input\s*\(/g);
        if (!reads || reads.length < 2) return "Read two whole numbers with int(input()).";
        if (!code.includes("+") || !code.includes("*")) return "Print a sum and a product.";
        return null;
      },
      hint: "a = int(input()) and b = int(input()), then print(a + b) and print(a * b).",
      solution: 'print("First?")\na = int(input())\nprint("Second?")\nb = int(input())\nprint(a + b)\nprint(a * b)',
    },
    {
      type: "write",
      id: "q-challenge",
      level: "hard",
      skill: "Mini challenge",
      challenge: true,
      prompt:
        "Build a bill.\n• Print Price? and read a decimal with float()\n• Print Quantity? and read a whole number with int()\n• Print the total, which is price times quantity\n\nThe checker types:\n19.5\n2\n\nThe last line of output must be 39.0, and the two questions must appear:\nPrice?\nQuantity?\n39.0",
      starter: 'print("Price?")\n',
      inputs: ["19.5", "2"],
      expected: "Price?\nQuantity?\n39.0",
      check: (_r, code) => {
        if (!/float\s*\(/.test(code)) return "Read the price with float(), because 19.5 has a decimal point.";
        if (!/int\s*\(/.test(code)) return "Read the quantity with int().";
        if (!/\*/.test(code)) return "The total is price times quantity.";
        return null;
      },
      hint: "price = float(input()) then qty = int(input()) then print(price * qty).",
      solution: 'print("Price?")\nprice = float(input())\nprint("Quantity?")\nqty = int(input())\nprint(price * qty)',
    },
  ],
};
