import type { LessonContentBank } from "./types";

export const MATH_CONTENT_2: LessonContentBank = {
  C11: {
    notes: {
      bigIdea:
        "Shapes are everywhere — in your classroom and on every screen. Count the sides and corners, and you can name any flat (2D) shape.",
      definitions: [
        { term: "2D shape", meaning: "A flat shape you can draw on paper, like a square or a circle." },
        { term: "Side", meaning: "A straight edge of a shape." },
        { term: "Corner (vertex)", meaning: "The point where two sides meet. More than one are called vertices." },
        { term: "Hexagon", meaning: "A shape with 6 sides and 6 corners — like one cell of a honeycomb." },
        { term: "Pixel", meaning: "One tiny square of light on a screen. Many pixels make a picture." },
      ],
      panels: [
        {
          title: "Count the sides",
          body: [
            "Triangle: 3 sides, 3 corners. Square: 4 equal sides.",
            "Rectangle: 4 sides — the opposite sides are equal, but not all four.",
            "Circle: one curvy line — no straight sides, no corners.",
          ],
        },
        {
          title: "More sides, new names",
          body: [
            "Pentagon = 5 sides. Hexagon = 6 sides. Octagon = 8 sides.",
            "A STOP sign is an octagon — count its 8 sides!",
            "Tip: sides and corners are always the same number in these shapes.",
          ],
        },
        {
          title: "Spot shapes in your classroom",
          body: [
            "Blackboard → rectangle. Wall clock → circle.",
            "A samosa → triangle. A carrom board → square.",
            "Look around: how many rectangles can you find in 1 minute?",
          ],
        },
        {
          title: "Shapes on screens",
          body: [
            "Every screen picture is built from tiny squares called pixels.",
            "A game house = a square + a triangle roof.",
            "Sides in that house: 4 + 3 = 7 sides altogether.",
          ],
        },
      ],
      remember: [
        "Count the sides to name the shape.",
        "Square: 4 equal sides. Rectangle: opposite sides equal.",
        "Triangle 3, pentagon 5, hexagon 6, octagon 8.",
        "A circle has no sides and no corners.",
      ],
      checkYourself: {
        q: "How many sides does a hexagon have?",
        a: "6 sides (and 6 corners) — like a honeycomb cell.",
      },
      dinoLine: "Chapter 1 done. You can name shapes by counting their sides — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "How many sides does a triangle have?",
        options: ["2", "3", "4", "5"],
        correctIndex: 1,
        explanation: "“Tri” means three — a triangle has 3 sides and 3 corners.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which shape has no straight sides and no corners?",
        options: ["Square", "Triangle", "Circle", "Rectangle"],
        correctIndex: 2,
        explanation: "A circle is one smooth curvy line, so it has no sides or corners.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "A square has 4 equal sides.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Yes! All 4 sides of a square are the same length.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "A shape with 5 sides is called a…",
        options: ["Pentagon", "Hexagon", "Octagon", "Rectangle"],
        correctIndex: 0,
        explanation: "Pentagon = 5 sides. Hexagon has 6 and octagon has 8.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "How many sides does a hexagon have?",
        options: ["4", "5", "8", "6"],
        correctIndex: 3,
        explanation: "A hexagon has 6 sides, just like a honeycomb cell.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What makes a square different from a rectangle?",
        options: [
          "A square has 3 sides",
          "A square has all 4 sides equal; a rectangle only has opposite sides equal",
          "A rectangle has curvy corners",
          "There is no difference at all",
        ],
        correctIndex: 1,
        explanation: "Both have 4 sides, but only the square has all 4 sides the same length.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A STOP sign has 8 sides. What shape is it?",
        options: ["Hexagon", "Pentagon", "Octagon", "Circle"],
        correctIndex: 2,
        explanation: "8 sides means it is an octagon.",
      },
      {
        difficulty: "medium",
        type: "true_false",
        prompt: "A triangle has 4 corners.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "A triangle has 3 sides, so it has 3 corners, not 4.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "A classroom wall has 2 square windows and 1 triangle flag. How many sides do they have altogether?",
        options: ["10", "12", "7", "11"],
        correctIndex: 3,
        explanation: "Squares: 4 + 4 = 8, triangle: 3, so 8 + 3 = 11 sides.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "How many corners do one hexagon and one triangle have altogether?",
        options: ["9", "8", "10", "12"],
        correctIndex: 0,
        explanation: "Hexagon has 6 corners, triangle has 3, so 6 + 3 = 9.",
      },
    ],
  },

  C12: {
    notes: {
      bigIdea:
        "A grid is made of rows and columns. Every point on it has an address like (2, 3) — go across first, then up. Computers use the same idea to place every pixel on a screen.",
      definitions: [
        { term: "Grid", meaning: "Lines going across and up that make rows and columns, like a chessboard." },
        { term: "Coordinates", meaning: "The address of a point, written (across, up) — for example (4, 2)." },
        { term: "x (across)", meaning: "The first number. It tells how far to go right from the start." },
        { term: "y (up)", meaning: "The second number. It tells how far to go up." },
        { term: "Origin (0, 0)", meaning: "The starting corner at the bottom left of the grid." },
      ],
      panels: [
        {
          title: "Across first, then up",
          body: [
            "Start at (0, 0), the bottom-left corner.",
            "To reach (4, 2): walk 4 across, then climb 2 up.",
            "Order matters! (4, 2) and (2, 4) are different places.",
          ],
        },
        {
          title: "Moving on the grid",
          body: [
            "Start at (1, 2). Move 3 right → add 3 to across → (4, 2).",
            "Start at (4, 1). Move 2 up → add 2 to up → (4, 3).",
            "Moving left takes away from across: (5, 3) → 1 left → (4, 3).",
          ],
        },
        {
          title: "Battleship game",
          body: [
            "Hide a ship at (3, 4) on a 5×5 grid. Your friend guesses spots.",
            "Guess (3, 4) → hit! Guess (4, 3) → miss — the numbers are swapped.",
            "Read the address carefully: across, then up.",
          ],
        },
        {
          title: "Grids inside computers",
          body: [
            "A screen is a giant grid of tiny squares called pixels.",
            "The computer colours each pixel using its address, like (120, 45).",
            "A chessboard is a grid too — 8 rows and 8 columns.",
          ],
        },
      ],
      remember: [
        "A grid has rows and columns.",
        "Address = (across, up).",
        "Across first, then up — order matters.",
        "Screens are grids of pixels.",
      ],
      checkYourself: {
        q: "Mark (4, 2) on a grid. Which number is across?",
        a: "4 is across. Start at (0, 0), go 4 across, then 2 up.",
      },
      dinoLine: "Chapter 2 done. You can find any point on a grid — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In the address (3, 5), which number tells you how far to go across?",
        options: ["3", "5", "Both", "Neither"],
        correctIndex: 0,
        explanation: "The first number is always across, so 3 is across and 5 is up.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "A grid is made of…",
        options: ["Circles only", "One long line", "Rows and columns", "Only colours"],
        correctIndex: 2,
        explanation: "A grid has rows and columns, like a chessboard.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "To find (2, 4), you go 4 across first, then 2 up.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "Across comes first: go 2 across, then 4 up.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Start at (0, 0). Go 2 across and 3 up. What is your address?",
        options: ["(3, 2)", "(2, 3)", "(5, 0)", "(2, 2)"],
        correctIndex: 1,
        explanation: "Across 2, up 3 → (2, 3).",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Start at (1, 2) and move 3 right. Where are you now?",
        options: ["(1, 5)", "(4, 5)", "(3, 2)", "(4, 2)"],
        correctIndex: 3,
        explanation: "Moving right adds to across: 1 + 3 = 4, up stays 2 → (4, 2).",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Start at (4, 1) and move 2 up. Where are you now?",
        options: ["(6, 1)", "(3, 4)", "(4, 3)", "(2, 1)"],
        correctIndex: 2,
        explanation: "Moving up adds to the second number: 1 + 2 = 3 → (4, 3).",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "In battleship, your ship is hidden at (3, 4). Your friend guesses (4, 3). Hit or miss?",
        options: [
          "Hit — the numbers are the same",
          "Miss — the order of the numbers matters",
          "Hit — it is close enough",
          "You can’t tell",
        ],
        correctIndex: 1,
        explanation: "(4, 3) means 4 across, 3 up — a different spot from (3, 4).",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A computer screen is a grid of tiny squares. What are they called?",
        options: ["Rows", "Pencils", "Dots of ink", "Pixels"],
        correctIndex: 3,
        explanation: "Pixels are the tiny squares; each one has its own address.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Start at (2, 2). Move 3 right, then 2 up, then 1 left. Where are you?",
        options: ["(4, 4)", "(5, 4)", "(3, 4)", "(4, 3)"],
        correctIndex: 0,
        explanation: "Across: 2 + 3 − 1 = 4. Up: 2 + 2 = 4. So you are at (4, 4).",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "A chess piece moves from (1, 1) to (1, 5). How did it move?",
        options: ["4 across", "5 up", "4 up", "1 up"],
        correctIndex: 2,
        explanation: "Across stayed 1. Up went from 1 to 5, so 5 − 1 = 4 up.",
      },
    ],
  },

  C13: {
    notes: {
      bigIdea:
        "A shape has line symmetry if you can fold it so both halves match exactly. Patterns repeat a small part again and again — in rangoli, floor tiles, and game art.",
      definitions: [
        { term: "Line of symmetry", meaning: "A fold line where both halves match exactly, like a mirror." },
        { term: "Symmetrical", meaning: "A shape that has at least one line of symmetry." },
        { term: "Pattern", meaning: "Something that repeats in the same order again and again." },
        { term: "Pattern unit", meaning: "The small part that repeats, like “red, blue” in red, blue, red, blue." },
      ],
      panels: [
        {
          title: "The fold test",
          body: [
            "Fold a picture on a line. Do both halves sit exactly on top? Symmetry!",
            "A heart: fold straight down the middle — both halves match.",
            "A butterfly: its two wings match across the middle line.",
          ],
        },
        {
          title: "How many fold lines?",
          body: [
            "Square: 4 lines (up-down, across, and 2 corner-to-corner).",
            "Rectangle (not a square): 2 lines — up-down and across only.",
            "Letter A: 1 line down the middle. Letter F: none.",
          ],
        },
        {
          title: "Draw the missing half",
          body: [
            "The fold line works like a mirror.",
            "A dot 2 squares left of the fold → its match is 2 squares right.",
            "Same distance from the fold, just on the other side.",
          ],
        },
        {
          title: "Patterns in rangoli and tiles",
          body: [
            "Rangoli border: star, dot, dot, star, dot, dot… The unit is “star, dot, dot”.",
            "Tiles: square, triangle, triangle, square… → 10th tile is a square.",
            "Why? The unit has 3 tiles, so tiles 1, 4, 7 and 10 are squares.",
          ],
        },
      ],
      remember: [
        "Symmetry = fold and both halves match.",
        "Square has 4 fold lines; rectangle has 2.",
        "Missing half: same distance, other side of the fold.",
        "Find the repeating unit to continue a pattern.",
      ],
      checkYourself: {
        q: "Does a heart have a line of symmetry? Draw or describe it.",
        a: "Yes — one line straight down the middle, from the top dip to the bottom point. Both halves match.",
      },
      dinoLine: "Chapter 3 done. You can find fold lines and finish patterns — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What is a line of symmetry?",
        options: [
          "Any line you draw on a shape",
          "A fold line where both halves match exactly",
          "The longest side of a shape",
          "A line with dots on it",
        ],
        correctIndex: 1,
        explanation: "Fold on the line — if both halves match, it is a line of symmetry.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "A heart has a line of symmetry.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Fold a heart straight down the middle and both halves match.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which capital letter has a line of symmetry straight down the middle?",
        options: ["F", "G", "A", "R"],
        correctIndex: 2,
        explanation: "Fold A down the middle and both sides match; F, G and R don’t.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What comes next? red, blue, red, blue, red, ___",
        options: ["Red", "Green", "Yellow", "Blue"],
        correctIndex: 3,
        explanation: "The unit “red, blue” repeats, so blue comes after red.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "How many lines of symmetry does a square have?",
        options: ["1", "2", "4", "0"],
        correctIndex: 2,
        explanation: "Up-down, across, and 2 corner-to-corner lines: 4 in total.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A rectangle that is NOT a square has how many lines of symmetry?",
        options: ["2", "4", "1", "0"],
        correctIndex: 0,
        explanation: "Only up-down and across work; corner-to-corner folds don’t match.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A rangoli border goes: star, dot, dot, star, dot, dot, star, ___, ___. What are the next two?",
        options: ["Star, star", "Dot, star", "Star, dot", "Dot, dot"],
        correctIndex: 3,
        explanation: "The unit is “star, dot, dot”, so after a star come two dots.",
      },
      {
        difficulty: "medium",
        type: "true_false",
        prompt: "If you fold a butterfly picture down the middle and the wings match, the butterfly has line symmetry.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Matching halves after a fold is exactly what line symmetry means.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "You are drawing the missing half of a picture. A dot is 2 squares to the LEFT of the fold line. Where does its matching dot go?",
        options: ["1 square right of the fold", "2 squares right of the fold", "4 squares right of the fold", "On the fold line"],
        correctIndex: 1,
        explanation: "The fold is a mirror — same distance (2 squares), other side.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Floor tiles go: square, triangle, triangle, square, triangle, triangle… What is the 10th tile?",
        options: ["Triangle", "Circle", "Square", "You can’t tell"],
        correctIndex: 2,
        explanation: "The unit has 3 tiles, so tiles 1, 4, 7 and 10 are squares.",
      },
    ],
  },

  C14: {
    notes: {
      bigIdea:
        "A turn of 90° is a quarter turn. Two quarter turns make a half turn (180°), and four make a full turn (360°) — back where you started. Robots and coding turtles turn exactly like this.",
      definitions: [
        { term: "Turn", meaning: "Changing the way you face without moving from your spot." },
        { term: "Quarter turn (90°)", meaning: "A small square-corner turn, like the minute hand going from 12 to 3." },
        { term: "Half turn (180°)", meaning: "Two quarter turns. You end up facing the opposite way." },
        { term: "Full turn (360°)", meaning: "Four quarter turns. You face the same way you started." },
        { term: "Clockwise", meaning: "The way a clock’s hands move. A right turn is clockwise." },
      ],
      panels: [
        {
          title: "Quarter, half, full",
          body: [
            "90° = quarter turn. 180° = half turn. 360° = full turn.",
            "Three quarter turns = 270° — almost all the way round.",
            "Clock hand from 12 to 3 → quarter turn. 12 to 6 → half turn.",
          ],
        },
        {
          title: "Right and left",
          body: [
            "Right turn = clockwise. Order: North → East → South → West.",
            "Left turn = anticlockwise. Order: North → West → South → East.",
            "Face east, turn left 90° → now you face north.",
          ],
        },
        {
          title: "Count the turns",
          body: [
            "Face north. 1 quarter turn right → east.",
            "2 quarter turns right → south. 3 → west.",
            "4 quarter turns → north again — a full turn!",
          ],
        },
        {
          title: "Turns in coding",
          body: [
            "In block coding, a turtle or robot obeys “turn right 90”.",
            "It spins on its spot — it does not walk.",
            "You’ll use this in the next chapter to draw shapes!",
          ],
        },
      ],
      remember: [
        "90° = quarter, 180° = half, 360° = full.",
        "Four quarter turns bring you back.",
        "Right turn = clockwise: N → E → S → W.",
        "A turn changes where you face, not where you stand.",
      ],
      checkYourself: {
        q: "You face north. Two quarter-turns right. Which way now?",
        a: "South. North → east (1 turn) → south (2 turns). That is a half turn.",
      },
      dinoLine: "Chapter 4 done. You can turn like a coding turtle — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "A quarter turn is how many degrees?",
        options: ["45°", "90°", "180°", "360°"],
        correctIndex: 1,
        explanation: "A quarter turn is 90° — one square corner.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "A half turn is…",
        options: ["90°", "360°", "180°", "100°"],
        correctIndex: 2,
        explanation: "Two quarter turns: 90° + 90° = 180°.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "Four quarter turns bring you all the way round, facing the same way as before.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "4 × 90° = 360°, a full turn.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "You face north and make one quarter turn right. Which way do you face now?",
        options: ["West", "South", "North", "East"],
        correctIndex: 3,
        explanation: "Right is clockwise: north → east.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "You face north. You make two quarter turns right. Which way now?",
        options: ["South", "East", "West", "North"],
        correctIndex: 0,
        explanation: "North → east → south. Two quarter turns is a half turn.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "You face east. You make one quarter turn left. Which way now?",
        options: ["South", "North", "West", "East"],
        correctIndex: 1,
        explanation: "Left is anticlockwise: east → north.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A full turn is 360°. How many quarter turns is that?",
        options: ["2", "3", "4", "8"],
        correctIndex: 2,
        explanation: "90° + 90° + 90° + 90° = 360°, so 4 quarter turns.",
      },
      {
        difficulty: "medium",
        type: "true_false",
        prompt: "“Turn right 90°” is a quarter turn anticlockwise.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "A right turn is clockwise, the same way a clock’s hands move.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "You face north. You make three quarter turns right. Which way now?",
        options: ["East", "South", "North", "West"],
        correctIndex: 3,
        explanation: "North → east → south → west after 3 right turns.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "A clock’s minute hand moves from 12 to 9, going clockwise. How much has it turned?",
        options: ["Three quarter turns (270°)", "One quarter turn (90°)", "A half turn (180°)", "A full turn (360°)"],
        correctIndex: 0,
        explanation: "12 → 3 → 6 → 9 is 3 quarter turns: 90° × 3 = 270°.",
      },
    ],
  },

  C15: {
    notes: {
      bigIdea:
        "You can draw a shape by giving a turtle simple commands: “forward 4” and “turn right 90”. A list of commands is a tiny program — change one number and you change the drawing.",
      definitions: [
        { term: "Command", meaning: "One clear instruction, like “forward 4” or “turn right 90”." },
        { term: "Forward N", meaning: "Walk N steps straight ahead, drawing a line." },
        { term: "Turn right 90", meaning: "Spin a quarter turn clockwise on the spot. No line is drawn." },
        { term: "Repeat N", meaning: "Do the same commands N times — saves writing them again." },
        { term: "Program", meaning: "A list of commands a computer follows in order." },
      ],
      panels: [
        {
          title: "Step 1 · Draw a square",
          body: [
            "Commands: forward 4, turn right 90.",
            "Do it 4 times → 4 equal sides and 4 corners. A square!",
            "Short way: repeat 4 [forward 4, turn right 90].",
          ],
        },
        {
          title: "Step 2 · Change one number",
          body: [
            "Want a bigger square? Change forward 4 → forward 8.",
            "Keep turn right 90 — squares always need 90° corners.",
            "Path length: 4 sides × 4 steps = 16 steps. With forward 8 → 32 steps.",
          ],
        },
        {
          title: "Step 3 · Try a rectangle",
          body: [
            "Long side 6, short side 3.",
            "repeat 2 [forward 6, turn right 90, forward 3, turn right 90].",
            "Path length: 6 + 3 + 6 + 3 = 18 steps.",
          ],
        },
        {
          title: "Step 4 · Plus sign and fixing bugs",
          body: [
            "Plus sign from the middle: repeat 4 [forward 2, back 2, turn right 90] → 4 arms.",
            "Broken square with only 3 sides? Add one more “forward 4”.",
            "Check each command in order, like debugging a program.",
          ],
        },
      ],
      remember: [
        "Square = repeat 4 [forward, turn right 90].",
        "Change the forward number to change the size.",
        "Turning spins; forward draws.",
        "Commands in order = a tiny program.",
      ],
      checkYourself: {
        q: "Write the commands to draw a square of 4 steps a side.",
        a: "Forward 4, turn right 90 — do it 4 times. Short way: repeat 4 [forward 4, turn right 90].",
      },
      dinoLine: "Chapter 5 done and Unit 3 complete. You drew shapes with commands — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which commands draw a square?",
        options: [
          "Forward 4 — repeat 4 times",
          "Forward 4, turn right 90 — repeat 4 times",
          "Turn right 90 — repeat 2 times",
          "Forward 4, turn right 45 — repeat 4 times",
        ],
        correctIndex: 1,
        explanation: "A square needs 4 equal sides with a 90° turn after each one.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In the command “forward 5”, what does the 5 tell the turtle?",
        options: ["How far to walk — 5 steps", "How many turns to make", "Which colour to use", "How fast to go"],
        correctIndex: 0,
        explanation: "The number after forward is how many steps to walk.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "A list of drawing commands followed in order is like a tiny program.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "A program is just commands a computer follows in order.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "How many times must you do “forward 3, turn right 90” to finish a square?",
        options: ["3", "2", "6", "4"],
        correctIndex: 3,
        explanation: "A square has 4 sides, so you do it 4 times.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Your square uses “forward 4”. What should you change to make a bigger square?",
        options: ["Change turn right 90 to turn right 45", "Change repeat 4 to repeat 2", "Change forward 4 to forward 8", "Change nothing"],
        correctIndex: 2,
        explanation: "Only the side length changes; the 90° turns and repeat 4 stay the same.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "The turtle runs: repeat 4 [forward 4, turn right 90]. How many steps does it walk in total?",
        options: ["16", "8", "12", "20"],
        correctIndex: 0,
        explanation: "4 sides × 4 steps = 16 steps.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A script says: forward 4, turn right 90, forward 4, turn right 90, forward 4, turn right 90. It draws only 3 sides. How do you fix it?",
        options: ["Add one more turn left 90", "Add one more forward 4", "Add a forward 8", "Nothing is wrong"],
        correctIndex: 1,
        explanation: "The square is missing its 4th side, so add one more forward 4.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which commands draw a rectangle 6 steps long and 3 steps tall?",
        options: [
          "repeat 4 [forward 6, turn right 90]",
          "repeat 4 [forward 3, turn right 90]",
          "repeat 2 [forward 6, forward 3]",
          "repeat 2 [forward 6, turn right 90, forward 3, turn right 90]",
        ],
        correctIndex: 3,
        explanation: "A rectangle needs a long side, a turn, a short side, a turn — done 2 times.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "The turtle runs: repeat 2 [forward 6, turn right 90, forward 3, turn right 90]. How many steps does it walk?",
        options: ["9", "18", "12", "24"],
        correctIndex: 1,
        explanation: "6 + 3 + 6 + 3 = 18 steps.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "A turtle faces north. It runs “forward 2, turn right 90” two times. Which way does it face now?",
        options: ["North", "East", "South", "West"],
        correctIndex: 2,
        explanation: "Two right turns: north → east → south.",
      },
    ],
  },

  C16: {
    notes: {
      bigIdea:
        "An estimate is a sensible guess. Guess first, check with a clue, then improve — just like programmers test and fix their code. A wrong first guess is fine; it helps you get closer.",
      definitions: [
        { term: "Estimate", meaning: "A sensible guess that is close to the real answer." },
        { term: "Guess-check-improve", meaning: "Guess, check if it is too big or too small, then guess again better." },
        { term: "Clue", meaning: "A hint like “too small” or “too big” that helps you improve." },
        { term: "Debugging", meaning: "Finding and fixing mistakes in a program by testing again and again." },
      ],
      panels: [
        {
          title: "Sensible, not wild",
          body: [
            "A pencil is about 15 cm long — not 15 m, not 1 cm.",
            "A school bus holds about 40 children — not 4, not 4,000.",
            "Use things you know to make a good guess.",
          ],
        },
        {
          title: "Guess, check, improve",
          body: [
            "How many laddoos in the box? Guess 20 → clue: “too small”.",
            "Try 30 → clue: “too big”. So the answer is between 20 and 30.",
            "Try 25 → clue: “just right”. Each clue gets you closer!",
          ],
        },
        {
          title: "Worked example · Books on a shelf",
          body: [
            "Shelf = 1 metre = 100 cm. Each book is about 2 cm thick.",
            "100 ÷ 2 = 50. So about 50 books fit.",
            "Walking: each step ≈ 50 cm, so a 10 m hall (1,000 cm) ≈ 20 steps.",
          ],
        },
        {
          title: "Just like debugging",
          body: [
            "Coders try code, test it, and fix it — again and again.",
            "Smart guess tip: pick halfway between “too small” and “too big”.",
            "No shame in a first guess — every try teaches you something.",
          ],
        },
      ],
      remember: [
        "An estimate is a sensible guess.",
        "Guess → check → improve.",
        "“Too small” → go bigger. “Too big” → go smaller.",
        "First guesses are allowed to be wrong.",
      ],
      checkYourself: {
        q: "About how many books fit on a shelf of 1 metre if each book is 2 cm thick?",
        a: "About 50 books. 1 metre = 100 cm, and 100 ÷ 2 = 50.",
      },
      dinoLine: "Chapter 1 done. You can guess, check and improve like a coder — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What is an estimate?",
        options: ["An exact count", "A sensible guess close to the answer", "A wild random number", "Always a wrong answer"],
        correctIndex: 1,
        explanation: "An estimate is a sensible guess — close, but not exact.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "It is okay if your first guess is wrong — you can improve it.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "No shame in a first guess; clues help you get closer.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "You guess 20 and the clue says “too small”. What should you try next?",
        options: ["Try 10", "Guess 20 again", "Try a bigger number, like 30", "Give up"],
        correctIndex: 2,
        explanation: "Too small means the answer is bigger than 20, so go up.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What is the best estimate for the length of a pencil?",
        options: ["About 15 cm", "About 15 m", "About 1 cm", "About 150 cm"],
        correctIndex: 0,
        explanation: "A pencil fits in your hand — about 15 cm.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A shelf is 1 metre long. Each book is 2 cm thick. About how many books fit?",
        options: ["100", "20", "200", "50"],
        correctIndex: 3,
        explanation: "1 metre = 100 cm, and 100 ÷ 2 = 50 books.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "You guess 40 laddoos — “too big”. Then you guess 30 — “too small”. Where is the answer?",
        options: ["Between 30 and 40", "Less than 30", "More than 40", "Exactly 40"],
        correctIndex: 0,
        explanation: "Bigger than 30 but smaller than 40, so it is between them.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "How is guess-check-improve like debugging?",
        options: [
          "You never test anything",
          "You always get it right the first time",
          "You try, test, and fix again and again",
          "You delete everything and stop",
        ],
        correctIndex: 2,
        explanation: "Coders test their code and fix it bit by bit — just like improving a guess.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "About how many children fit on a school bus?",
        options: ["About 4", "About 40", "About 400", "About 4,000"],
        correctIndex: 1,
        explanation: "A bus has many seats, but not hundreds — about 40 is sensible.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Each of your steps is about 50 cm. About how many steps to cross a 10 m hall?",
        options: ["20", "10", "50", "200"],
        correctIndex: 0,
        explanation: "10 m = 1,000 cm, and 1,000 ÷ 50 = 20 steps.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "A secret number is between 1 and 100. You guess 50 — “too big”. You guess 25 — “too small”. What is the smartest next guess?",
        options: ["10", "60", "25 again", "About 37, halfway between 25 and 50"],
        correctIndex: 3,
        explanation: "The answer is between 25 and 50, so guess near the middle — about 37.",
      },
    ],
  },

  C17: {
    notes: {
      bigIdea:
        "Some things are certain, some are likely, some are unlikely, and some are impossible. Dice and coins help us think about chance — and AI uses chance too, guessing what is most likely from lots of examples.",
      definitions: [
        { term: "Certain", meaning: "It will surely happen. The sun will rise tomorrow." },
        { term: "Likely", meaning: "It will probably happen, but not for sure." },
        { term: "Unlikely", meaning: "It could happen, but probably won’t." },
        { term: "Impossible", meaning: "It can never happen. Rolling a 7 on a normal die." },
        { term: "Fair", meaning: "Every result has the same chance — like a normal coin or die." },
      ],
      panels: [
        {
          title: "The chance line",
          body: [
            "Impossible → unlikely → likely → certain.",
            "Rolling a 7 on a normal die (1 to 6) → impossible.",
            "Getting a 6 on your first Ludo roll → unlikely (1 out of 6).",
          ],
        },
        {
          title: "Coins and dice",
          body: [
            "A coin has 2 sides: heads and tails are about equally likely.",
            "A die has 6 faces. Even numbers: 2, 4, 6 → 3 out of 6.",
            "Bag with 7 blue and 3 yellow marbles → yellow is 3 out of 10: unlikely.",
          ],
        },
        {
          title: "Fair or unfair spinner?",
          body: [
            "4 equal parts, a different colour each → fair.",
            "3 red parts + 1 blue part → red is more likely: 3 out of 4.",
            "One part is half the circle → unfair, it wins more often.",
          ],
        },
        {
          title: "How AI guesses",
          body: [
            "AI looks at many examples and picks what is most likely.",
            "Seen 100 cat photos with pointy ears? Pointy ears → likely a cat.",
            "AI is not always certain — it can guess wrong too.",
          ],
        },
      ],
      remember: [
        "Certain, likely, unlikely, impossible.",
        "A coin: heads and tails about equally likely.",
        "Fair = every result has the same chance.",
        "AI picks what is most likely from examples.",
      ],
      checkYourself: {
        q: "Is ‘rolling a 7 on a normal die’ impossible or unlikely? Why?",
        a: "Impossible. A normal die only has 1 to 6, so a 7 can never come up.",
      },
      dinoLine: "Chapter 2 done. You can use chance words like a pro — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which chance word fits “The sun will rise tomorrow”?",
        options: ["Certain", "Unlikely", "Impossible", "Likely"],
        correctIndex: 0,
        explanation: "The sun rises every day, so it is certain.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "Rolling a 7 on a normal die is impossible.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "A normal die only has 1 to 6, so 7 can never come up.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "You toss a normal coin. Which is true?",
        options: ["Heads is much more likely", "Tails is much more likely", "Heads and tails are about equally likely", "Heads can never happen"],
        correctIndex: 2,
        explanation: "A fair coin has 2 sides, so each has about the same chance.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which chance word fits “Getting a 6 on your very first roll in Ludo”?",
        options: ["Likely", "Unlikely", "Certain", "Impossible"],
        correctIndex: 1,
        explanation: "It can happen, but it is only 1 out of 6 — unlikely.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What is the chance of rolling an even number on a normal die?",
        options: ["2 out of 6", "1 out of 6", "6 out of 6", "3 out of 6"],
        correctIndex: 3,
        explanation: "Even numbers are 2, 4 and 6 — that is 3 out of 6.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A spinner has 4 equal parts: 3 red and 1 blue. Which colour is more likely?",
        options: ["Blue", "Both the same", "Red", "Neither can happen"],
        correctIndex: 2,
        explanation: "Red has 3 parts out of 4; blue has only 1 out of 4.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which spinner is fair?",
        options: [
          "One part is half the circle, three small parts",
          "3 red parts and 1 blue part",
          "A spinner that always stops on red",
          "4 equal parts, a different colour each",
        ],
        correctIndex: 3,
        explanation: "Equal parts give every colour the same chance — that is fair.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "How does AI make a guess?",
        options: [
          "It picks what is most likely from lots of examples",
          "It is always certain",
          "It reads your mind",
          "It never uses examples",
        ],
        correctIndex: 0,
        explanation: "AI learns from many examples and picks the most likely answer.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "A bag has 5 green marbles and no red ones. You pick one without looking. Getting a red marble is…",
        options: ["Unlikely", "Likely", "Certain", "Impossible"],
        correctIndex: 3,
        explanation: "There are 0 red marbles, so red can never come out.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "A bag has 7 blue marbles and 3 yellow marbles. What is the chance of picking yellow?",
        options: ["3 out of 10 — unlikely", "7 out of 10 — likely", "3 out of 7 — likely", "10 out of 10 — certain"],
        correctIndex: 0,
        explanation: "7 + 3 = 10 marbles, and 3 are yellow: 3 out of 10, which is unlikely.",
      },
    ],
  },

  C18: {
    notes: {
      bigIdea:
        "When you know how a story ends but not how it began, work backwards. Draw the story, then reverse each arrow: adding becomes subtracting, and subtracting becomes adding — just like pressing undo.",
      definitions: [
        { term: "Working backwards", meaning: "Starting from the end and undoing each step to find the start." },
        { term: "Reverse (undo)", meaning: "The opposite action: add ↔ subtract, double ↔ halve." },
        { term: "Start number", meaning: "What you had at the beginning of the story." },
        { term: "End number", meaning: "What you have at the finish — the part you already know." },
      ],
      panels: [
        {
          title: "Draw the story",
          body: [
            "Story: “I had some sweets. I got 4 more. Now I have 12.”",
            "Arrow: start → +4 → 12.",
            "Reverse: 12 → −4 → 8. I started with 8 sweets.",
          ],
        },
        {
          title: "Flip the action",
          body: [
            "Got more / found / bought → undo by subtracting.",
            "Lost / gave away / ate → undo by adding.",
            "Doubled → undo by halving.",
          ],
        },
        {
          title: "Worked examples",
          body: [
            "Mina has 9 stickers after losing 3 → 9 + 3 = 12 at the start.",
            "Riya got ₹20 and now has ₹50 → 50 − 20 = ₹30 before.",
            "Check: 30 + 20 = 50. ✔ Always check forwards!",
          ],
        },
        {
          title: "Two steps and undo in code",
          body: [
            "Kabir got 6 cards, gave away 4, now has 10.",
            "Undo last step first: 10 + 4 = 14, then 14 − 6 = 8.",
            "Apps work the same way — “Undo” reverses your last action.",
          ],
        },
      ],
      remember: [
        "Know the end? Work backwards.",
        "Add ↔ subtract. Double ↔ halve.",
        "Undo the last step first.",
        "Check your answer going forwards.",
      ],
      checkYourself: {
        q: "Mina has 9 stickers after losing 3. How many did she start with?",
        a: "12 stickers. Losing is undone by adding: 9 + 3 = 12. Check: 12 − 3 = 9.",
      },
      dinoLine: "Chapter 3 done. You can undo a story to find the start — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "You have 12 sweets after getting 4 more. How many did you have at the start?",
        options: ["16", "8", "4", "12"],
        correctIndex: 1,
        explanation: "Undo “got 4” by subtracting: 12 − 4 = 8.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What is the undo (reverse) of “add 5”?",
        options: ["Add 5 again", "Double it", "Subtract 5", "Do nothing"],
        correctIndex: 2,
        explanation: "Adding and subtracting undo each other.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "To undo “gave away 3”, you subtract 3.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "Giving away took 3 off, so to undo it you add 3 back.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Working backwards is most useful when you know…",
        options: ["The end, but not the start", "Nothing at all", "Only the middle", "The start only"],
        correctIndex: 0,
        explanation: "You begin at the known end and undo steps to find the start.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Mina has 9 stickers after losing 3. How many did she start with?",
        options: ["6", "3", "12", "27"],
        correctIndex: 2,
        explanation: "Undo losing by adding: 9 + 3 = 12.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Arjun gave 5 marbles to his sister. Now he has 10. How many did he have at first?",
        options: ["5", "10", "50", "15"],
        correctIndex: 3,
        explanation: "Undo giving away by adding: 10 + 5 = 15.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Riya’s mum gave her ₹20. Now Riya has ₹50. How much did she have before?",
        options: ["₹70", "₹30", "₹20", "₹25"],
        correctIndex: 1,
        explanation: "Undo getting ₹20 by subtracting: 50 − 20 = ₹30.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Working backwards is like which button in apps and code?",
        options: ["Save", "Print", "Volume", "Undo"],
        correctIndex: 3,
        explanation: "Undo reverses your last action — that’s working backwards.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Kabir got 6 cards, then gave away 4. Now he has 10. How many did he start with?",
        options: ["8", "12", "20", "0"],
        correctIndex: 0,
        explanation: "Undo the last step first: 10 + 4 = 14, then 14 − 6 = 8.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Think of a number. Add 7, then double it. You get 30. What was the number?",
        options: ["23", "8", "37", "15"],
        correctIndex: 1,
        explanation: "Undo double: 30 ÷ 2 = 15. Undo add 7: 15 − 7 = 8.",
      },
    ],
  },

  C19: {
    notes: {
      bigIdea:
        "A big, messy job feels hard. Break it into small jobs, put them in order, and do one at a time. This is called decomposition — and it’s how programmers write algorithms too.",
      definitions: [
        { term: "Decomposition", meaning: "Breaking a big problem into smaller, easier parts." },
        { term: "Small task", meaning: "One simple job you can finish on its own." },
        { term: "Order", meaning: "Which task comes first, next, and last." },
        { term: "Algorithm", meaning: "A step-by-step plan to solve a problem, often written in parts." },
      ],
      panels: [
        {
          title: "Pack a school bag",
          body: [
            "Big job: pack the bag. Small jobs: books, bottle, lunch box, pencil box.",
            "1. Check today’s timetable. 2. Put in those books.",
            "3. Fill the water bottle. 4. Add the lunch box.",
          ],
        },
        {
          title: "Break it, then order it",
          body: [
            "Clean your room: pick up toys, put books on the shelf, make the bed.",
            "Nimbu pani: squeeze lemons → add water → stir in sugar → pour and serve.",
            "Serving comes last — you can’t pour it before it’s made!",
          ],
        },
        {
          title: "Maths decomposition",
          body: [
            "23 + 45: tens 20 + 40 = 60, ones 3 + 5 = 8 → 68.",
            "6 × 14: 6 × 10 = 60 and 6 × 4 = 24 → 60 + 24 = 84.",
            "Small sums are easier than one big one.",
          ],
        },
        {
          title: "Just like an algorithm",
          body: [
            "Coders split a big program into small parts.",
            "Class party: pick a date → make a guest list → buy snacks → set up and enjoy.",
            "Each part is small, clear, and in the right order.",
          ],
        },
      ],
      remember: [
        "Big job → small jobs.",
        "Put the small jobs in order.",
        "Do one small job at a time.",
        "Algorithms are built in parts, too.",
      ],
      checkYourself: {
        q: "Break ‘make a birthday card’ into four small steps.",
        a: "1. Fold the paper. 2. Draw a picture on the front. 3. Write a message inside. 4. Sign your name and give it.",
      },
      dinoLine: "Chapter 4 done. You can break big jobs into small steps — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What does decomposition mean?",
        options: ["Doing everything at once", "Breaking a big problem into small parts", "Skipping the hard parts", "Guessing the answer"],
        correctIndex: 1,
        explanation: "Decomposition breaks one big job into small, easy jobs.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "Breaking a big job into small steps makes it easier.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Small steps are easier to do one at a time.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which is a small step in packing your school bag?",
        options: ["Build a house", "Go to sleep", "Watch TV", "Put in today’s books"],
        correctIndex: 3,
        explanation: "Putting in today’s books is one small part of packing the bag.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Coders write an algorithm in small parts. Which idea is that?",
        options: ["Decomposition", "Symmetry", "Probability", "Estimation"],
        correctIndex: 0,
        explanation: "Splitting a big program into parts is decomposition.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "You are making a birthday card. Which step comes first?",
        options: ["Write the message inside", "Give it to your friend", "Fold the paper", "Sign your name"],
        correctIndex: 2,
        explanation: "You need a folded card before you can draw or write on it.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Making nimbu pani: which step should come LAST?",
        options: ["Squeeze the lemons", "Add water", "Stir in sugar", "Pour into a glass and serve"],
        correctIndex: 3,
        explanation: "You serve it only after it is made.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Big job: clean your room. Which is NOT a small part of it?",
        options: ["Pick up toys", "Make the bed", "Fly a kite", "Put books on the shelf"],
        correctIndex: 2,
        explanation: "Flying a kite doesn’t help clean the room.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "To add 23 + 45, break it into tens and ones: 20 + 40 = 60 and 3 + 5 = 8. What is the answer?",
        options: ["68", "63", "86", "60"],
        correctIndex: 0,
        explanation: "60 + 8 = 68.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Which order makes the most sense for hosting a class party?",
        options: [
          "Set up → pick a date → buy snacks → make a guest list",
          "Pick a date → make a guest list → buy snacks → set up and enjoy",
          "Buy snacks → enjoy → pick a date → make a guest list",
          "Enjoy → set up → make a guest list → pick a date",
        ],
        correctIndex: 1,
        explanation: "Plan first (date, guests), then shop, then set up and enjoy.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Break 6 × 14 into 6 × 10 and 6 × 4. What is the answer?",
        options: ["64", "70", "84", "624"],
        correctIndex: 2,
        explanation: "6 × 10 = 60 and 6 × 4 = 24, so 60 + 24 = 84.",
      },
    ],
  },

  C20: {
    notes: {
      bigIdea:
        "This capstone mixes ideas from the whole Math-for-CS track: patterns, sorting, grids, turns, chance, and working backwards. Pick a strategy, show your working, and explain how you solved it.",
      definitions: [
        { term: "Strategy", meaning: "A plan for solving a problem, like working backwards or breaking it into parts." },
        { term: "Show your working", meaning: "Write each step so someone else can follow your thinking." },
        { term: "Venn diagram", meaning: "Overlapping circles for sorting. Things that fit both groups go in the middle." },
        { term: "Capstone", meaning: "A final challenge that uses everything you’ve learned." },
      ],
      panels: [
        {
          title: "Step 1 · Patterns and sorting",
          body: [
            "2, 4, 6, 8, … → add 2 each time → next is 10.",
            "1, 3, 6, 10, … → add 2, 3, 4, then 5 → next is 15.",
            "Sort 45, 12, 30 smallest to biggest → 12, 30, 45.",
          ],
        },
        {
          title: "Step 2 · Venn and grids",
          body: [
            "Circles “Red things” and “Fruits”: a red apple goes in the middle.",
            "Grid: (3, 1) → 3 across, 1 up.",
            "Start (1, 1), move 2 right, 3 up, 1 right → (4, 4).",
          ],
        },
        {
          title: "Step 3 · Turns, chance, backwards",
          body: [
            "Face east, half turn (180°) → face west.",
            "A coin landing heads is not certain — it’s about equally likely.",
            "Priya has 15 beads after buying 6 → 15 − 6 = 9 at the start.",
          ],
        },
        {
          title: "Step 4 · Talk it through",
          body: [
            "Use at least two strategies: e.g. draw it, then work backwards.",
            "Check your answer forwards: 9 + 6 = 15. ✔",
            "Tell a parent: grids place pixels; chance helps AI guess.",
          ],
        },
      ],
      remember: [
        "Find the rule to continue a pattern.",
        "Grid address = (across, up).",
        "Chance words: certain, likely, unlikely, impossible.",
        "Show your working and check it.",
      ],
      checkYourself: {
        q: "Name two maths ideas from this track that help you understand computers or AI.",
        a: "Grids and coordinates (screens place every pixel by its address) and probability (AI guesses what is most likely). Decomposition and turns also help!",
      },
      dinoLine: "Chapter 5 done and the whole Math-for-CS track is complete — you think like a real problem solver, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What comes next? 2, 4, 6, 8, ___",
        options: ["9", "10", "12", "16"],
        correctIndex: 1,
        explanation: "The rule is add 2: 8 + 2 = 10.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In the grid point (3, 1), which number tells you how far UP to go?",
        options: ["3", "4", "1", "Both"],
        correctIndex: 2,
        explanation: "Address is (across, up), so 1 is up.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "A normal coin landing on heads is certain.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "It could be heads or tails — about equally likely, not certain.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Sort from smallest to biggest: 45, 12, 30.",
        options: ["45, 30, 12", "30, 12, 45", "12, 45, 30", "12, 30, 45"],
        correctIndex: 3,
        explanation: "12 is smallest, then 30, then 45.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A Venn diagram has two circles: “Red things” and “Fruits”. Where does a red apple go?",
        options: ["Only in “Red things”", "Only in “Fruits”", "In the middle, where the circles overlap", "Outside both circles"],
        correctIndex: 2,
        explanation: "A red apple is red AND a fruit, so it goes in the overlap.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "You face east and make a half turn (180°). Which way do you face now?",
        options: ["North", "West", "South", "East"],
        correctIndex: 1,
        explanation: "A half turn makes you face the opposite way: east → west.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Priya has 15 beads after buying 6 more. How many did she have at the start?",
        options: ["21", "6", "15", "9"],
        correctIndex: 3,
        explanation: "Work backwards: 15 − 6 = 9. Check: 9 + 6 = 15.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which maths idea helps AI guess what is most likely?",
        options: ["Probability (chance)", "Symmetry", "Rows and columns", "Sorting"],
        correctIndex: 0,
        explanation: "AI uses chance to pick the most likely answer from examples.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Start at (1, 1). Move 2 right, then 3 up, then 1 right. Where are you?",
        options: ["(3, 4)", "(4, 3)", "(4, 4)", "(2, 5)"],
        correctIndex: 2,
        explanation: "Across: 1 + 2 + 1 = 4. Up: 1 + 3 = 4. So (4, 4).",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "What comes next? 1, 3, 6, 10, ___",
        options: ["15", "14", "13", "16"],
        correctIndex: 0,
        explanation: "The jumps grow: +2, +3, +4, then +5 → 10 + 5 = 15.",
      },
    ],
  },
};
