import type { LessonContentBank } from "./types";

export const MATH_CONTENT_1: LessonContentBank = {
  C1: {
    notes: {
      bigIdea:
        "Computers count with only two digits: 0 (light off) and 1 (light on). With three lights in a row, the place of each 1 tells you its value — 4, 2 and 1 — so we can count from 0 to 5.",
      definitions: [
        { term: "Binary", meaning: "Counting with only two digits, 0 and 1. It is the computer’s light-switch language." },
        { term: "ON / OFF", meaning: "A light that is ON is written as 1. A light that is OFF is written as 0." },
        { term: "Bit", meaning: "One light (or one switch) — a single 0 or 1." },
        { term: "Place", meaning: "Where a light sits in the row. With three lights, the places are worth 4, 2 and 1 (left to right)." },
      ],
      panels: [
        {
          title: "Only two digits",
          body: [
            "We use ten digits (0–9). Computers use just two: 0 and 1.",
            "Hold up 3 fingers as 3 light switches: finger up = 1, finger down = 0.",
            "Remember CS A2: ON = 1, OFF = 0.",
          ],
        },
        {
          title: "Each place has a value",
          body: [
            "Three lights: left = 4, middle = 2, right = 1.",
            "Add the values of the lights that are ON.",
            "1 0 1 → 4 + 0 + 1 = 5.",
          ],
        },
        {
          title: "Count 0 to 5",
          body: [
            "0 = 000 · 1 = 001 · 2 = 010",
            "3 = 011 (2 + 1) · 4 = 100 · 5 = 101 (4 + 1)",
            "Each new number just adds one more — like adding one laddoo to the plate.",
          ],
        },
        {
          title: "The place of a 1 matters",
          body: [
            "001 and 100 both have just one light ON.",
            "But 001 = 1 and 100 = 4 — the place changes the value!",
            "Our normal numbers work the same way (see C3: 23 is not 32).",
          ],
        },
      ],
      remember: [
        "Binary uses only 0 and 1.",
        "ON = 1 · OFF = 0.",
        "Three lights are worth 4, 2, 1.",
        "3 = 011 · 5 = 101.",
      ],
      checkYourself: {
        q: "Show 3 using three on/off lights.",
        a: "Off, on, on → 011. The middle light (2) plus the right light (1) makes 2 + 1 = 3.",
      },
      dinoLine: "Chapter 1 done. You can count to 5 the computer way — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In binary, a light that is ON is written as…",
        options: ["0", "1", "2", "5"],
        correctIndex: 1,
        explanation: "ON is 1 and OFF is 0 — just two digits.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "How many different digits does binary use?",
        options: ["Ten", "Five", "Two — 0 and 1", "Three"],
        correctIndex: 2,
        explanation: "Binary only has 0 and 1, like a light that is off or on.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "In binary, 0 means the light is OFF.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Yes! 0 = OFF and 1 = ON.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "With three lights in a row, how much is the right-most light worth?",
        options: ["1", "2", "4", "10"],
        correctIndex: 0,
        explanation: "The three places are worth 4, 2, 1 — the right-most one is 1.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which light pattern shows the number 3?",
        options: ["100", "011", "101", "110"],
        correctIndex: 1,
        explanation: "011 → 0 + 2 + 1 = 3.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What number does the pattern 101 show?",
        options: ["2", "3", "4", "5"],
        correctIndex: 3,
        explanation: "101 → 4 + 0 + 1 = 5.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which light pattern shows the number 4?",
        options: ["100", "001", "010", "111"],
        correctIndex: 0,
        explanation: "Only the left light (worth 4) is on: 100 → 4 + 0 + 0 = 4.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What number does the pattern 010 show?",
        options: ["4", "3", "2", "1"],
        correctIndex: 2,
        explanation: "Only the middle light is on, and it is worth 2: 0 + 2 + 0 = 2.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "001 and 100 both have only one light ON. Why are they different numbers?",
        options: [
          "They are really the same number",
          "100 is bigger because it has more zeros",
          "001 is bigger because the 1 comes last",
          "The place of the 1 matters — 001 is 1, but 100 is 4",
        ],
        correctIndex: 3,
        explanation: "The right place is worth 1 and the left place is worth 4, so the place changes the value.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Meera counts in binary: 001, 010, 011, … What comes next?",
        options: ["110", "012", "100", "111"],
        correctIndex: 2,
        explanation: "011 is 3, so next is 4, which is 100. (Binary has no digit 2!)",
      },
    ],
  },

  C2: {
    notes: {
      bigIdea:
        "Every whole number is either odd or even. Even numbers can be shared into pairs with none left over; odd numbers always have one left over. Spotting patterns like this is how both maths and code repeat things.",
      definitions: [
        { term: "Even number", meaning: "A number you can split into pairs with nothing left over. It ends in 0, 2, 4, 6 or 8." },
        { term: "Odd number", meaning: "A number that leaves one left over when you make pairs. It ends in 1, 3, 5, 7 or 9." },
        { term: "Pattern", meaning: "Something that repeats or grows by a rule, like clap-snap-clap-snap." },
        { term: "Skip every other", meaning: "Say one number, jump the next: 2, 4, 6… or 1, 3, 5…" },
      ],
      panels: [
        {
          title: "Pairs test",
          body: [
            "8 laddoos → 4 pairs, none left. 8 is even.",
            "7 laddoos → 3 pairs and 1 left over. 7 is odd.",
            "Quick trick: look at the last digit.",
          ],
        },
        {
          title: "Sort numbers to 20",
          body: [
            "Even: 2, 4, 6, 8, 10, 12, 14, 16, 18, 20.",
            "Odd: 1, 3, 5, 7, 9, 11, 13, 15, 17, 19.",
            "Odd and even take turns: odd, even, odd, even…",
          ],
        },
        {
          title: "Clap patterns",
          body: [
            "Clap, snap, clap, snap, clap, … → next is snap.",
            "Clap on even numbers only: 2 👏, 4 👏, 6 👏.",
            "A pattern is a rule that repeats — code loves repeating!",
          ],
        },
        {
          title: "Skip every other number",
          body: [
            "Start at 2, skip one each time: 2, 4, 6, 8, 10 → evens.",
            "Start at 1: 1, 3, 5, 7, 9 → odds.",
            "Next in 10, 12, 14, __? It is 16 (add 2).",
          ],
        },
      ],
      remember: [
        "Even = pairs, nothing left over.",
        "Odd = one left over.",
        "Check the last digit: 0, 2, 4, 6, 8 → even.",
        "Patterns repeat by a rule.",
      ],
      checkYourself: {
        q: "Is 14 odd or even? How do you know?",
        a: "Even. 14 makes 7 pairs with nothing left over, and it ends in 4.",
      },
      dinoLine: "Chapter 2 done. You can sort odd and even and spot patterns — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which number is even?",
        options: ["7", "13", "8", "15"],
        correctIndex: 2,
        explanation: "8 makes 4 pairs with none left over, and it ends in 8.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which number is odd?",
        options: ["9", "4", "10", "12"],
        correctIndex: 0,
        explanation: "9 makes 4 pairs and 1 left over, so it is odd.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "14 is an even number.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "14 ends in 4 and makes 7 pairs — even!",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What comes next: 2, 4, 6, 8, __?",
        options: ["9", "10", "12", "11"],
        correctIndex: 1,
        explanation: "The rule is add 2: 8 + 2 = 10.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What comes next: 1, 3, 5, 7, __?",
        options: ["8", "10", "9", "11"],
        correctIndex: 2,
        explanation: "These are odd numbers going up by 2: 7 + 2 = 9.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "How many odd numbers are there from 1 to 10?",
        options: ["4", "5", "6", "10"],
        correctIndex: 1,
        explanation: "1, 3, 5, 7, 9 — that is 5 odd numbers.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Riya has 11 laddoos. She puts them into pairs. What happens?",
        options: [
          "She gets 11 pairs",
          "Two laddoos are left over",
          "All laddoos make pairs",
          "One laddoo is left over, so 11 is odd",
        ],
        correctIndex: 3,
        explanation: "11 = 5 pairs + 1 left over, so 11 is odd.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Clap pattern: clap, snap, clap, snap, clap, __ ?",
        options: ["clap", "snap", "stomp", "clap clap"],
        correctIndex: 1,
        explanation: "Clap and snap take turns, so after clap comes snap.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Which list has ONLY even numbers?",
        options: ["2, 5, 8, 10", "6, 9, 14, 18", "3, 7, 11, 15", "4, 12, 16, 20"],
        correctIndex: 3,
        explanation: "4, 12, 16 and 20 all end in 0, 2, 4, 6 or 8. The others have 5, 9 or odd numbers.",
      },
      {
        difficulty: "hard",
        type: "true_false",
        prompt: "If you skip every other number starting at 1 (1, 3, 5, …), you will land on 20.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "Starting at 1 and skipping every other gives only odd numbers, and 20 is even.",
      },
    ],
  },

  C3: {
    notes: {
      bigIdea:
        "In our numbers, where a digit sits tells you what it is worth: ones, tens or hundreds. That is why 23 and 32 are different. Binary also cares about position — it just uses different place values.",
      definitions: [
        { term: "Digit", meaning: "One of the ten symbols 0–9 that we use to write numbers." },
        { term: "Place value", meaning: "What a digit is worth because of where it sits — ones, tens or hundreds." },
        { term: "Ones, tens, hundreds", meaning: "From right to left: ones place, tens place (groups of 10), hundreds place (groups of 100)." },
        { term: "Expanded form", meaning: "Writing a number as the sum of its places, like 352 = 300 + 50 + 2." },
      ],
      panels: [
        {
          title: "Why 23 is not 32",
          body: [
            "23 = 2 tens + 3 ones = 20 + 3.",
            "32 = 3 tens + 2 ones = 30 + 2.",
            "Same digits, different places, different numbers!",
          ],
        },
        {
          title: "Build a number",
          body: [
            "4 bundles of 10 sticks + 7 single sticks = 47.",
            "In 47, the 4 means 4 tens = 40. The 7 means 7 ones.",
            "Swap them: 74 = 7 tens + 4 ones. A much bigger number!",
          ],
        },
        {
          title: "Hundreds too",
          body: [
            "352 = 3 hundreds + 5 tens + 2 ones.",
            "352 = 300 + 50 + 2.",
            "The 5 in 352 is worth 50, not 5.",
          ],
        },
        {
          title: "Base-10 vs binary",
          body: [
            "Our places go 100, 10, 1 (each is 10 times bigger).",
            "Binary lights go 4, 2, 1 (each is 2 times bigger).",
            "Both follow one big rule: position matters!",
          ],
        },
      ],
      remember: [
        "Places: hundreds, tens, ones.",
        "The place tells a digit’s value.",
        "23 ≠ 32 — position matters.",
        "Binary cares about position too.",
      ],
      checkYourself: {
        q: "In 47, what does the 4 stand for?",
        a: "4 tens, which is 40. It sits in the tens place.",
      },
      dinoLine: "Chapter 3 done. You know ones, tens and hundreds — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In 36, what does the 3 stand for?",
        options: ["3 ones", "3 tens (30)", "3 hundreds", "36"],
        correctIndex: 1,
        explanation: "The 3 is in the tens place, so it means 3 tens = 30.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In 58, the 8 is in which place?",
        options: ["Ones", "Tens", "Hundreds", "Thousands"],
        correctIndex: 0,
        explanation: "The right-most digit is always in the ones place.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "4 tens and 2 ones make…",
        options: ["24", "6", "42", "402"],
        correctIndex: 2,
        explanation: "4 tens = 40, plus 2 ones: 40 + 2 = 42.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "23 and 32 are the same number because they use the same digits.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "23 = 20 + 3 but 32 = 30 + 2 — the places are different.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What is the value of the 5 in 352?",
        options: ["5", "500", "5 hundreds", "50"],
        correctIndex: 3,
        explanation: "The 5 is in the tens place: 5 tens = 50.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which number is 300 + 40 + 7?",
        options: ["347", "3407", "374", "743"],
        correctIndex: 0,
        explanation: "3 hundreds, 4 tens, 7 ones = 347.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Swap the digits of 61. What new number do you get?",
        options: ["61", "7", "16", "160"],
        correctIndex: 2,
        explanation: "The 1 moves to the tens place and the 6 to the ones: 10 + 6 = 16.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "How many tens are in 90?",
        options: ["90", "1", "19", "9"],
        correctIndex: 3,
        explanation: "90 = 9 tens + 0 ones, so there are 9 tens.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "With three binary lights, 100 means 4. In our normal numbers, 100 means…",
        options: ["four", "one hundred", "ten", "one"],
        correctIndex: 1,
        explanation: "In base-10 the third place is hundreds, so 100 = one hundred. Different place values, same “position matters” idea.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Aarav has 2 bundles of ten pencils and 7 single pencils. His friend gives him 1 more bundle of ten. How many pencils now?",
        options: ["28", "37", "30", "47"],
        correctIndex: 1,
        explanation: "2 tens + 7 ones = 27, and one more ten makes 3 tens + 7 ones = 37.",
      },
    ],
  },

  C4: {
    notes: {
      bigIdea:
        "Skip counting means adding the same number again and again: by 2s, 5s or 10s. A list made by a rule is a sequence. “Repeat add 2” is exactly what a loop does in code.",
      definitions: [
        { term: "Skip counting", meaning: "Counting by jumping the same amount each time, like 5, 10, 15, 20." },
        { term: "Sequence", meaning: "A list of numbers in order that follows a rule, like 3, 6, 9, 12." },
        { term: "Rule", meaning: "What you do to get the next number, like “add 3”." },
        { term: "Loop", meaning: "In code, doing the same step again and again (CS A8). Skip counting is a loop!" },
      ],
      panels: [
        {
          title: "Skip by 2, 5 and 10",
          body: [
            "By 2: 2, 4, 6, 8, 10, 12…",
            "By 5: 5, 10, 15, 20, 25… (like counting ₹5 coins).",
            "By 10: 10, 20, 30, 40, 50.",
          ],
        },
        {
          title: "Find the rule",
          body: [
            "3, 6, 9, 12 → each jump is 3. Rule: add 3.",
            "Check: 6 − 3 = 3, 9 − 6 = 3, 12 − 9 = 3.",
            "Next three: 15, 18, 21.",
          ],
        },
        {
          title: "Cricket runs",
          body: [
            "A batter hits 4 runs every over.",
            "After 1, 2, 3 overs: 4, 8, 12 runs.",
            "Rule: add 4. After 5 overs: 16, then 20 runs.",
          ],
        },
        {
          title: "It’s a loop!",
          body: [
            "Start at 0. Repeat: add 2. Say the number.",
            "0 → 2 → 4 → 6 → 8 → 10.",
            "Same step, again and again — that is a loop in code.",
          ],
        },
      ],
      remember: [
        "Skip counting = add the same amount.",
        "The rule tells the next number.",
        "Check the jump between numbers.",
        "“Repeat add 2” is a loop.",
      ],
      checkYourself: {
        q: "What is the rule for 5, 10, 15, 20?",
        a: "Add 5 each time. (10 − 5 = 5, 15 − 10 = 5, 20 − 15 = 5.)",
      },
      dinoLine: "Chapter 4 done. You can skip count and find a sequence’s rule — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Skip count by 2: 2, 4, 6, __",
        options: ["7", "8", "10", "9"],
        correctIndex: 1,
        explanation: "Add 2 each time: 6 + 2 = 8.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Skip count by 10: 10, 20, 30, __",
        options: ["31", "35", "40", "50"],
        correctIndex: 2,
        explanation: "Add 10 each time: 30 + 10 = 40.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What is the rule for 3, 6, 9, 12?",
        options: ["Add 3", "Add 2", "Add 6", "Add 9"],
        correctIndex: 0,
        explanation: "Each jump is 3: 6 − 3 = 3, 9 − 6 = 3, 12 − 9 = 3.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "“Repeat add 2” is like a loop in code.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "A loop does the same step again and again — just like adding 2 each time.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What are the next three numbers? 5, 10, 15, __, __, __",
        options: ["16, 17, 18", "20, 30, 40", "20, 25, 30", "25, 35, 45"],
        correctIndex: 2,
        explanation: "The rule is add 5: 15 + 5 = 20, 20 + 5 = 25, 25 + 5 = 30.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which number is missing? 10, 20, __, 40, 50",
        options: ["25", "35", "45", "30"],
        correctIndex: 3,
        explanation: "Counting by 10s: 20 + 10 = 30.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A batter scores 4 runs every over: 4, 8, 12 after 1, 2, 3 overs. How many runs after 5 overs?",
        options: ["16", "20", "24", "15"],
        correctIndex: 1,
        explanation: "Keep adding 4: 12, 16 (4 overs), 20 (5 overs).",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which sequence is skip counting by 5?",
        options: ["5, 10, 20, 40", "2, 4, 6, 8", "10, 15, 25, 30", "25, 30, 35, 40"],
        correctIndex: 3,
        explanation: "25, 30, 35, 40 jumps by 5 every time. The others change the jump or jump by 2.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Counting by 2s from 2 up to 20, how many numbers do you say?",
        options: ["20", "10", "11", "9"],
        correctIndex: 1,
        explanation: "2, 4, 6, 8, 10, 12, 14, 16, 18, 20 — that is 10 numbers.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Which number will you NOT say when skip counting by 5 up to 50?",
        options: ["35", "45", "42", "50"],
        correctIndex: 2,
        explanation: "Counting by 5s lands only on numbers ending in 0 or 5, so 42 is skipped.",
      },
    ],
  },

  C5: {
    notes: {
      bigIdea:
        "A growing pattern gets bigger by a rule each step — like adding 1 more, or doubling. If you can say the rule in words, you can draw the next picture. A fun one is 1, 1, 2, 3, 5, where each number is the last two added together.",
      definitions: [
        { term: "Growing pattern", meaning: "A pattern that gets bigger each step by following a rule." },
        { term: "Step", meaning: "One picture or number in the pattern: step 1, step 2, step 3…" },
        { term: "Rule in words", meaning: "Saying how the pattern grows, like “add one more row each time”." },
        { term: "Fibonacci-lite", meaning: "1, 1, 2, 3, 5, 8 — each new number is the last two numbers added." },
      ],
      panels: [
        {
          title: "Add one more",
          body: [
            "Stack of rupee coins: 1, 2, 3, 4 coins.",
            "Rule: add 1 coin each step.",
            "Next stack: 5 coins.",
          ],
        },
        {
          title: "Squares that double",
          body: [
            "Step 1: 1 square. Step 2: 2 squares. Step 3: 4 squares.",
            "Rule: double each time (1 + 1 = 2, 2 + 2 = 4).",
            "Step 4: 4 + 4 = 8 squares.",
          ],
        },
        {
          title: "Triangle of laddoos",
          body: [
            "Row 1: 1 laddoo → total 1.",
            "Add a row of 2 → total 3. Add a row of 3 → total 6.",
            "Rule: add one more row, each row 1 bigger. Next: 6 + 4 = 10.",
          ],
        },
        {
          title: "Fibonacci-lite story",
          body: [
            "Start with 1 and 1.",
            "Add the last two: 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5.",
            "Next: 3 + 5 = 8. Nature loves this pattern — look at flower petals!",
          ],
        },
      ],
      remember: [
        "Growing patterns follow a rule.",
        "Say the rule in words first.",
        "Draw the next step to check.",
        "1, 1, 2, 3, 5 → add the last two.",
      ],
      checkYourself: {
        q: "Squares: 1, then 3, then 6. How many in the next step if we add one more row?",
        a: "10. The rows go 1, 2, 3, so the next row has 4 squares: 6 + 4 = 10.",
      },
      dinoLine: "Chapter 5 done. You can grow a pattern and explain its rule — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Pattern: 1, 2, 3, 4, __ (add 1 each time). What comes next?",
        options: ["5", "6", "8", "4"],
        correctIndex: 0,
        explanation: "Add 1: 4 + 1 = 5.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Block towers: 2, 4, 6, 8 blocks. How many blocks in the next tower?",
        options: ["9", "12", "10", "16"],
        correctIndex: 2,
        explanation: "Each tower has 2 more blocks: 8 + 2 = 10.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "In a growing pattern, each step gets bigger by following a rule.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "That is what a growing pattern is — it grows by a rule.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Squares: 1, 2, 4, 8 — each step doubles. How many squares next?",
        options: ["10", "12", "9", "16"],
        correctIndex: 3,
        explanation: "Double 8: 8 + 8 = 16.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A triangle of laddoos has totals 1, 3, 6. The next step adds a row of 4. How many laddoos in all?",
        options: ["9", "10", "12", "8"],
        correctIndex: 1,
        explanation: "6 + 4 = 10.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "In the pattern 1, 1, 2, 3, 5, each new number is…",
        options: [
          "the last number plus 1",
          "double the last number",
          "always an odd number",
          "the last two numbers added together",
        ],
        correctIndex: 3,
        explanation: "1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5 — add the last two.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "What comes after 1, 1, 2, 3, 5?",
        options: ["6", "7", "8", "10"],
        correctIndex: 2,
        explanation: "Add the last two: 3 + 5 = 8.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "The pattern goes 3, 5, 7, 9. What is the rule in words?",
        options: ["Add 2 each time", "Add 3 each time", "Double each time", "Add the last two numbers"],
        correctIndex: 0,
        explanation: "5 − 3 = 2, 7 − 5 = 2, 9 − 7 = 2 — add 2 each time.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Pattern: 1, 2, 4, 7, 11 (add 1, then 2, then 3, then 4). What comes next?",
        options: ["15", "16", "14", "22"],
        correctIndex: 1,
        explanation: "The next jump is 5: 11 + 5 = 16.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Add-the-last-two pattern: 2, 3, 5, 8, __",
        options: ["11", "10", "16", "13"],
        correctIndex: 3,
        explanation: "5 + 8 = 13.",
      },
    ],
  },

  C6: {
    notes: {
      bigIdea:
        "A statement is a sentence that is either true or false — in this game there is no “maybe”. Just one example can prove a statement false. Computers check true-or-false questions all the time to decide what to do.",
      definitions: [
        { term: "Statement", meaning: "A sentence that tells something and can be checked, like “A cat has four legs.”" },
        { term: "True", meaning: "The statement matches the facts." },
        { term: "False", meaning: "The statement does not match the facts." },
        { term: "Counter-example", meaning: "One example that shows a statement is false — like a penguin for “All birds can fly.”" },
      ],
      panels: [
        {
          title: "Is it a statement?",
          body: [
            "“A week has 7 days.” → Statement (true).",
            "“Please shut the door.” → Not a statement, it is a request.",
            "“What time is it?” → Not a statement, it is a question.",
          ],
        },
        {
          title: "True or false — no maybe",
          body: [
            "“5 + 3 = 8.” → True.",
            "“10 is an odd number.” → False (10 is even).",
            "“Cricket is played with a bat.” → True.",
          ],
        },
        {
          title: "One example can break it",
          body: [
            "“All birds can fly.” Penguins are birds that can’t fly.",
            "So the statement is false.",
            "Words like “all” and “every” need to work every single time.",
          ],
        },
        {
          title: "Computers check conditions",
          body: [
            "A game checks: “Is your score more than 10?”",
            "Score 12 → true → you win! Score 7 → false → play again.",
            "That true/false check is called a condition in code.",
          ],
        },
      ],
      remember: [
        "A statement is true or false.",
        "No “maybe” in this game.",
        "One counter-example makes “all” false.",
        "Code uses true/false to decide.",
      ],
      checkYourself: {
        q: "True or false: every even number ends with 0, 2, 4, 6, or 8.",
        a: "True. Every even number (like 14, 20, 36) ends with 0, 2, 4, 6 or 8.",
      },
      dinoLine: "Chapter 1 done. You can tell true from false like a logic detective — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "“The sun rises in the east.” True or false?",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Every morning the sun comes up in the east, so it is true.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "“All birds can fly.” True or false?",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "Penguins are birds that cannot fly, so the statement is false.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which of these is a statement you can mark true or false?",
        options: ["Please close the door.", "What time is it?", "A cat has four legs.", "Wow!"],
        correctIndex: 2,
        explanation: "“A cat has four legs” tells a fact we can check. The others are a request, a question and a shout.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In this game, a statement can be…",
        options: ["True, false, or maybe", "Only true or false", "Only true", "Anything you like"],
        correctIndex: 1,
        explanation: "There is no “maybe” here — every statement is either true or false.",
      },
      {
        difficulty: "medium",
        type: "true_false",
        prompt: "“5 + 3 = 9.” True or false?",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "5 + 3 = 8, not 9, so it is false.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Why is “All birds can fly” false?",
        options: [
          "Penguins are birds that cannot fly",
          "Some birds can swim",
          "Some birds are very big",
          "Parrots can talk",
        ],
        correctIndex: 0,
        explanation: "One bird that can’t fly (a penguin) is enough to make “all” false.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which statement is TRUE?",
        options: ["10 is an odd number", "3 is bigger than 8", "A square has 3 sides", "A week has 7 days"],
        correctIndex: 3,
        explanation: "A week really has 7 days. 10 is even, 3 is smaller than 8, and a square has 4 sides.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "A game says: “If your score is more than 10, you win.” Your score is 12. Is the condition true or false?",
        options: ["False — you lose", "True — you win", "Maybe", "It cannot be checked"],
        correctIndex: 1,
        explanation: "12 is more than 10, so the condition is true and you win.",
      },
      {
        difficulty: "hard",
        type: "true_false",
        prompt: "“Every number that ends in 5 is odd.” True or false?",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Numbers like 5, 15, 25 always leave one left over in pairs, so they are all odd.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Which fruit proves that “All fruits are red” is false?",
        options: ["An apple", "A strawberry", "A banana", "A cherry"],
        correctIndex: 2,
        explanation: "A banana is a fruit that is yellow, not red — one counter-example is enough.",
      },
    ],
  },

  C7: {
    notes: {
      bigIdea:
        "AND, OR and NOT are tiny logic words. AND needs both things to be true. OR needs at least one. NOT flips true to false and false to true. Games use them every time they check “if both” or “if either”.",
      definitions: [
        { term: "AND", meaning: "Both things must be true. Cake AND juice means you need both." },
        { term: "OR", meaning: "At least one thing must be true. Ticket OR pass — either one works (both is fine too)." },
        { term: "NOT", meaning: "The opposite. If it is NOT raining, then “raining” is false." },
        { term: "Rule", meaning: "A check that says yes or no, like “You may enter if…”." },
      ],
      panels: [
        {
          title: "AND = both",
          body: [
            "Party rule: bring cake AND juice.",
            "Cake + juice → yes. Only cake → no. Only juice → no.",
            "AND is fussy — it wants everything!",
          ],
        },
        {
          title: "OR = at least one",
          body: [
            "Rule: enter with a ticket OR a pass.",
            "Ticket only → yes. Pass only → yes. Both → yes.",
            "Neither → no.",
          ],
        },
        {
          title: "NOT = the opposite",
          body: [
            "Rule: enter if you are NOT wearing muddy shoes.",
            "Clean shoes → yes. Muddy shoes → no.",
            "NOT true = false. NOT false = true.",
          ],
        },
        {
          title: "In games",
          body: [
            "“If you have a key AND a torch, open the cave.” → if-both.",
            "“If you find a coin OR a gem, get a point.” → if-either.",
            "Code checks these rules many times every second.",
          ],
        },
      ],
      remember: [
        "AND → both must be true.",
        "OR → at least one is true.",
        "NOT → flip it to the opposite.",
        "Games use if-both and if-either.",
      ],
      checkYourself: {
        q: "You need a hat AND a ticket. You have only a ticket. Can you enter?",
        a: "No. AND means you need both, and you are missing the hat.",
      },
      dinoLine: "Chapter 2 done. You can use AND, OR and NOT like a party planner — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Party rule: you need cake AND juice. What does that mean?",
        options: ["You need only cake", "You need both cake and juice", "You need neither", "You need only juice"],
        correctIndex: 1,
        explanation: "AND means both must be there.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What does OR mean?",
        options: ["Both must be true", "None can be true", "The opposite", "At least one must be true"],
        correctIndex: 3,
        explanation: "OR is happy if at least one thing is true.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What does NOT mean?",
        options: ["The opposite", "Both", "At least one", "Maybe"],
        correctIndex: 0,
        explanation: "NOT flips things: true becomes false, false becomes true.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "NOT true is false.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "NOT gives the opposite, and the opposite of true is false.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Rule: bring a gift AND a card. Kabir brings a gift but no card. Can he enter?",
        options: ["Yes", "No — he needs both", "Yes, one is enough", "Only if he sings"],
        correctIndex: 1,
        explanation: "AND needs both, and Kabir has no card.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Rule: enter with a ticket OR a pass. Sara has only a pass. Can she enter?",
        options: ["No", "Only with a ticket too", "Yes — one is enough for OR", "Nobody can enter"],
        correctIndex: 2,
        explanation: "OR needs at least one, and Sara has a pass.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Rule: enter if you are NOT wearing muddy shoes. Aman’s shoes are clean. Can he enter?",
        options: ["No", "Only with a hat", "Only on Sunday", "Yes — his shoes are not muddy"],
        correctIndex: 3,
        explanation: "His shoes are NOT muddy, so the rule is true and he can enter.",
      },
      {
        difficulty: "medium",
        type: "true_false",
        prompt: "With OR, if both things are true, the answer is still true.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "OR needs at least one — two is more than enough.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Game rule: “If you have a key AND a torch, open the cave.” Who can open it?",
        options: ["Tia: key only", "Raj: torch only", "Zoya: key and torch", "Neel: neither"],
        correctIndex: 2,
        explanation: "Only Zoya has both the key and the torch, which AND needs.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Party rule: bring juice OR sweets, AND do NOT come late. Pooja brings sweets and comes on time. Can she enter?",
        options: [
          "No — she didn’t bring juice",
          "Yes — she has sweets and she is not late",
          "No — she needs both juice and sweets",
          "Only if she comes late",
        ],
        correctIndex: 1,
        explanation: "Sweets makes the OR part true, and being on time makes NOT late true — both parts pass.",
      },
    ],
  },

  C8: {
    notes: {
      bigIdea:
        "We compare numbers with three signs: greater than (>), less than (<) and equal (=). Sorting means putting things in order, smallest to biggest or biggest to smallest. Computers sort lists so they can find things faster.",
      definitions: [
        { term: "Greater than (>)", meaning: "The first number is bigger. 9 > 4." },
        { term: "Less than (<)", meaning: "The first number is smaller. 3 < 8." },
        { term: "Equal (=)", meaning: "Both are the same. 7 = 7." },
        { term: "Sort", meaning: "Put things in order, like smallest to biggest." },
      ],
      panels: [
        {
          title: "Compare two numbers",
          body: [
            "Look at the biggest place first: 36 vs 63 → 3 tens < 6 tens, so 36 < 63.",
            "Same tens? Check ones: 45 vs 48 → 45 < 48.",
            "Class 4–5: 305 vs 350 → same hundreds, 0 tens < 5 tens, so 305 < 350.",
          ],
        },
        {
          title: "The crocodile trick",
          body: [
            "The open mouth of > or < eats the bigger number.",
            "15 > 12 → the mouth faces 15.",
            "8 < 10 → the mouth faces 10.",
          ],
        },
        {
          title: "Sort a toy collection",
          body: [
            "Toy cars: 12, 5, 30, 21, 9.",
            "Smallest to biggest: 5, 9, 12, 21, 30.",
            "Tip: find the smallest, write it, cross it out, repeat.",
          ],
        },
        {
          title: "Why computers sort",
          body: [
            "A sorted class list (roll numbers 1, 2, 3…) is quick to search.",
            "Looking for roll number 27? Jump near the end, not the start.",
            "Same numbers twice? Keep both: 7, 7 stay in the list.",
          ],
        },
      ],
      remember: [
        "> greater · < less · = equal.",
        "Compare the biggest place first.",
        "Sort: find the smallest, then the next.",
        "Sorted lists are faster to search.",
      ],
      checkYourself: {
        q: "Put 19, 7, 42, 7 in order from smallest to biggest.",
        a: "7, 7, 19, 42. Both 7s stay in the list.",
      },
      dinoLine: "Chapter 3 done. You can compare and sort like a computer — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which sign means “greater than”?",
        options: [">", "<", "=", "+"],
        correctIndex: 0,
        explanation: "> means greater than — the open mouth faces the bigger number.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which of these is true?",
        options: ["9 < 4", "15 > 12", "20 = 21", "8 > 10"],
        correctIndex: 1,
        explanation: "15 is bigger than 12, so 15 > 12 is true.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Pick the right sign: 36 __ 63",
        options: [">", "=", "<", "+"],
        correctIndex: 2,
        explanation: "3 tens is less than 6 tens, so 36 < 63.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "Computers sort things so they can find them faster.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "A sorted list is much quicker to search.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Put in order from smallest to biggest: 25, 8, 17",
        options: ["25, 17, 8", "17, 8, 25", "8, 25, 17", "8, 17, 25"],
        correctIndex: 3,
        explanation: "8 is smallest, then 17, then 25.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Toy car counts: 12, 5, 30, 21, 9. Which is the biggest?",
        options: ["21", "30", "12", "9"],
        correctIndex: 1,
        explanation: "30 has the most tens (3 tens), so it is the biggest.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Which list is sorted from biggest to smallest?",
        options: ["6, 19, 31, 42, 50", "42, 50, 31, 19, 6", "50, 42, 31, 19, 6", "50, 31, 42, 6, 19"],
        correctIndex: 2,
        explanation: "50 > 42 > 31 > 19 > 6 — each number is smaller than the one before.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Pick the right sign: 305 __ 350",
        options: [">", "<", "=", "×"],
        correctIndex: 1,
        explanation: "Same hundreds; 0 tens is less than 5 tens, so 305 < 350.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Put 14, 3, 27, 3 in order from smallest to biggest.",
        options: ["3, 14, 27", "3, 3, 14, 27", "27, 14, 3, 3", "3, 14, 3, 27"],
        correctIndex: 1,
        explanation: "Keep both 3s: 3, 3, 14, 27.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Pencils of 9 cm, 14 cm, 6 cm, 11 cm and 8 cm are sorted smallest to biggest. Which one is in the middle?",
        options: ["11 cm", "14 cm", "6 cm", "9 cm"],
        correctIndex: 3,
        explanation: "Sorted: 6, 8, 9, 11, 14 — the middle (3rd) one is 9 cm.",
      },
    ],
  },

  C9: {
    notes: {
      bigIdea:
        "A set is a group of things that belong together, like fruits or sports. A Venn diagram uses circles to sort things. Where two circles overlap, we put things that belong to BOTH sets.",
      definitions: [
        { term: "Set", meaning: "A group of things that belong together, like “fruits” or “things in my school bag”." },
        { term: "Member", meaning: "One thing inside a set. Mango is a member of the set “fruits”." },
        { term: "Venn diagram", meaning: "Circles that show sets. Each circle is one set." },
        { term: "Overlap (both)", meaning: "The middle part where circles meet — for things in both sets." },
      ],
      panels: [
        {
          title: "What belongs?",
          body: [
            "Set “fruits”: mango, banana, apple, guava.",
            "Set “sports”: cricket, kabaddi, football.",
            "Samosa is not a sport — it does not belong in that set!",
          ],
        },
        {
          title: "Two circles",
          body: [
            "Circle A: red things. Circle B: round things.",
            "Red ball → middle (red AND round).",
            "Red toy car → only A. Orange ball → only B.",
          ],
        },
        {
          title: "Outside the circles",
          body: [
            "Yellow banana: not red, not round.",
            "It goes outside both circles — “neither”.",
            "Every item has one spot: A only, B only, both, or neither.",
          ],
        },
        {
          title: "School bag sets",
          body: [
            "Circle A: things you write with. Circle B: things made of wood.",
            "Pencil → both. Pen → only A. Ruler (wooden) → only B.",
            "Water bottle → neither.",
          ],
        },
      ],
      remember: [
        "A set is a group that belongs together.",
        "Each circle is one set.",
        "Middle = in both sets.",
        "Outside = in neither set.",
      ],
      checkYourself: {
        q: "Circles: ‘red things’ and ‘things you eat’. Where does an apple go?",
        a: "In the middle, because an apple is red AND you can eat it.",
      },
      dinoLine: "Chapter 4 done. You can sort things into sets and Venn circles — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What is a set?",
        options: ["A group of things that belong together", "Just one single thing", "A kind of number", "A TV show"],
        correctIndex: 0,
        explanation: "A set is a group of things that belong together, like fruits.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which item belongs in the set “fruits”?",
        options: ["Bat", "Mango", "Pencil", "Bus"],
        correctIndex: 1,
        explanation: "A mango is a fruit. The others are not.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "Which one does NOT belong in the set “sports”?",
        options: ["Cricket", "Kabaddi", "Football", "Samosa"],
        correctIndex: 3,
        explanation: "Samosa is a snack, not a sport.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "In a Venn diagram, the middle part where the circles overlap is for things in BOTH sets.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "The overlap holds things that belong to both circles.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Circles: “red things” and “round things”. Where does a red ball go?",
        options: ["Only red things", "Only round things", "In the middle — both", "Outside both circles"],
        correctIndex: 2,
        explanation: "A red ball is red AND round, so it goes in the middle.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Circles: “red things” and “round things”. Where does a yellow banana go?",
        options: ["Only red things", "Outside both circles", "In the middle", "Only round things"],
        correctIndex: 1,
        explanation: "A banana is not red and not round, so it goes outside — neither.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Circles: “yellow things” and “things you eat”. Where does a yellow school bus go?",
        options: ["Only yellow things", "Only things you eat", "In the middle", "Outside both circles"],
        correctIndex: 0,
        explanation: "The bus is yellow, but you can’t eat it — so only the yellow circle.",
      },
      {
        difficulty: "medium",
        type: "true_false",
        prompt: "A red toy car goes in the middle of “red things” and “things you eat”.",
        options: ["True", "False"],
        correctIndex: 1,
        explanation: "It is red, but you can’t eat it — so it goes only in “red things”.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Circles: “games played with a ball” and “games played in a team”. Which goes in the middle?",
        options: ["Running race", "Chess", "Swimming", "Football"],
        correctIndex: 3,
        explanation: "Football uses a ball AND is played in a team, so it belongs in both.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Set A: 2, 4, 6, 8. Set B: 3, 6, 9. Which number is in BOTH sets?",
        options: ["4", "9", "6", "3"],
        correctIndex: 2,
        explanation: "6 is in Set A and in Set B, so it goes in the middle.",
      },
    ],
  },

  C10: {
    notes: {
      bigIdea:
        "Logic puzzles are solved one clue at a time. Use a clue, cross out what can’t be true, then use the next clue. Writing down the clues you used helps you check your answer.",
      definitions: [
        { term: "Clue", meaning: "A small fact that helps you solve the puzzle, like “Meera is last.”" },
        { term: "Logic puzzle", meaning: "A puzzle you solve by thinking step by step, not by guessing." },
        { term: "Sudoku-lite", meaning: "A 4×4 grid where each row and column has 1, 2, 3, 4 (or 4 shapes) exactly once." },
        { term: "Strategy", meaning: "Your plan: use one clue, then the next, and cross out what’s impossible." },
      ],
      panels: [
        {
          title: "One clue at a time",
          body: [
            "Three children: Ravi, Meera, Neha. Seats 1, 2, 3.",
            "Clue 1: Meera is last → Meera in seat 3.",
            "Clue 2: Ravi is not first → Ravi in seat 2. So Neha is first!",
          ],
        },
        {
          title: "Who owns the hat?",
          body: [
            "Kids: Riya, Sam, Tara. Things: hat, bag, bottle.",
            "Sam owns the bag. Riya has no hat → Riya has the bottle.",
            "Only the hat and Tara are left → Tara owns the hat.",
          ],
        },
        {
          title: "Sudoku-lite 4×4",
          body: [
            "Each row and column needs 1, 2, 3, 4 once — no repeats.",
            "Row: 3, __, 1, 2 → which is missing? 4!",
            "Shapes work too: ★ ● ▲ ■, each once per row.",
          ],
        },
        {
          title: "Write your clues",
          body: [
            "Next to each answer, write the clue that gave it.",
            "“Seat 3 = Meera (clue 1).”",
            "If something doesn’t fit, you can find where you slipped.",
          ],
        },
      ],
      remember: [
        "Use one clue at a time.",
        "Cross out what can’t be true.",
        "Sudoku-lite: each number once per row and column.",
        "Write down the clues you used.",
      ],
      checkYourself: {
        q: "Ravi is not first. Meera is last. Who can be first? (3 children)",
        a: "The third child. Meera is last, and Ravi is not first — so the only one left for first place is the other child (for example, Neha).",
      },
      dinoLine: "Chapter 5 done. You can solve puzzles one clue at a time — super work, champ!",
    },
    quiz: [
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "What is the best way to solve a logic puzzle?",
        options: ["Guess quickly", "Use one clue at a time", "Skip the clues", "Pick the longest answer"],
        correctIndex: 1,
        explanation: "Use a clue, cross out what can’t be true, then use the next clue.",
      },
      {
        difficulty: "easy",
        type: "true_false",
        prompt: "Writing down the clues you used helps you check your answer.",
        options: ["True", "False"],
        correctIndex: 0,
        explanation: "Written clues show your steps, so you can spot any mistake.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "In a 4×4 Sudoku-lite, each row must have…",
        options: [
          "the same shape 4 times",
          "any shapes you like",
          "each of the 4 shapes (or numbers 1–4) once",
          "only circles",
        ],
        correctIndex: 2,
        explanation: "No repeats: every row has each shape or number exactly once.",
      },
      {
        difficulty: "easy",
        type: "mcq",
        prompt: "There are 3 seats in a row. Clue: “Dev is last.” Which seat is Dev in?",
        options: ["Seat 3", "Seat 1", "Seat 2", "No seat"],
        correctIndex: 0,
        explanation: "With 3 seats, last means seat 3.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Sudoku-lite row: 1, 2, __, 4. What goes in the blank?",
        options: ["1", "3", "2", "4"],
        correctIndex: 1,
        explanation: "The row needs 1, 2, 3, 4 once each — 3 is missing.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Clue 1: Pinky is taller than Golu. Clue 2: Golu is taller than Tinku. Who is the shortest?",
        options: ["Pinky", "Golu", "Tinku", "We can’t tell"],
        correctIndex: 2,
        explanation: "Pinky > Golu > Tinku in height, so Tinku is the shortest.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Shape row (each of ★ ● ▲ ■ once): ★, ●, ▲, __. What is missing?",
        options: ["▲", "●", "★", "■"],
        correctIndex: 3,
        explanation: "★, ● and ▲ are used, so the square ■ is missing.",
      },
      {
        difficulty: "medium",
        type: "mcq",
        prompt: "Kids: Riya, Sam, Tara. Things: hat, bag, bottle (one each). Sam owns the bag. Riya has no hat. Who owns the hat?",
        options: ["Tara", "Riya", "Sam", "Nobody"],
        correctIndex: 0,
        explanation: "Sam has the bag, so Riya must have the bottle — that leaves the hat for Tara.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Kiran, Lata and Om stand in a line. Lata is last. Kiran is not first. What is the order?",
        options: ["Kiran, Om, Lata", "Om, Kiran, Lata", "Om, Lata, Kiran", "Lata, Kiran, Om"],
        correctIndex: 1,
        explanation: "Lata is 3rd. Kiran can’t be 1st, so Kiran is 2nd and Om is 1st.",
      },
      {
        difficulty: "hard",
        type: "mcq",
        prompt: "Sudoku-lite: Row 1 is 1, 2, 3, 4. Row 2 is 3, 4, __, 2. What goes in the blank?",
        options: ["1", "3", "2", "4"],
        correctIndex: 0,
        explanation: "Row 2 already has 3, 4 and 2, so it needs 1 — and 1 is not above it in that column (that’s a 3).",
      },
    ],
  },
};
